// Code generated by ent, DO NOT EDIT.

package series

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the series type in the database.
	Label = "series"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldThumbnailURL holds the string denoting the thumbnail_url field in the database.
	FieldThumbnailURL = "thumbnail_url"
	// FieldArtist holds the string denoting the artist field in the database.
	FieldArtist = "artist"
	// FieldAuthor holds the string denoting the author field in the database.
	FieldAuthor = "author"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldGenre holds the string denoting the genre field in the database.
	FieldGenre = "genre"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldStoragePath holds the string denoting the storage_path field in the database.
	FieldStoragePath = "storage_path"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldChapterCount holds the string denoting the chapter_count field in the database.
	FieldChapterCount = "chapter_count"
	// FieldPauseDownloads holds the string denoting the pause_downloads field in the database.
	FieldPauseDownloads = "pause_downloads"
	// EdgeProviders holds the string denoting the providers edge name in mutations.
	EdgeProviders = "providers"
	// EdgeLatestSeries holds the string denoting the latest_series edge name in mutations.
	EdgeLatestSeries = "latest_series"
	// Table holds the table name of the series in the database.
	Table = "series"
	// ProvidersTable is the table that holds the providers relation/edge.
	ProvidersTable = "series_providers"
	// ProvidersInverseTable is the table name for the SeriesProvider entity.
	// It exists in this package in order to avoid circular dependency with the "seriesprovider" package.
	ProvidersInverseTable = "series_providers"
	// ProvidersColumn is the table column denoting the providers relation/edge.
	ProvidersColumn = "series_id"
	// LatestSeriesTable is the table that holds the latest_series relation/edge.
	LatestSeriesTable = "latest_series"
	// LatestSeriesInverseTable is the table name for the LatestSeries entity.
	// It exists in this package in order to avoid circular dependency with the "latestseries" package.
	LatestSeriesInverseTable = "latest_series"
	// LatestSeriesColumn is the table column denoting the latest_series relation/edge.
	LatestSeriesColumn = "series_id"
)

// Columns holds all SQL columns for series fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldThumbnailURL,
	FieldArtist,
	FieldAuthor,
	FieldDescription,
	FieldGenre,
	FieldStatus,
	FieldStoragePath,
	FieldType,
	FieldChapterCount,
	FieldPauseDownloads,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultThumbnailURL holds the default value on creation for the "thumbnail_url" field.
	DefaultThumbnailURL string
	// DefaultArtist holds the default value on creation for the "artist" field.
	DefaultArtist string
	// DefaultAuthor holds the default value on creation for the "author" field.
	DefaultAuthor string
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultChapterCount holds the default value on creation for the "chapter_count" field.
	DefaultChapterCount int
	// DefaultPauseDownloads holds the default value on creation for the "pause_downloads" field.
	DefaultPauseDownloads bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Series queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByThumbnailURL orders the results by the thumbnail_url field.
func ByThumbnailURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThumbnailURL, opts...).ToFunc()
}

// ByArtist orders the results by the artist field.
func ByArtist(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArtist, opts...).ToFunc()
}

// ByAuthor orders the results by the author field.
func ByAuthor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthor, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByStoragePath orders the results by the storage_path field.
func ByStoragePath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStoragePath, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByChapterCount orders the results by the chapter_count field.
func ByChapterCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChapterCount, opts...).ToFunc()
}

// ByPauseDownloads orders the results by the pause_downloads field.
func ByPauseDownloads(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPauseDownloads, opts...).ToFunc()
}

// ByProvidersCount orders the results by providers count.
func ByProvidersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProvidersStep(), opts...)
	}
}

// ByProviders orders the results by providers terms.
func ByProviders(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProvidersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByLatestSeriesCount orders the results by latest_series count.
func ByLatestSeriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLatestSeriesStep(), opts...)
	}
}

// ByLatestSeries orders the results by latest_series terms.
func ByLatestSeries(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLatestSeriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newProvidersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProvidersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ProvidersTable, ProvidersColumn),
	)
}
func newLatestSeriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LatestSeriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LatestSeriesTable, LatestSeriesColumn),
	)
}
