// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/technobecet/kaizoku-go/internal/ent/downloadqueueitem"
	"github.com/technobecet/kaizoku-go/internal/ent/predicate"
)

// DownloadQueueItemDelete is the builder for deleting a DownloadQueueItem entity.
type DownloadQueueItemDelete struct {
	config
	hooks    []Hook
	mutation *DownloadQueueItemMutation
}

// Where appends a list predicates to the DownloadQueueItemDelete builder.
func (_d *DownloadQueueItemDelete) Where(ps ...predicate.DownloadQueueItem) *DownloadQueueItemDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DownloadQueueItemDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DownloadQueueItemDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DownloadQueueItemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(downloadqueueitem.Table, sqlgraph.NewFieldSpec(downloadqueueitem.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DownloadQueueItemDeleteOne is the builder for deleting a single DownloadQueueItem entity.
type DownloadQueueItemDeleteOne struct {
	_d *DownloadQueueItemDelete
}

// Where appends a list predicates to the DownloadQueueItemDelete builder.
func (_d *DownloadQueueItemDeleteOne) Where(ps ...predicate.DownloadQueueItem) *DownloadQueueItemDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DownloadQueueItemDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{downloadqueueitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DownloadQueueItemDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
