// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/technobecet/kaizoku-go/internal/ent/downloadqueueitem"
	"github.com/technobecet/kaizoku-go/internal/types"
)

// DownloadQueueItemCreate is the builder for creating a DownloadQueueItem entity.
type DownloadQueueItemCreate struct {
	config
	mutation *DownloadQueueItemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetGroupKey sets the "group_key" field.
func (_c *DownloadQueueItemCreate) SetGroupKey(v string) *DownloadQueueItemCreate {
	_c.mutation.SetGroupKey(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *DownloadQueueItemCreate) SetStatus(v int) *DownloadQueueItemCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DownloadQueueItemCreate) SetNillableStatus(v *int) *DownloadQueueItemCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *DownloadQueueItemCreate) SetPriority(v int) *DownloadQueueItemCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *DownloadQueueItemCreate) SetNillablePriority(v *int) *DownloadQueueItemCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetScheduledAt sets the "scheduled_at" field.
func (_c *DownloadQueueItemCreate) SetScheduledAt(v time.Time) *DownloadQueueItemCreate {
	_c.mutation.SetScheduledAt(v)
	return _c
}

// SetNillableScheduledAt sets the "scheduled_at" field if the given value is not nil.
func (_c *DownloadQueueItemCreate) SetNillableScheduledAt(v *time.Time) *DownloadQueueItemCreate {
	if v != nil {
		_c.SetScheduledAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DownloadQueueItemCreate) SetCreatedAt(v time.Time) *DownloadQueueItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DownloadQueueItemCreate) SetNillableCreatedAt(v *time.Time) *DownloadQueueItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *DownloadQueueItemCreate) SetStartedAt(v time.Time) *DownloadQueueItemCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *DownloadQueueItemCreate) SetNillableStartedAt(v *time.Time) *DownloadQueueItemCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *DownloadQueueItemCreate) SetCompletedAt(v time.Time) *DownloadQueueItemCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *DownloadQueueItemCreate) SetNillableCompletedAt(v *time.Time) *DownloadQueueItemCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetArgs sets the "args" field.
func (_c *DownloadQueueItemCreate) SetArgs(v types.DownloadChapterArgs) *DownloadQueueItemCreate {
	_c.mutation.SetArgs(v)
	return _c
}

// SetID sets the "id" field.
func (_c *DownloadQueueItemCreate) SetID(v uuid.UUID) *DownloadQueueItemCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DownloadQueueItemCreate) SetNillableID(v *uuid.UUID) *DownloadQueueItemCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the DownloadQueueItemMutation object of the builder.
func (_c *DownloadQueueItemCreate) Mutation() *DownloadQueueItemMutation {
	return _c.mutation
}

// Save creates the DownloadQueueItem in the database.
func (_c *DownloadQueueItemCreate) Save(ctx context.Context) (*DownloadQueueItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DownloadQueueItemCreate) SaveX(ctx context.Context) *DownloadQueueItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DownloadQueueItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DownloadQueueItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DownloadQueueItemCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := downloadqueueitem.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := downloadqueueitem.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.ScheduledAt(); !ok {
		v := downloadqueueitem.DefaultScheduledAt()
		_c.mutation.SetScheduledAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := downloadqueueitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := downloadqueueitem.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DownloadQueueItemCreate) check() error {
	if _, ok := _c.mutation.GroupKey(); !ok {
		return &ValidationError{Name: "group_key", err: errors.New(`ent: missing required field "DownloadQueueItem.group_key"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DownloadQueueItem.status"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "DownloadQueueItem.priority"`)}
	}
	if _, ok := _c.mutation.ScheduledAt(); !ok {
		return &ValidationError{Name: "scheduled_at", err: errors.New(`ent: missing required field "DownloadQueueItem.scheduled_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DownloadQueueItem.created_at"`)}
	}
	if _, ok := _c.mutation.Args(); !ok {
		return &ValidationError{Name: "args", err: errors.New(`ent: missing required field "DownloadQueueItem.args"`)}
	}
	return nil
}

func (_c *DownloadQueueItemCreate) sqlSave(ctx context.Context) (*DownloadQueueItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DownloadQueueItemCreate) createSpec() (*DownloadQueueItem, *sqlgraph.CreateSpec) {
	var (
		_node = &DownloadQueueItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(downloadqueueitem.Table, sqlgraph.NewFieldSpec(downloadqueueitem.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.GroupKey(); ok {
		_spec.SetField(downloadqueueitem.FieldGroupKey, field.TypeString, value)
		_node.GroupKey = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(downloadqueueitem.FieldStatus, field.TypeInt, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(downloadqueueitem.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.ScheduledAt(); ok {
		_spec.SetField(downloadqueueitem.FieldScheduledAt, field.TypeTime, value)
		_node.ScheduledAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(downloadqueueitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(downloadqueueitem.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(downloadqueueitem.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.Args(); ok {
		_spec.SetField(downloadqueueitem.FieldArgs, field.TypeJSON, value)
		_node.Args = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DownloadQueueItem.Create().
//		SetGroupKey(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DownloadQueueItemUpsert) {
//			SetGroupKey(v+v).
//		}).
//		Exec(ctx)
func (_c *DownloadQueueItemCreate) OnConflict(opts ...sql.ConflictOption) *DownloadQueueItemUpsertOne {
	_c.conflict = opts
	return &DownloadQueueItemUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DownloadQueueItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DownloadQueueItemCreate) OnConflictColumns(columns ...string) *DownloadQueueItemUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DownloadQueueItemUpsertOne{
		create: _c,
	}
}

type (
	// DownloadQueueItemUpsertOne is the builder for "upsert"-ing
	//  one DownloadQueueItem node.
	DownloadQueueItemUpsertOne struct {
		create *DownloadQueueItemCreate
	}

	// DownloadQueueItemUpsert is the "OnConflict" setter.
	DownloadQueueItemUpsert struct {
		*sql.UpdateSet
	}
)

// SetGroupKey sets the "group_key" field.
func (u *DownloadQueueItemUpsert) SetGroupKey(v string) *DownloadQueueItemUpsert {
	u.Set(downloadqueueitem.FieldGroupKey, v)
	return u
}

// UpdateGroupKey sets the "group_key" field to the value that was provided on create.
func (u *DownloadQueueItemUpsert) UpdateGroupKey() *DownloadQueueItemUpsert {
	u.SetExcluded(downloadqueueitem.FieldGroupKey)
	return u
}

// SetStatus sets the "status" field.
func (u *DownloadQueueItemUpsert) SetStatus(v int) *DownloadQueueItemUpsert {
	u.Set(downloadqueueitem.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DownloadQueueItemUpsert) UpdateStatus() *DownloadQueueItemUpsert {
	u.SetExcluded(downloadqueueitem.FieldStatus)
	return u
}

// AddStatus adds v to the "status" field.
func (u *DownloadQueueItemUpsert) AddStatus(v int) *DownloadQueueItemUpsert {
	u.Add(downloadqueueitem.FieldStatus, v)
	return u
}

// SetPriority sets the "priority" field.
func (u *DownloadQueueItemUpsert) SetPriority(v int) *DownloadQueueItemUpsert {
	u.Set(downloadqueueitem.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *DownloadQueueItemUpsert) UpdatePriority() *DownloadQueueItemUpsert {
	u.SetExcluded(downloadqueueitem.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *DownloadQueueItemUpsert) AddPriority(v int) *DownloadQueueItemUpsert {
	u.Add(downloadqueueitem.FieldPriority, v)
	return u
}

// SetScheduledAt sets the "scheduled_at" field.
func (u *DownloadQueueItemUpsert) SetScheduledAt(v time.Time) *DownloadQueueItemUpsert {
	u.Set(downloadqueueitem.FieldScheduledAt, v)
	return u
}

// UpdateScheduledAt sets the "scheduled_at" field to the value that was provided on create.
func (u *DownloadQueueItemUpsert) UpdateScheduledAt() *DownloadQueueItemUpsert {
	u.SetExcluded(downloadqueueitem.FieldScheduledAt)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *DownloadQueueItemUpsert) SetStartedAt(v time.Time) *DownloadQueueItemUpsert {
	u.Set(downloadqueueitem.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *DownloadQueueItemUpsert) UpdateStartedAt() *DownloadQueueItemUpsert {
	u.SetExcluded(downloadqueueitem.FieldStartedAt)
	return u
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *DownloadQueueItemUpsert) ClearStartedAt() *DownloadQueueItemUpsert {
	u.SetNull(downloadqueueitem.FieldStartedAt)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *DownloadQueueItemUpsert) SetCompletedAt(v time.Time) *DownloadQueueItemUpsert {
	u.Set(downloadqueueitem.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *DownloadQueueItemUpsert) UpdateCompletedAt() *DownloadQueueItemUpsert {
	u.SetExcluded(downloadqueueitem.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *DownloadQueueItemUpsert) ClearCompletedAt() *DownloadQueueItemUpsert {
	u.SetNull(downloadqueueitem.FieldCompletedAt)
	return u
}

// SetArgs sets the "args" field.
func (u *DownloadQueueItemUpsert) SetArgs(v types.DownloadChapterArgs) *DownloadQueueItemUpsert {
	u.Set(downloadqueueitem.FieldArgs, v)
	return u
}

// UpdateArgs sets the "args" field to the value that was provided on create.
func (u *DownloadQueueItemUpsert) UpdateArgs() *DownloadQueueItemUpsert {
	u.SetExcluded(downloadqueueitem.FieldArgs)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.DownloadQueueItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(downloadqueueitem.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DownloadQueueItemUpsertOne) UpdateNewValues() *DownloadQueueItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(downloadqueueitem.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(downloadqueueitem.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DownloadQueueItem.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DownloadQueueItemUpsertOne) Ignore() *DownloadQueueItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DownloadQueueItemUpsertOne) DoNothing() *DownloadQueueItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DownloadQueueItemCreate.OnConflict
// documentation for more info.
func (u *DownloadQueueItemUpsertOne) Update(set func(*DownloadQueueItemUpsert)) *DownloadQueueItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DownloadQueueItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetGroupKey sets the "group_key" field.
func (u *DownloadQueueItemUpsertOne) SetGroupKey(v string) *DownloadQueueItemUpsertOne {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.SetGroupKey(v)
	})
}

// UpdateGroupKey sets the "group_key" field to the value that was provided on create.
func (u *DownloadQueueItemUpsertOne) UpdateGroupKey() *DownloadQueueItemUpsertOne {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.UpdateGroupKey()
	})
}

// SetStatus sets the "status" field.
func (u *DownloadQueueItemUpsertOne) SetStatus(v int) *DownloadQueueItemUpsertOne {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *DownloadQueueItemUpsertOne) AddStatus(v int) *DownloadQueueItemUpsertOne {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DownloadQueueItemUpsertOne) UpdateStatus() *DownloadQueueItemUpsertOne {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.UpdateStatus()
	})
}

// SetPriority sets the "priority" field.
func (u *DownloadQueueItemUpsertOne) SetPriority(v int) *DownloadQueueItemUpsertOne {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *DownloadQueueItemUpsertOne) AddPriority(v int) *DownloadQueueItemUpsertOne {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *DownloadQueueItemUpsertOne) UpdatePriority() *DownloadQueueItemUpsertOne {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.UpdatePriority()
	})
}

// SetScheduledAt sets the "scheduled_at" field.
func (u *DownloadQueueItemUpsertOne) SetScheduledAt(v time.Time) *DownloadQueueItemUpsertOne {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.SetScheduledAt(v)
	})
}

// UpdateScheduledAt sets the "scheduled_at" field to the value that was provided on create.
func (u *DownloadQueueItemUpsertOne) UpdateScheduledAt() *DownloadQueueItemUpsertOne {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.UpdateScheduledAt()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *DownloadQueueItemUpsertOne) SetStartedAt(v time.Time) *DownloadQueueItemUpsertOne {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *DownloadQueueItemUpsertOne) UpdateStartedAt() *DownloadQueueItemUpsertOne {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *DownloadQueueItemUpsertOne) ClearStartedAt() *DownloadQueueItemUpsertOne {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.ClearStartedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *DownloadQueueItemUpsertOne) SetCompletedAt(v time.Time) *DownloadQueueItemUpsertOne {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *DownloadQueueItemUpsertOne) UpdateCompletedAt() *DownloadQueueItemUpsertOne {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *DownloadQueueItemUpsertOne) ClearCompletedAt() *DownloadQueueItemUpsertOne {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.ClearCompletedAt()
	})
}

// SetArgs sets the "args" field.
func (u *DownloadQueueItemUpsertOne) SetArgs(v types.DownloadChapterArgs) *DownloadQueueItemUpsertOne {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.SetArgs(v)
	})
}

// UpdateArgs sets the "args" field to the value that was provided on create.
func (u *DownloadQueueItemUpsertOne) UpdateArgs() *DownloadQueueItemUpsertOne {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.UpdateArgs()
	})
}

// Exec executes the query.
func (u *DownloadQueueItemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DownloadQueueItemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DownloadQueueItemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DownloadQueueItemUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: DownloadQueueItemUpsertOne.ID is not supported by MySQL driver. Use DownloadQueueItemUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DownloadQueueItemUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DownloadQueueItemCreateBulk is the builder for creating many DownloadQueueItem entities in bulk.
type DownloadQueueItemCreateBulk struct {
	config
	err      error
	builders []*DownloadQueueItemCreate
	conflict []sql.ConflictOption
}

// Save creates the DownloadQueueItem entities in the database.
func (_c *DownloadQueueItemCreateBulk) Save(ctx context.Context) ([]*DownloadQueueItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DownloadQueueItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DownloadQueueItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DownloadQueueItemCreateBulk) SaveX(ctx context.Context) []*DownloadQueueItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DownloadQueueItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DownloadQueueItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DownloadQueueItem.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DownloadQueueItemUpsert) {
//			SetGroupKey(v+v).
//		}).
//		Exec(ctx)
func (_c *DownloadQueueItemCreateBulk) OnConflict(opts ...sql.ConflictOption) *DownloadQueueItemUpsertBulk {
	_c.conflict = opts
	return &DownloadQueueItemUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DownloadQueueItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DownloadQueueItemCreateBulk) OnConflictColumns(columns ...string) *DownloadQueueItemUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DownloadQueueItemUpsertBulk{
		create: _c,
	}
}

// DownloadQueueItemUpsertBulk is the builder for "upsert"-ing
// a bulk of DownloadQueueItem nodes.
type DownloadQueueItemUpsertBulk struct {
	create *DownloadQueueItemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DownloadQueueItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(downloadqueueitem.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *DownloadQueueItemUpsertBulk) UpdateNewValues() *DownloadQueueItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(downloadqueueitem.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(downloadqueueitem.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DownloadQueueItem.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DownloadQueueItemUpsertBulk) Ignore() *DownloadQueueItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DownloadQueueItemUpsertBulk) DoNothing() *DownloadQueueItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DownloadQueueItemCreateBulk.OnConflict
// documentation for more info.
func (u *DownloadQueueItemUpsertBulk) Update(set func(*DownloadQueueItemUpsert)) *DownloadQueueItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DownloadQueueItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetGroupKey sets the "group_key" field.
func (u *DownloadQueueItemUpsertBulk) SetGroupKey(v string) *DownloadQueueItemUpsertBulk {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.SetGroupKey(v)
	})
}

// UpdateGroupKey sets the "group_key" field to the value that was provided on create.
func (u *DownloadQueueItemUpsertBulk) UpdateGroupKey() *DownloadQueueItemUpsertBulk {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.UpdateGroupKey()
	})
}

// SetStatus sets the "status" field.
func (u *DownloadQueueItemUpsertBulk) SetStatus(v int) *DownloadQueueItemUpsertBulk {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *DownloadQueueItemUpsertBulk) AddStatus(v int) *DownloadQueueItemUpsertBulk {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DownloadQueueItemUpsertBulk) UpdateStatus() *DownloadQueueItemUpsertBulk {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.UpdateStatus()
	})
}

// SetPriority sets the "priority" field.
func (u *DownloadQueueItemUpsertBulk) SetPriority(v int) *DownloadQueueItemUpsertBulk {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *DownloadQueueItemUpsertBulk) AddPriority(v int) *DownloadQueueItemUpsertBulk {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *DownloadQueueItemUpsertBulk) UpdatePriority() *DownloadQueueItemUpsertBulk {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.UpdatePriority()
	})
}

// SetScheduledAt sets the "scheduled_at" field.
func (u *DownloadQueueItemUpsertBulk) SetScheduledAt(v time.Time) *DownloadQueueItemUpsertBulk {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.SetScheduledAt(v)
	})
}

// UpdateScheduledAt sets the "scheduled_at" field to the value that was provided on create.
func (u *DownloadQueueItemUpsertBulk) UpdateScheduledAt() *DownloadQueueItemUpsertBulk {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.UpdateScheduledAt()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *DownloadQueueItemUpsertBulk) SetStartedAt(v time.Time) *DownloadQueueItemUpsertBulk {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *DownloadQueueItemUpsertBulk) UpdateStartedAt() *DownloadQueueItemUpsertBulk {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *DownloadQueueItemUpsertBulk) ClearStartedAt() *DownloadQueueItemUpsertBulk {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.ClearStartedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *DownloadQueueItemUpsertBulk) SetCompletedAt(v time.Time) *DownloadQueueItemUpsertBulk {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *DownloadQueueItemUpsertBulk) UpdateCompletedAt() *DownloadQueueItemUpsertBulk {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *DownloadQueueItemUpsertBulk) ClearCompletedAt() *DownloadQueueItemUpsertBulk {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.ClearCompletedAt()
	})
}

// SetArgs sets the "args" field.
func (u *DownloadQueueItemUpsertBulk) SetArgs(v types.DownloadChapterArgs) *DownloadQueueItemUpsertBulk {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.SetArgs(v)
	})
}

// UpdateArgs sets the "args" field to the value that was provided on create.
func (u *DownloadQueueItemUpsertBulk) UpdateArgs() *DownloadQueueItemUpsertBulk {
	return u.Update(func(s *DownloadQueueItemUpsert) {
		s.UpdateArgs()
	})
}

// Exec executes the query.
func (u *DownloadQueueItemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DownloadQueueItemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DownloadQueueItemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DownloadQueueItemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
