// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/technobecet/kaizoku-go/internal/ent/etagcache"
	"github.com/technobecet/kaizoku-go/internal/ent/predicate"
)

// EtagCacheUpdate is the builder for updating EtagCache entities.
type EtagCacheUpdate struct {
	config
	hooks    []Hook
	mutation *EtagCacheMutation
}

// Where appends a list predicates to the EtagCacheUpdate builder.
func (_u *EtagCacheUpdate) Where(ps ...predicate.EtagCache) *EtagCacheUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEtag sets the "etag" field.
func (_u *EtagCacheUpdate) SetEtag(v string) *EtagCacheUpdate {
	_u.mutation.SetEtag(v)
	return _u
}

// SetNillableEtag sets the "etag" field if the given value is not nil.
func (_u *EtagCacheUpdate) SetNillableEtag(v *string) *EtagCacheUpdate {
	if v != nil {
		_u.SetEtag(*v)
	}
	return _u
}

// SetLastUpdated sets the "last_updated" field.
func (_u *EtagCacheUpdate) SetLastUpdated(v time.Time) *EtagCacheUpdate {
	_u.mutation.SetLastUpdated(v)
	return _u
}

// SetNillableLastUpdated sets the "last_updated" field if the given value is not nil.
func (_u *EtagCacheUpdate) SetNillableLastUpdated(v *time.Time) *EtagCacheUpdate {
	if v != nil {
		_u.SetLastUpdated(*v)
	}
	return _u
}

// Mutation returns the EtagCacheMutation object of the builder.
func (_u *EtagCacheUpdate) Mutation() *EtagCacheMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EtagCacheUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EtagCacheUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EtagCacheUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EtagCacheUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *EtagCacheUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(etagcache.Table, etagcache.Columns, sqlgraph.NewFieldSpec(etagcache.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Etag(); ok {
		_spec.SetField(etagcache.FieldEtag, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastUpdated(); ok {
		_spec.SetField(etagcache.FieldLastUpdated, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{etagcache.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EtagCacheUpdateOne is the builder for updating a single EtagCache entity.
type EtagCacheUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EtagCacheMutation
}

// SetEtag sets the "etag" field.
func (_u *EtagCacheUpdateOne) SetEtag(v string) *EtagCacheUpdateOne {
	_u.mutation.SetEtag(v)
	return _u
}

// SetNillableEtag sets the "etag" field if the given value is not nil.
func (_u *EtagCacheUpdateOne) SetNillableEtag(v *string) *EtagCacheUpdateOne {
	if v != nil {
		_u.SetEtag(*v)
	}
	return _u
}

// SetLastUpdated sets the "last_updated" field.
func (_u *EtagCacheUpdateOne) SetLastUpdated(v time.Time) *EtagCacheUpdateOne {
	_u.mutation.SetLastUpdated(v)
	return _u
}

// SetNillableLastUpdated sets the "last_updated" field if the given value is not nil.
func (_u *EtagCacheUpdateOne) SetNillableLastUpdated(v *time.Time) *EtagCacheUpdateOne {
	if v != nil {
		_u.SetLastUpdated(*v)
	}
	return _u
}

// Mutation returns the EtagCacheMutation object of the builder.
func (_u *EtagCacheUpdateOne) Mutation() *EtagCacheMutation {
	return _u.mutation
}

// Where appends a list predicates to the EtagCacheUpdate builder.
func (_u *EtagCacheUpdateOne) Where(ps ...predicate.EtagCache) *EtagCacheUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EtagCacheUpdateOne) Select(field string, fields ...string) *EtagCacheUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EtagCache entity.
func (_u *EtagCacheUpdateOne) Save(ctx context.Context) (*EtagCache, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EtagCacheUpdateOne) SaveX(ctx context.Context) *EtagCache {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EtagCacheUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EtagCacheUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *EtagCacheUpdateOne) sqlSave(ctx context.Context) (_node *EtagCache, err error) {
	_spec := sqlgraph.NewUpdateSpec(etagcache.Table, etagcache.Columns, sqlgraph.NewFieldSpec(etagcache.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EtagCache.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, etagcache.FieldID)
		for _, f := range fields {
			if !etagcache.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != etagcache.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Etag(); ok {
		_spec.SetField(etagcache.FieldEtag, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastUpdated(); ok {
		_spec.SetField(etagcache.FieldLastUpdated, field.TypeTime, value)
	}
	_node = &EtagCache{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{etagcache.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
