// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/technobecet/kaizoku-go/internal/ent/importentry"
	"github.com/technobecet/kaizoku-go/internal/types"
)

// ImportEntry is the model entity for the ImportEntry schema.
type ImportEntry struct {
	config `json:"-"`
	// ID of the ent.
	// Path is the PK
	ID string `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Status holds the value of the "status" field.
	Status int `json:"status,omitempty"`
	// Action holds the value of the "action" field.
	Action int `json:"action,omitempty"`
	// Info holds the value of the "info" field.
	Info *types.KaizokuInfo `json:"info,omitempty"`
	// Series holds the value of the "series" field.
	Series []map[string]interface{} `json:"series,omitempty"`
	// ContinueAfterChapter holds the value of the "continue_after_chapter" field.
	ContinueAfterChapter *float64 `json:"continue_after_chapter,omitempty"`
	selectValues         sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ImportEntry) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case importentry.FieldInfo, importentry.FieldSeries:
			values[i] = new([]byte)
		case importentry.FieldContinueAfterChapter:
			values[i] = new(sql.NullFloat64)
		case importentry.FieldStatus, importentry.FieldAction:
			values[i] = new(sql.NullInt64)
		case importentry.FieldID, importentry.FieldTitle:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ImportEntry fields.
func (_m *ImportEntry) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case importentry.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case importentry.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case importentry.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = int(value.Int64)
			}
		case importentry.FieldAction:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = int(value.Int64)
			}
		case importentry.FieldInfo:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field info", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Info); err != nil {
					return fmt.Errorf("unmarshal field info: %w", err)
				}
			}
		case importentry.FieldSeries:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field series", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Series); err != nil {
					return fmt.Errorf("unmarshal field series: %w", err)
				}
			}
		case importentry.FieldContinueAfterChapter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field continue_after_chapter", values[i])
			} else if value.Valid {
				_m.ContinueAfterChapter = new(float64)
				*_m.ContinueAfterChapter = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ImportEntry.
// This includes values selected through modifiers, order, etc.
func (_m *ImportEntry) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ImportEntry.
// Note that you need to call ImportEntry.Unwrap() before calling this method if this ImportEntry
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ImportEntry) Update() *ImportEntryUpdateOne {
	return NewImportEntryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ImportEntry entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ImportEntry) Unwrap() *ImportEntry {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ImportEntry is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ImportEntry) String() string {
	var builder strings.Builder
	builder.WriteString("ImportEntry(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(fmt.Sprintf("%v", _m.Action))
	builder.WriteString(", ")
	builder.WriteString("info=")
	builder.WriteString(fmt.Sprintf("%v", _m.Info))
	builder.WriteString(", ")
	builder.WriteString("series=")
	builder.WriteString(fmt.Sprintf("%v", _m.Series))
	builder.WriteString(", ")
	if v := _m.ContinueAfterChapter; v != nil {
		builder.WriteString("continue_after_chapter=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ImportEntries is a parsable slice of ImportEntry.
type ImportEntries []*ImportEntry
