// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/technobecet/kaizoku-go/internal/ent/importentry"
	"github.com/technobecet/kaizoku-go/internal/types"
)

// ImportEntryCreate is the builder for creating a ImportEntry entity.
type ImportEntryCreate struct {
	config
	mutation *ImportEntryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTitle sets the "title" field.
func (_c *ImportEntryCreate) SetTitle(v string) *ImportEntryCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ImportEntryCreate) SetStatus(v int) *ImportEntryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ImportEntryCreate) SetNillableStatus(v *int) *ImportEntryCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *ImportEntryCreate) SetAction(v int) *ImportEntryCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_c *ImportEntryCreate) SetNillableAction(v *int) *ImportEntryCreate {
	if v != nil {
		_c.SetAction(*v)
	}
	return _c
}

// SetInfo sets the "info" field.
func (_c *ImportEntryCreate) SetInfo(v *types.KaizokuInfo) *ImportEntryCreate {
	_c.mutation.SetInfo(v)
	return _c
}

// SetSeries sets the "series" field.
func (_c *ImportEntryCreate) SetSeries(v []map[string]interface{}) *ImportEntryCreate {
	_c.mutation.SetSeries(v)
	return _c
}

// SetContinueAfterChapter sets the "continue_after_chapter" field.
func (_c *ImportEntryCreate) SetContinueAfterChapter(v float64) *ImportEntryCreate {
	_c.mutation.SetContinueAfterChapter(v)
	return _c
}

// SetNillableContinueAfterChapter sets the "continue_after_chapter" field if the given value is not nil.
func (_c *ImportEntryCreate) SetNillableContinueAfterChapter(v *float64) *ImportEntryCreate {
	if v != nil {
		_c.SetContinueAfterChapter(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ImportEntryCreate) SetID(v string) *ImportEntryCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ImportEntryMutation object of the builder.
func (_c *ImportEntryCreate) Mutation() *ImportEntryMutation {
	return _c.mutation
}

// Save creates the ImportEntry in the database.
func (_c *ImportEntryCreate) Save(ctx context.Context) (*ImportEntry, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ImportEntryCreate) SaveX(ctx context.Context) *ImportEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImportEntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImportEntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ImportEntryCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := importentry.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Action(); !ok {
		v := importentry.DefaultAction
		_c.mutation.SetAction(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ImportEntryCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "ImportEntry.title"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ImportEntry.status"`)}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "ImportEntry.action"`)}
	}
	return nil
}

func (_c *ImportEntryCreate) sqlSave(ctx context.Context) (*ImportEntry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ImportEntry.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ImportEntryCreate) createSpec() (*ImportEntry, *sqlgraph.CreateSpec) {
	var (
		_node = &ImportEntry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(importentry.Table, sqlgraph.NewFieldSpec(importentry.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(importentry.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(importentry.FieldStatus, field.TypeInt, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(importentry.FieldAction, field.TypeInt, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.Info(); ok {
		_spec.SetField(importentry.FieldInfo, field.TypeJSON, value)
		_node.Info = value
	}
	if value, ok := _c.mutation.Series(); ok {
		_spec.SetField(importentry.FieldSeries, field.TypeJSON, value)
		_node.Series = value
	}
	if value, ok := _c.mutation.ContinueAfterChapter(); ok {
		_spec.SetField(importentry.FieldContinueAfterChapter, field.TypeFloat64, value)
		_node.ContinueAfterChapter = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImportEntry.Create().
//		SetTitle(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImportEntryUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *ImportEntryCreate) OnConflict(opts ...sql.ConflictOption) *ImportEntryUpsertOne {
	_c.conflict = opts
	return &ImportEntryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImportEntry.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImportEntryCreate) OnConflictColumns(columns ...string) *ImportEntryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImportEntryUpsertOne{
		create: _c,
	}
}

type (
	// ImportEntryUpsertOne is the builder for "upsert"-ing
	//  one ImportEntry node.
	ImportEntryUpsertOne struct {
		create *ImportEntryCreate
	}

	// ImportEntryUpsert is the "OnConflict" setter.
	ImportEntryUpsert struct {
		*sql.UpdateSet
	}
)

// SetTitle sets the "title" field.
func (u *ImportEntryUpsert) SetTitle(v string) *ImportEntryUpsert {
	u.Set(importentry.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ImportEntryUpsert) UpdateTitle() *ImportEntryUpsert {
	u.SetExcluded(importentry.FieldTitle)
	return u
}

// SetStatus sets the "status" field.
func (u *ImportEntryUpsert) SetStatus(v int) *ImportEntryUpsert {
	u.Set(importentry.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ImportEntryUpsert) UpdateStatus() *ImportEntryUpsert {
	u.SetExcluded(importentry.FieldStatus)
	return u
}

// AddStatus adds v to the "status" field.
func (u *ImportEntryUpsert) AddStatus(v int) *ImportEntryUpsert {
	u.Add(importentry.FieldStatus, v)
	return u
}

// SetAction sets the "action" field.
func (u *ImportEntryUpsert) SetAction(v int) *ImportEntryUpsert {
	u.Set(importentry.FieldAction, v)
	return u
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *ImportEntryUpsert) UpdateAction() *ImportEntryUpsert {
	u.SetExcluded(importentry.FieldAction)
	return u
}

// AddAction adds v to the "action" field.
func (u *ImportEntryUpsert) AddAction(v int) *ImportEntryUpsert {
	u.Add(importentry.FieldAction, v)
	return u
}

// SetInfo sets the "info" field.
func (u *ImportEntryUpsert) SetInfo(v *types.KaizokuInfo) *ImportEntryUpsert {
	u.Set(importentry.FieldInfo, v)
	return u
}

// UpdateInfo sets the "info" field to the value that was provided on create.
func (u *ImportEntryUpsert) UpdateInfo() *ImportEntryUpsert {
	u.SetExcluded(importentry.FieldInfo)
	return u
}

// ClearInfo clears the value of the "info" field.
func (u *ImportEntryUpsert) ClearInfo() *ImportEntryUpsert {
	u.SetNull(importentry.FieldInfo)
	return u
}

// SetSeries sets the "series" field.
func (u *ImportEntryUpsert) SetSeries(v []map[string]interface{}) *ImportEntryUpsert {
	u.Set(importentry.FieldSeries, v)
	return u
}

// UpdateSeries sets the "series" field to the value that was provided on create.
func (u *ImportEntryUpsert) UpdateSeries() *ImportEntryUpsert {
	u.SetExcluded(importentry.FieldSeries)
	return u
}

// ClearSeries clears the value of the "series" field.
func (u *ImportEntryUpsert) ClearSeries() *ImportEntryUpsert {
	u.SetNull(importentry.FieldSeries)
	return u
}

// SetContinueAfterChapter sets the "continue_after_chapter" field.
func (u *ImportEntryUpsert) SetContinueAfterChapter(v float64) *ImportEntryUpsert {
	u.Set(importentry.FieldContinueAfterChapter, v)
	return u
}

// UpdateContinueAfterChapter sets the "continue_after_chapter" field to the value that was provided on create.
func (u *ImportEntryUpsert) UpdateContinueAfterChapter() *ImportEntryUpsert {
	u.SetExcluded(importentry.FieldContinueAfterChapter)
	return u
}

// AddContinueAfterChapter adds v to the "continue_after_chapter" field.
func (u *ImportEntryUpsert) AddContinueAfterChapter(v float64) *ImportEntryUpsert {
	u.Add(importentry.FieldContinueAfterChapter, v)
	return u
}

// ClearContinueAfterChapter clears the value of the "continue_after_chapter" field.
func (u *ImportEntryUpsert) ClearContinueAfterChapter() *ImportEntryUpsert {
	u.SetNull(importentry.FieldContinueAfterChapter)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ImportEntry.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(importentry.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ImportEntryUpsertOne) UpdateNewValues() *ImportEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(importentry.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImportEntry.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ImportEntryUpsertOne) Ignore() *ImportEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImportEntryUpsertOne) DoNothing() *ImportEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImportEntryCreate.OnConflict
// documentation for more info.
func (u *ImportEntryUpsertOne) Update(set func(*ImportEntryUpsert)) *ImportEntryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImportEntryUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *ImportEntryUpsertOne) SetTitle(v string) *ImportEntryUpsertOne {
	return u.Update(func(s *ImportEntryUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ImportEntryUpsertOne) UpdateTitle() *ImportEntryUpsertOne {
	return u.Update(func(s *ImportEntryUpsert) {
		s.UpdateTitle()
	})
}

// SetStatus sets the "status" field.
func (u *ImportEntryUpsertOne) SetStatus(v int) *ImportEntryUpsertOne {
	return u.Update(func(s *ImportEntryUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *ImportEntryUpsertOne) AddStatus(v int) *ImportEntryUpsertOne {
	return u.Update(func(s *ImportEntryUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ImportEntryUpsertOne) UpdateStatus() *ImportEntryUpsertOne {
	return u.Update(func(s *ImportEntryUpsert) {
		s.UpdateStatus()
	})
}

// SetAction sets the "action" field.
func (u *ImportEntryUpsertOne) SetAction(v int) *ImportEntryUpsertOne {
	return u.Update(func(s *ImportEntryUpsert) {
		s.SetAction(v)
	})
}

// AddAction adds v to the "action" field.
func (u *ImportEntryUpsertOne) AddAction(v int) *ImportEntryUpsertOne {
	return u.Update(func(s *ImportEntryUpsert) {
		s.AddAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *ImportEntryUpsertOne) UpdateAction() *ImportEntryUpsertOne {
	return u.Update(func(s *ImportEntryUpsert) {
		s.UpdateAction()
	})
}

// SetInfo sets the "info" field.
func (u *ImportEntryUpsertOne) SetInfo(v *types.KaizokuInfo) *ImportEntryUpsertOne {
	return u.Update(func(s *ImportEntryUpsert) {
		s.SetInfo(v)
	})
}

// UpdateInfo sets the "info" field to the value that was provided on create.
func (u *ImportEntryUpsertOne) UpdateInfo() *ImportEntryUpsertOne {
	return u.Update(func(s *ImportEntryUpsert) {
		s.UpdateInfo()
	})
}

// ClearInfo clears the value of the "info" field.
func (u *ImportEntryUpsertOne) ClearInfo() *ImportEntryUpsertOne {
	return u.Update(func(s *ImportEntryUpsert) {
		s.ClearInfo()
	})
}

// SetSeries sets the "series" field.
func (u *ImportEntryUpsertOne) SetSeries(v []map[string]interface{}) *ImportEntryUpsertOne {
	return u.Update(func(s *ImportEntryUpsert) {
		s.SetSeries(v)
	})
}

// UpdateSeries sets the "series" field to the value that was provided on create.
func (u *ImportEntryUpsertOne) UpdateSeries() *ImportEntryUpsertOne {
	return u.Update(func(s *ImportEntryUpsert) {
		s.UpdateSeries()
	})
}

// ClearSeries clears the value of the "series" field.
func (u *ImportEntryUpsertOne) ClearSeries() *ImportEntryUpsertOne {
	return u.Update(func(s *ImportEntryUpsert) {
		s.ClearSeries()
	})
}

// SetContinueAfterChapter sets the "continue_after_chapter" field.
func (u *ImportEntryUpsertOne) SetContinueAfterChapter(v float64) *ImportEntryUpsertOne {
	return u.Update(func(s *ImportEntryUpsert) {
		s.SetContinueAfterChapter(v)
	})
}

// AddContinueAfterChapter adds v to the "continue_after_chapter" field.
func (u *ImportEntryUpsertOne) AddContinueAfterChapter(v float64) *ImportEntryUpsertOne {
	return u.Update(func(s *ImportEntryUpsert) {
		s.AddContinueAfterChapter(v)
	})
}

// UpdateContinueAfterChapter sets the "continue_after_chapter" field to the value that was provided on create.
func (u *ImportEntryUpsertOne) UpdateContinueAfterChapter() *ImportEntryUpsertOne {
	return u.Update(func(s *ImportEntryUpsert) {
		s.UpdateContinueAfterChapter()
	})
}

// ClearContinueAfterChapter clears the value of the "continue_after_chapter" field.
func (u *ImportEntryUpsertOne) ClearContinueAfterChapter() *ImportEntryUpsertOne {
	return u.Update(func(s *ImportEntryUpsert) {
		s.ClearContinueAfterChapter()
	})
}

// Exec executes the query.
func (u *ImportEntryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImportEntryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImportEntryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ImportEntryUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ImportEntryUpsertOne.ID is not supported by MySQL driver. Use ImportEntryUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ImportEntryUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ImportEntryCreateBulk is the builder for creating many ImportEntry entities in bulk.
type ImportEntryCreateBulk struct {
	config
	err      error
	builders []*ImportEntryCreate
	conflict []sql.ConflictOption
}

// Save creates the ImportEntry entities in the database.
func (_c *ImportEntryCreateBulk) Save(ctx context.Context) ([]*ImportEntry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ImportEntry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ImportEntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ImportEntryCreateBulk) SaveX(ctx context.Context) []*ImportEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImportEntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImportEntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImportEntry.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImportEntryUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *ImportEntryCreateBulk) OnConflict(opts ...sql.ConflictOption) *ImportEntryUpsertBulk {
	_c.conflict = opts
	return &ImportEntryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImportEntry.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImportEntryCreateBulk) OnConflictColumns(columns ...string) *ImportEntryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImportEntryUpsertBulk{
		create: _c,
	}
}

// ImportEntryUpsertBulk is the builder for "upsert"-ing
// a bulk of ImportEntry nodes.
type ImportEntryUpsertBulk struct {
	create *ImportEntryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ImportEntry.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(importentry.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ImportEntryUpsertBulk) UpdateNewValues() *ImportEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(importentry.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImportEntry.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ImportEntryUpsertBulk) Ignore() *ImportEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImportEntryUpsertBulk) DoNothing() *ImportEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImportEntryCreateBulk.OnConflict
// documentation for more info.
func (u *ImportEntryUpsertBulk) Update(set func(*ImportEntryUpsert)) *ImportEntryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImportEntryUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *ImportEntryUpsertBulk) SetTitle(v string) *ImportEntryUpsertBulk {
	return u.Update(func(s *ImportEntryUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ImportEntryUpsertBulk) UpdateTitle() *ImportEntryUpsertBulk {
	return u.Update(func(s *ImportEntryUpsert) {
		s.UpdateTitle()
	})
}

// SetStatus sets the "status" field.
func (u *ImportEntryUpsertBulk) SetStatus(v int) *ImportEntryUpsertBulk {
	return u.Update(func(s *ImportEntryUpsert) {
		s.SetStatus(v)
	})
}

// AddStatus adds v to the "status" field.
func (u *ImportEntryUpsertBulk) AddStatus(v int) *ImportEntryUpsertBulk {
	return u.Update(func(s *ImportEntryUpsert) {
		s.AddStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ImportEntryUpsertBulk) UpdateStatus() *ImportEntryUpsertBulk {
	return u.Update(func(s *ImportEntryUpsert) {
		s.UpdateStatus()
	})
}

// SetAction sets the "action" field.
func (u *ImportEntryUpsertBulk) SetAction(v int) *ImportEntryUpsertBulk {
	return u.Update(func(s *ImportEntryUpsert) {
		s.SetAction(v)
	})
}

// AddAction adds v to the "action" field.
func (u *ImportEntryUpsertBulk) AddAction(v int) *ImportEntryUpsertBulk {
	return u.Update(func(s *ImportEntryUpsert) {
		s.AddAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *ImportEntryUpsertBulk) UpdateAction() *ImportEntryUpsertBulk {
	return u.Update(func(s *ImportEntryUpsert) {
		s.UpdateAction()
	})
}

// SetInfo sets the "info" field.
func (u *ImportEntryUpsertBulk) SetInfo(v *types.KaizokuInfo) *ImportEntryUpsertBulk {
	return u.Update(func(s *ImportEntryUpsert) {
		s.SetInfo(v)
	})
}

// UpdateInfo sets the "info" field to the value that was provided on create.
func (u *ImportEntryUpsertBulk) UpdateInfo() *ImportEntryUpsertBulk {
	return u.Update(func(s *ImportEntryUpsert) {
		s.UpdateInfo()
	})
}

// ClearInfo clears the value of the "info" field.
func (u *ImportEntryUpsertBulk) ClearInfo() *ImportEntryUpsertBulk {
	return u.Update(func(s *ImportEntryUpsert) {
		s.ClearInfo()
	})
}

// SetSeries sets the "series" field.
func (u *ImportEntryUpsertBulk) SetSeries(v []map[string]interface{}) *ImportEntryUpsertBulk {
	return u.Update(func(s *ImportEntryUpsert) {
		s.SetSeries(v)
	})
}

// UpdateSeries sets the "series" field to the value that was provided on create.
func (u *ImportEntryUpsertBulk) UpdateSeries() *ImportEntryUpsertBulk {
	return u.Update(func(s *ImportEntryUpsert) {
		s.UpdateSeries()
	})
}

// ClearSeries clears the value of the "series" field.
func (u *ImportEntryUpsertBulk) ClearSeries() *ImportEntryUpsertBulk {
	return u.Update(func(s *ImportEntryUpsert) {
		s.ClearSeries()
	})
}

// SetContinueAfterChapter sets the "continue_after_chapter" field.
func (u *ImportEntryUpsertBulk) SetContinueAfterChapter(v float64) *ImportEntryUpsertBulk {
	return u.Update(func(s *ImportEntryUpsert) {
		s.SetContinueAfterChapter(v)
	})
}

// AddContinueAfterChapter adds v to the "continue_after_chapter" field.
func (u *ImportEntryUpsertBulk) AddContinueAfterChapter(v float64) *ImportEntryUpsertBulk {
	return u.Update(func(s *ImportEntryUpsert) {
		s.AddContinueAfterChapter(v)
	})
}

// UpdateContinueAfterChapter sets the "continue_after_chapter" field to the value that was provided on create.
func (u *ImportEntryUpsertBulk) UpdateContinueAfterChapter() *ImportEntryUpsertBulk {
	return u.Update(func(s *ImportEntryUpsert) {
		s.UpdateContinueAfterChapter()
	})
}

// ClearContinueAfterChapter clears the value of the "continue_after_chapter" field.
func (u *ImportEntryUpsertBulk) ClearContinueAfterChapter() *ImportEntryUpsertBulk {
	return u.Update(func(s *ImportEntryUpsert) {
		s.ClearContinueAfterChapter()
	})
}

// Exec executes the query.
func (u *ImportEntryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ImportEntryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImportEntryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImportEntryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
