// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/technobecet/kaizoku-go/internal/ent/latestseries"
	"github.com/technobecet/kaizoku-go/internal/ent/series"
	"github.com/technobecet/kaizoku-go/internal/types"
)

// LatestSeriesCreate is the builder for creating a LatestSeries entity.
type LatestSeriesCreate struct {
	config
	mutation *LatestSeriesMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSuwayomiSourceID sets the "suwayomi_source_id" field.
func (_c *LatestSeriesCreate) SetSuwayomiSourceID(v string) *LatestSeriesCreate {
	_c.mutation.SetSuwayomiSourceID(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *LatestSeriesCreate) SetProvider(v string) *LatestSeriesCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetLanguage sets the "language" field.
func (_c *LatestSeriesCreate) SetLanguage(v string) *LatestSeriesCreate {
	_c.mutation.SetLanguage(v)
	return _c
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_c *LatestSeriesCreate) SetNillableLanguage(v *string) *LatestSeriesCreate {
	if v != nil {
		_c.SetLanguage(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *LatestSeriesCreate) SetURL(v string) *LatestSeriesCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_c *LatestSeriesCreate) SetNillableURL(v *string) *LatestSeriesCreate {
	if v != nil {
		_c.SetURL(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *LatestSeriesCreate) SetTitle(v string) *LatestSeriesCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *LatestSeriesCreate) SetNillableTitle(v *string) *LatestSeriesCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (_c *LatestSeriesCreate) SetThumbnailURL(v string) *LatestSeriesCreate {
	_c.mutation.SetThumbnailURL(v)
	return _c
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (_c *LatestSeriesCreate) SetNillableThumbnailURL(v *string) *LatestSeriesCreate {
	if v != nil {
		_c.SetThumbnailURL(*v)
	}
	return _c
}

// SetArtist sets the "artist" field.
func (_c *LatestSeriesCreate) SetArtist(v string) *LatestSeriesCreate {
	_c.mutation.SetArtist(v)
	return _c
}

// SetNillableArtist sets the "artist" field if the given value is not nil.
func (_c *LatestSeriesCreate) SetNillableArtist(v *string) *LatestSeriesCreate {
	if v != nil {
		_c.SetArtist(*v)
	}
	return _c
}

// SetAuthor sets the "author" field.
func (_c *LatestSeriesCreate) SetAuthor(v string) *LatestSeriesCreate {
	_c.mutation.SetAuthor(v)
	return _c
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_c *LatestSeriesCreate) SetNillableAuthor(v *string) *LatestSeriesCreate {
	if v != nil {
		_c.SetAuthor(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *LatestSeriesCreate) SetDescription(v string) *LatestSeriesCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *LatestSeriesCreate) SetNillableDescription(v *string) *LatestSeriesCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetGenre sets the "genre" field.
func (_c *LatestSeriesCreate) SetGenre(v []string) *LatestSeriesCreate {
	_c.mutation.SetGenre(v)
	return _c
}

// SetFetchDate sets the "fetch_date" field.
func (_c *LatestSeriesCreate) SetFetchDate(v time.Time) *LatestSeriesCreate {
	_c.mutation.SetFetchDate(v)
	return _c
}

// SetChapterCount sets the "chapter_count" field.
func (_c *LatestSeriesCreate) SetChapterCount(v int64) *LatestSeriesCreate {
	_c.mutation.SetChapterCount(v)
	return _c
}

// SetNillableChapterCount sets the "chapter_count" field if the given value is not nil.
func (_c *LatestSeriesCreate) SetNillableChapterCount(v *int64) *LatestSeriesCreate {
	if v != nil {
		_c.SetChapterCount(*v)
	}
	return _c
}

// SetLatestChapter sets the "latest_chapter" field.
func (_c *LatestSeriesCreate) SetLatestChapter(v float64) *LatestSeriesCreate {
	_c.mutation.SetLatestChapter(v)
	return _c
}

// SetNillableLatestChapter sets the "latest_chapter" field if the given value is not nil.
func (_c *LatestSeriesCreate) SetNillableLatestChapter(v *float64) *LatestSeriesCreate {
	if v != nil {
		_c.SetLatestChapter(*v)
	}
	return _c
}

// SetLatestChapterTitle sets the "latest_chapter_title" field.
func (_c *LatestSeriesCreate) SetLatestChapterTitle(v string) *LatestSeriesCreate {
	_c.mutation.SetLatestChapterTitle(v)
	return _c
}

// SetNillableLatestChapterTitle sets the "latest_chapter_title" field if the given value is not nil.
func (_c *LatestSeriesCreate) SetNillableLatestChapterTitle(v *string) *LatestSeriesCreate {
	if v != nil {
		_c.SetLatestChapterTitle(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *LatestSeriesCreate) SetStatus(v string) *LatestSeriesCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *LatestSeriesCreate) SetNillableStatus(v *string) *LatestSeriesCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetInLibrary sets the "in_library" field.
func (_c *LatestSeriesCreate) SetInLibrary(v int) *LatestSeriesCreate {
	_c.mutation.SetInLibrary(v)
	return _c
}

// SetNillableInLibrary sets the "in_library" field if the given value is not nil.
func (_c *LatestSeriesCreate) SetNillableInLibrary(v *int) *LatestSeriesCreate {
	if v != nil {
		_c.SetInLibrary(*v)
	}
	return _c
}

// SetSeriesID sets the "series_id" field.
func (_c *LatestSeriesCreate) SetSeriesID(v uuid.UUID) *LatestSeriesCreate {
	_c.mutation.SetSeriesID(v)
	return _c
}

// SetNillableSeriesID sets the "series_id" field if the given value is not nil.
func (_c *LatestSeriesCreate) SetNillableSeriesID(v *uuid.UUID) *LatestSeriesCreate {
	if v != nil {
		_c.SetSeriesID(*v)
	}
	return _c
}

// SetChapters sets the "chapters" field.
func (_c *LatestSeriesCreate) SetChapters(v []types.SuwayomiChapter) *LatestSeriesCreate {
	_c.mutation.SetChapters(v)
	return _c
}

// SetID sets the "id" field.
func (_c *LatestSeriesCreate) SetID(v int) *LatestSeriesCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSeries sets the "series" edge to the Series entity.
func (_c *LatestSeriesCreate) SetSeries(v *Series) *LatestSeriesCreate {
	return _c.SetSeriesID(v.ID)
}

// Mutation returns the LatestSeriesMutation object of the builder.
func (_c *LatestSeriesCreate) Mutation() *LatestSeriesMutation {
	return _c.mutation
}

// Save creates the LatestSeries in the database.
func (_c *LatestSeriesCreate) Save(ctx context.Context) (*LatestSeries, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LatestSeriesCreate) SaveX(ctx context.Context) *LatestSeries {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LatestSeriesCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LatestSeriesCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LatestSeriesCreate) defaults() {
	if _, ok := _c.mutation.Language(); !ok {
		v := latestseries.DefaultLanguage
		_c.mutation.SetLanguage(v)
	}
	if _, ok := _c.mutation.Title(); !ok {
		v := latestseries.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.LatestChapterTitle(); !ok {
		v := latestseries.DefaultLatestChapterTitle
		_c.mutation.SetLatestChapterTitle(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := latestseries.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.InLibrary(); !ok {
		v := latestseries.DefaultInLibrary
		_c.mutation.SetInLibrary(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LatestSeriesCreate) check() error {
	if _, ok := _c.mutation.SuwayomiSourceID(); !ok {
		return &ValidationError{Name: "suwayomi_source_id", err: errors.New(`ent: missing required field "LatestSeries.suwayomi_source_id"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "LatestSeries.provider"`)}
	}
	if _, ok := _c.mutation.Language(); !ok {
		return &ValidationError{Name: "language", err: errors.New(`ent: missing required field "LatestSeries.language"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "LatestSeries.title"`)}
	}
	if _, ok := _c.mutation.FetchDate(); !ok {
		return &ValidationError{Name: "fetch_date", err: errors.New(`ent: missing required field "LatestSeries.fetch_date"`)}
	}
	if _, ok := _c.mutation.LatestChapterTitle(); !ok {
		return &ValidationError{Name: "latest_chapter_title", err: errors.New(`ent: missing required field "LatestSeries.latest_chapter_title"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "LatestSeries.status"`)}
	}
	if _, ok := _c.mutation.InLibrary(); !ok {
		return &ValidationError{Name: "in_library", err: errors.New(`ent: missing required field "LatestSeries.in_library"`)}
	}
	return nil
}

func (_c *LatestSeriesCreate) sqlSave(ctx context.Context) (*LatestSeries, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LatestSeriesCreate) createSpec() (*LatestSeries, *sqlgraph.CreateSpec) {
	var (
		_node = &LatestSeries{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(latestseries.Table, sqlgraph.NewFieldSpec(latestseries.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.SuwayomiSourceID(); ok {
		_spec.SetField(latestseries.FieldSuwayomiSourceID, field.TypeString, value)
		_node.SuwayomiSourceID = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(latestseries.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Language(); ok {
		_spec.SetField(latestseries.FieldLanguage, field.TypeString, value)
		_node.Language = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(latestseries.FieldURL, field.TypeString, value)
		_node.URL = &value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(latestseries.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.ThumbnailURL(); ok {
		_spec.SetField(latestseries.FieldThumbnailURL, field.TypeString, value)
		_node.ThumbnailURL = &value
	}
	if value, ok := _c.mutation.Artist(); ok {
		_spec.SetField(latestseries.FieldArtist, field.TypeString, value)
		_node.Artist = &value
	}
	if value, ok := _c.mutation.Author(); ok {
		_spec.SetField(latestseries.FieldAuthor, field.TypeString, value)
		_node.Author = &value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(latestseries.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Genre(); ok {
		_spec.SetField(latestseries.FieldGenre, field.TypeJSON, value)
		_node.Genre = value
	}
	if value, ok := _c.mutation.FetchDate(); ok {
		_spec.SetField(latestseries.FieldFetchDate, field.TypeTime, value)
		_node.FetchDate = value
	}
	if value, ok := _c.mutation.ChapterCount(); ok {
		_spec.SetField(latestseries.FieldChapterCount, field.TypeInt64, value)
		_node.ChapterCount = &value
	}
	if value, ok := _c.mutation.LatestChapter(); ok {
		_spec.SetField(latestseries.FieldLatestChapter, field.TypeFloat64, value)
		_node.LatestChapter = &value
	}
	if value, ok := _c.mutation.LatestChapterTitle(); ok {
		_spec.SetField(latestseries.FieldLatestChapterTitle, field.TypeString, value)
		_node.LatestChapterTitle = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(latestseries.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.InLibrary(); ok {
		_spec.SetField(latestseries.FieldInLibrary, field.TypeInt, value)
		_node.InLibrary = value
	}
	if value, ok := _c.mutation.Chapters(); ok {
		_spec.SetField(latestseries.FieldChapters, field.TypeJSON, value)
		_node.Chapters = value
	}
	if nodes := _c.mutation.SeriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   latestseries.SeriesTable,
			Columns: []string{latestseries.SeriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SeriesID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LatestSeries.Create().
//		SetSuwayomiSourceID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LatestSeriesUpsert) {
//			SetSuwayomiSourceID(v+v).
//		}).
//		Exec(ctx)
func (_c *LatestSeriesCreate) OnConflict(opts ...sql.ConflictOption) *LatestSeriesUpsertOne {
	_c.conflict = opts
	return &LatestSeriesUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LatestSeries.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LatestSeriesCreate) OnConflictColumns(columns ...string) *LatestSeriesUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LatestSeriesUpsertOne{
		create: _c,
	}
}

type (
	// LatestSeriesUpsertOne is the builder for "upsert"-ing
	//  one LatestSeries node.
	LatestSeriesUpsertOne struct {
		create *LatestSeriesCreate
	}

	// LatestSeriesUpsert is the "OnConflict" setter.
	LatestSeriesUpsert struct {
		*sql.UpdateSet
	}
)

// SetSuwayomiSourceID sets the "suwayomi_source_id" field.
func (u *LatestSeriesUpsert) SetSuwayomiSourceID(v string) *LatestSeriesUpsert {
	u.Set(latestseries.FieldSuwayomiSourceID, v)
	return u
}

// UpdateSuwayomiSourceID sets the "suwayomi_source_id" field to the value that was provided on create.
func (u *LatestSeriesUpsert) UpdateSuwayomiSourceID() *LatestSeriesUpsert {
	u.SetExcluded(latestseries.FieldSuwayomiSourceID)
	return u
}

// SetProvider sets the "provider" field.
func (u *LatestSeriesUpsert) SetProvider(v string) *LatestSeriesUpsert {
	u.Set(latestseries.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *LatestSeriesUpsert) UpdateProvider() *LatestSeriesUpsert {
	u.SetExcluded(latestseries.FieldProvider)
	return u
}

// SetLanguage sets the "language" field.
func (u *LatestSeriesUpsert) SetLanguage(v string) *LatestSeriesUpsert {
	u.Set(latestseries.FieldLanguage, v)
	return u
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *LatestSeriesUpsert) UpdateLanguage() *LatestSeriesUpsert {
	u.SetExcluded(latestseries.FieldLanguage)
	return u
}

// SetURL sets the "url" field.
func (u *LatestSeriesUpsert) SetURL(v string) *LatestSeriesUpsert {
	u.Set(latestseries.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *LatestSeriesUpsert) UpdateURL() *LatestSeriesUpsert {
	u.SetExcluded(latestseries.FieldURL)
	return u
}

// ClearURL clears the value of the "url" field.
func (u *LatestSeriesUpsert) ClearURL() *LatestSeriesUpsert {
	u.SetNull(latestseries.FieldURL)
	return u
}

// SetTitle sets the "title" field.
func (u *LatestSeriesUpsert) SetTitle(v string) *LatestSeriesUpsert {
	u.Set(latestseries.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *LatestSeriesUpsert) UpdateTitle() *LatestSeriesUpsert {
	u.SetExcluded(latestseries.FieldTitle)
	return u
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (u *LatestSeriesUpsert) SetThumbnailURL(v string) *LatestSeriesUpsert {
	u.Set(latestseries.FieldThumbnailURL, v)
	return u
}

// UpdateThumbnailURL sets the "thumbnail_url" field to the value that was provided on create.
func (u *LatestSeriesUpsert) UpdateThumbnailURL() *LatestSeriesUpsert {
	u.SetExcluded(latestseries.FieldThumbnailURL)
	return u
}

// ClearThumbnailURL clears the value of the "thumbnail_url" field.
func (u *LatestSeriesUpsert) ClearThumbnailURL() *LatestSeriesUpsert {
	u.SetNull(latestseries.FieldThumbnailURL)
	return u
}

// SetArtist sets the "artist" field.
func (u *LatestSeriesUpsert) SetArtist(v string) *LatestSeriesUpsert {
	u.Set(latestseries.FieldArtist, v)
	return u
}

// UpdateArtist sets the "artist" field to the value that was provided on create.
func (u *LatestSeriesUpsert) UpdateArtist() *LatestSeriesUpsert {
	u.SetExcluded(latestseries.FieldArtist)
	return u
}

// ClearArtist clears the value of the "artist" field.
func (u *LatestSeriesUpsert) ClearArtist() *LatestSeriesUpsert {
	u.SetNull(latestseries.FieldArtist)
	return u
}

// SetAuthor sets the "author" field.
func (u *LatestSeriesUpsert) SetAuthor(v string) *LatestSeriesUpsert {
	u.Set(latestseries.FieldAuthor, v)
	return u
}

// UpdateAuthor sets the "author" field to the value that was provided on create.
func (u *LatestSeriesUpsert) UpdateAuthor() *LatestSeriesUpsert {
	u.SetExcluded(latestseries.FieldAuthor)
	return u
}

// ClearAuthor clears the value of the "author" field.
func (u *LatestSeriesUpsert) ClearAuthor() *LatestSeriesUpsert {
	u.SetNull(latestseries.FieldAuthor)
	return u
}

// SetDescription sets the "description" field.
func (u *LatestSeriesUpsert) SetDescription(v string) *LatestSeriesUpsert {
	u.Set(latestseries.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *LatestSeriesUpsert) UpdateDescription() *LatestSeriesUpsert {
	u.SetExcluded(latestseries.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *LatestSeriesUpsert) ClearDescription() *LatestSeriesUpsert {
	u.SetNull(latestseries.FieldDescription)
	return u
}

// SetGenre sets the "genre" field.
func (u *LatestSeriesUpsert) SetGenre(v []string) *LatestSeriesUpsert {
	u.Set(latestseries.FieldGenre, v)
	return u
}

// UpdateGenre sets the "genre" field to the value that was provided on create.
func (u *LatestSeriesUpsert) UpdateGenre() *LatestSeriesUpsert {
	u.SetExcluded(latestseries.FieldGenre)
	return u
}

// ClearGenre clears the value of the "genre" field.
func (u *LatestSeriesUpsert) ClearGenre() *LatestSeriesUpsert {
	u.SetNull(latestseries.FieldGenre)
	return u
}

// SetFetchDate sets the "fetch_date" field.
func (u *LatestSeriesUpsert) SetFetchDate(v time.Time) *LatestSeriesUpsert {
	u.Set(latestseries.FieldFetchDate, v)
	return u
}

// UpdateFetchDate sets the "fetch_date" field to the value that was provided on create.
func (u *LatestSeriesUpsert) UpdateFetchDate() *LatestSeriesUpsert {
	u.SetExcluded(latestseries.FieldFetchDate)
	return u
}

// SetChapterCount sets the "chapter_count" field.
func (u *LatestSeriesUpsert) SetChapterCount(v int64) *LatestSeriesUpsert {
	u.Set(latestseries.FieldChapterCount, v)
	return u
}

// UpdateChapterCount sets the "chapter_count" field to the value that was provided on create.
func (u *LatestSeriesUpsert) UpdateChapterCount() *LatestSeriesUpsert {
	u.SetExcluded(latestseries.FieldChapterCount)
	return u
}

// AddChapterCount adds v to the "chapter_count" field.
func (u *LatestSeriesUpsert) AddChapterCount(v int64) *LatestSeriesUpsert {
	u.Add(latestseries.FieldChapterCount, v)
	return u
}

// ClearChapterCount clears the value of the "chapter_count" field.
func (u *LatestSeriesUpsert) ClearChapterCount() *LatestSeriesUpsert {
	u.SetNull(latestseries.FieldChapterCount)
	return u
}

// SetLatestChapter sets the "latest_chapter" field.
func (u *LatestSeriesUpsert) SetLatestChapter(v float64) *LatestSeriesUpsert {
	u.Set(latestseries.FieldLatestChapter, v)
	return u
}

// UpdateLatestChapter sets the "latest_chapter" field to the value that was provided on create.
func (u *LatestSeriesUpsert) UpdateLatestChapter() *LatestSeriesUpsert {
	u.SetExcluded(latestseries.FieldLatestChapter)
	return u
}

// AddLatestChapter adds v to the "latest_chapter" field.
func (u *LatestSeriesUpsert) AddLatestChapter(v float64) *LatestSeriesUpsert {
	u.Add(latestseries.FieldLatestChapter, v)
	return u
}

// ClearLatestChapter clears the value of the "latest_chapter" field.
func (u *LatestSeriesUpsert) ClearLatestChapter() *LatestSeriesUpsert {
	u.SetNull(latestseries.FieldLatestChapter)
	return u
}

// SetLatestChapterTitle sets the "latest_chapter_title" field.
func (u *LatestSeriesUpsert) SetLatestChapterTitle(v string) *LatestSeriesUpsert {
	u.Set(latestseries.FieldLatestChapterTitle, v)
	return u
}

// UpdateLatestChapterTitle sets the "latest_chapter_title" field to the value that was provided on create.
func (u *LatestSeriesUpsert) UpdateLatestChapterTitle() *LatestSeriesUpsert {
	u.SetExcluded(latestseries.FieldLatestChapterTitle)
	return u
}

// SetStatus sets the "status" field.
func (u *LatestSeriesUpsert) SetStatus(v string) *LatestSeriesUpsert {
	u.Set(latestseries.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LatestSeriesUpsert) UpdateStatus() *LatestSeriesUpsert {
	u.SetExcluded(latestseries.FieldStatus)
	return u
}

// SetInLibrary sets the "in_library" field.
func (u *LatestSeriesUpsert) SetInLibrary(v int) *LatestSeriesUpsert {
	u.Set(latestseries.FieldInLibrary, v)
	return u
}

// UpdateInLibrary sets the "in_library" field to the value that was provided on create.
func (u *LatestSeriesUpsert) UpdateInLibrary() *LatestSeriesUpsert {
	u.SetExcluded(latestseries.FieldInLibrary)
	return u
}

// AddInLibrary adds v to the "in_library" field.
func (u *LatestSeriesUpsert) AddInLibrary(v int) *LatestSeriesUpsert {
	u.Add(latestseries.FieldInLibrary, v)
	return u
}

// SetSeriesID sets the "series_id" field.
func (u *LatestSeriesUpsert) SetSeriesID(v uuid.UUID) *LatestSeriesUpsert {
	u.Set(latestseries.FieldSeriesID, v)
	return u
}

// UpdateSeriesID sets the "series_id" field to the value that was provided on create.
func (u *LatestSeriesUpsert) UpdateSeriesID() *LatestSeriesUpsert {
	u.SetExcluded(latestseries.FieldSeriesID)
	return u
}

// ClearSeriesID clears the value of the "series_id" field.
func (u *LatestSeriesUpsert) ClearSeriesID() *LatestSeriesUpsert {
	u.SetNull(latestseries.FieldSeriesID)
	return u
}

// SetChapters sets the "chapters" field.
func (u *LatestSeriesUpsert) SetChapters(v []types.SuwayomiChapter) *LatestSeriesUpsert {
	u.Set(latestseries.FieldChapters, v)
	return u
}

// UpdateChapters sets the "chapters" field to the value that was provided on create.
func (u *LatestSeriesUpsert) UpdateChapters() *LatestSeriesUpsert {
	u.SetExcluded(latestseries.FieldChapters)
	return u
}

// ClearChapters clears the value of the "chapters" field.
func (u *LatestSeriesUpsert) ClearChapters() *LatestSeriesUpsert {
	u.SetNull(latestseries.FieldChapters)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.LatestSeries.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(latestseries.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LatestSeriesUpsertOne) UpdateNewValues() *LatestSeriesUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(latestseries.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LatestSeries.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LatestSeriesUpsertOne) Ignore() *LatestSeriesUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LatestSeriesUpsertOne) DoNothing() *LatestSeriesUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LatestSeriesCreate.OnConflict
// documentation for more info.
func (u *LatestSeriesUpsertOne) Update(set func(*LatestSeriesUpsert)) *LatestSeriesUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LatestSeriesUpsert{UpdateSet: update})
	}))
	return u
}

// SetSuwayomiSourceID sets the "suwayomi_source_id" field.
func (u *LatestSeriesUpsertOne) SetSuwayomiSourceID(v string) *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetSuwayomiSourceID(v)
	})
}

// UpdateSuwayomiSourceID sets the "suwayomi_source_id" field to the value that was provided on create.
func (u *LatestSeriesUpsertOne) UpdateSuwayomiSourceID() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateSuwayomiSourceID()
	})
}

// SetProvider sets the "provider" field.
func (u *LatestSeriesUpsertOne) SetProvider(v string) *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *LatestSeriesUpsertOne) UpdateProvider() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateProvider()
	})
}

// SetLanguage sets the "language" field.
func (u *LatestSeriesUpsertOne) SetLanguage(v string) *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetLanguage(v)
	})
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *LatestSeriesUpsertOne) UpdateLanguage() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateLanguage()
	})
}

// SetURL sets the "url" field.
func (u *LatestSeriesUpsertOne) SetURL(v string) *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *LatestSeriesUpsertOne) UpdateURL() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateURL()
	})
}

// ClearURL clears the value of the "url" field.
func (u *LatestSeriesUpsertOne) ClearURL() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.ClearURL()
	})
}

// SetTitle sets the "title" field.
func (u *LatestSeriesUpsertOne) SetTitle(v string) *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *LatestSeriesUpsertOne) UpdateTitle() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateTitle()
	})
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (u *LatestSeriesUpsertOne) SetThumbnailURL(v string) *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetThumbnailURL(v)
	})
}

// UpdateThumbnailURL sets the "thumbnail_url" field to the value that was provided on create.
func (u *LatestSeriesUpsertOne) UpdateThumbnailURL() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateThumbnailURL()
	})
}

// ClearThumbnailURL clears the value of the "thumbnail_url" field.
func (u *LatestSeriesUpsertOne) ClearThumbnailURL() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.ClearThumbnailURL()
	})
}

// SetArtist sets the "artist" field.
func (u *LatestSeriesUpsertOne) SetArtist(v string) *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetArtist(v)
	})
}

// UpdateArtist sets the "artist" field to the value that was provided on create.
func (u *LatestSeriesUpsertOne) UpdateArtist() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateArtist()
	})
}

// ClearArtist clears the value of the "artist" field.
func (u *LatestSeriesUpsertOne) ClearArtist() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.ClearArtist()
	})
}

// SetAuthor sets the "author" field.
func (u *LatestSeriesUpsertOne) SetAuthor(v string) *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetAuthor(v)
	})
}

// UpdateAuthor sets the "author" field to the value that was provided on create.
func (u *LatestSeriesUpsertOne) UpdateAuthor() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateAuthor()
	})
}

// ClearAuthor clears the value of the "author" field.
func (u *LatestSeriesUpsertOne) ClearAuthor() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.ClearAuthor()
	})
}

// SetDescription sets the "description" field.
func (u *LatestSeriesUpsertOne) SetDescription(v string) *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *LatestSeriesUpsertOne) UpdateDescription() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *LatestSeriesUpsertOne) ClearDescription() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.ClearDescription()
	})
}

// SetGenre sets the "genre" field.
func (u *LatestSeriesUpsertOne) SetGenre(v []string) *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetGenre(v)
	})
}

// UpdateGenre sets the "genre" field to the value that was provided on create.
func (u *LatestSeriesUpsertOne) UpdateGenre() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateGenre()
	})
}

// ClearGenre clears the value of the "genre" field.
func (u *LatestSeriesUpsertOne) ClearGenre() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.ClearGenre()
	})
}

// SetFetchDate sets the "fetch_date" field.
func (u *LatestSeriesUpsertOne) SetFetchDate(v time.Time) *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetFetchDate(v)
	})
}

// UpdateFetchDate sets the "fetch_date" field to the value that was provided on create.
func (u *LatestSeriesUpsertOne) UpdateFetchDate() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateFetchDate()
	})
}

// SetChapterCount sets the "chapter_count" field.
func (u *LatestSeriesUpsertOne) SetChapterCount(v int64) *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetChapterCount(v)
	})
}

// AddChapterCount adds v to the "chapter_count" field.
func (u *LatestSeriesUpsertOne) AddChapterCount(v int64) *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.AddChapterCount(v)
	})
}

// UpdateChapterCount sets the "chapter_count" field to the value that was provided on create.
func (u *LatestSeriesUpsertOne) UpdateChapterCount() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateChapterCount()
	})
}

// ClearChapterCount clears the value of the "chapter_count" field.
func (u *LatestSeriesUpsertOne) ClearChapterCount() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.ClearChapterCount()
	})
}

// SetLatestChapter sets the "latest_chapter" field.
func (u *LatestSeriesUpsertOne) SetLatestChapter(v float64) *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetLatestChapter(v)
	})
}

// AddLatestChapter adds v to the "latest_chapter" field.
func (u *LatestSeriesUpsertOne) AddLatestChapter(v float64) *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.AddLatestChapter(v)
	})
}

// UpdateLatestChapter sets the "latest_chapter" field to the value that was provided on create.
func (u *LatestSeriesUpsertOne) UpdateLatestChapter() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateLatestChapter()
	})
}

// ClearLatestChapter clears the value of the "latest_chapter" field.
func (u *LatestSeriesUpsertOne) ClearLatestChapter() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.ClearLatestChapter()
	})
}

// SetLatestChapterTitle sets the "latest_chapter_title" field.
func (u *LatestSeriesUpsertOne) SetLatestChapterTitle(v string) *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetLatestChapterTitle(v)
	})
}

// UpdateLatestChapterTitle sets the "latest_chapter_title" field to the value that was provided on create.
func (u *LatestSeriesUpsertOne) UpdateLatestChapterTitle() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateLatestChapterTitle()
	})
}

// SetStatus sets the "status" field.
func (u *LatestSeriesUpsertOne) SetStatus(v string) *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LatestSeriesUpsertOne) UpdateStatus() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateStatus()
	})
}

// SetInLibrary sets the "in_library" field.
func (u *LatestSeriesUpsertOne) SetInLibrary(v int) *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetInLibrary(v)
	})
}

// AddInLibrary adds v to the "in_library" field.
func (u *LatestSeriesUpsertOne) AddInLibrary(v int) *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.AddInLibrary(v)
	})
}

// UpdateInLibrary sets the "in_library" field to the value that was provided on create.
func (u *LatestSeriesUpsertOne) UpdateInLibrary() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateInLibrary()
	})
}

// SetSeriesID sets the "series_id" field.
func (u *LatestSeriesUpsertOne) SetSeriesID(v uuid.UUID) *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetSeriesID(v)
	})
}

// UpdateSeriesID sets the "series_id" field to the value that was provided on create.
func (u *LatestSeriesUpsertOne) UpdateSeriesID() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateSeriesID()
	})
}

// ClearSeriesID clears the value of the "series_id" field.
func (u *LatestSeriesUpsertOne) ClearSeriesID() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.ClearSeriesID()
	})
}

// SetChapters sets the "chapters" field.
func (u *LatestSeriesUpsertOne) SetChapters(v []types.SuwayomiChapter) *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetChapters(v)
	})
}

// UpdateChapters sets the "chapters" field to the value that was provided on create.
func (u *LatestSeriesUpsertOne) UpdateChapters() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateChapters()
	})
}

// ClearChapters clears the value of the "chapters" field.
func (u *LatestSeriesUpsertOne) ClearChapters() *LatestSeriesUpsertOne {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.ClearChapters()
	})
}

// Exec executes the query.
func (u *LatestSeriesUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LatestSeriesCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LatestSeriesUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LatestSeriesUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LatestSeriesUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LatestSeriesCreateBulk is the builder for creating many LatestSeries entities in bulk.
type LatestSeriesCreateBulk struct {
	config
	err      error
	builders []*LatestSeriesCreate
	conflict []sql.ConflictOption
}

// Save creates the LatestSeries entities in the database.
func (_c *LatestSeriesCreateBulk) Save(ctx context.Context) ([]*LatestSeries, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LatestSeries, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LatestSeriesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LatestSeriesCreateBulk) SaveX(ctx context.Context) []*LatestSeries {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LatestSeriesCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LatestSeriesCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LatestSeries.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LatestSeriesUpsert) {
//			SetSuwayomiSourceID(v+v).
//		}).
//		Exec(ctx)
func (_c *LatestSeriesCreateBulk) OnConflict(opts ...sql.ConflictOption) *LatestSeriesUpsertBulk {
	_c.conflict = opts
	return &LatestSeriesUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LatestSeries.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LatestSeriesCreateBulk) OnConflictColumns(columns ...string) *LatestSeriesUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LatestSeriesUpsertBulk{
		create: _c,
	}
}

// LatestSeriesUpsertBulk is the builder for "upsert"-ing
// a bulk of LatestSeries nodes.
type LatestSeriesUpsertBulk struct {
	create *LatestSeriesCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LatestSeries.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(latestseries.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LatestSeriesUpsertBulk) UpdateNewValues() *LatestSeriesUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(latestseries.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LatestSeries.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LatestSeriesUpsertBulk) Ignore() *LatestSeriesUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LatestSeriesUpsertBulk) DoNothing() *LatestSeriesUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LatestSeriesCreateBulk.OnConflict
// documentation for more info.
func (u *LatestSeriesUpsertBulk) Update(set func(*LatestSeriesUpsert)) *LatestSeriesUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LatestSeriesUpsert{UpdateSet: update})
	}))
	return u
}

// SetSuwayomiSourceID sets the "suwayomi_source_id" field.
func (u *LatestSeriesUpsertBulk) SetSuwayomiSourceID(v string) *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetSuwayomiSourceID(v)
	})
}

// UpdateSuwayomiSourceID sets the "suwayomi_source_id" field to the value that was provided on create.
func (u *LatestSeriesUpsertBulk) UpdateSuwayomiSourceID() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateSuwayomiSourceID()
	})
}

// SetProvider sets the "provider" field.
func (u *LatestSeriesUpsertBulk) SetProvider(v string) *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *LatestSeriesUpsertBulk) UpdateProvider() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateProvider()
	})
}

// SetLanguage sets the "language" field.
func (u *LatestSeriesUpsertBulk) SetLanguage(v string) *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetLanguage(v)
	})
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *LatestSeriesUpsertBulk) UpdateLanguage() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateLanguage()
	})
}

// SetURL sets the "url" field.
func (u *LatestSeriesUpsertBulk) SetURL(v string) *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *LatestSeriesUpsertBulk) UpdateURL() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateURL()
	})
}

// ClearURL clears the value of the "url" field.
func (u *LatestSeriesUpsertBulk) ClearURL() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.ClearURL()
	})
}

// SetTitle sets the "title" field.
func (u *LatestSeriesUpsertBulk) SetTitle(v string) *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *LatestSeriesUpsertBulk) UpdateTitle() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateTitle()
	})
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (u *LatestSeriesUpsertBulk) SetThumbnailURL(v string) *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetThumbnailURL(v)
	})
}

// UpdateThumbnailURL sets the "thumbnail_url" field to the value that was provided on create.
func (u *LatestSeriesUpsertBulk) UpdateThumbnailURL() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateThumbnailURL()
	})
}

// ClearThumbnailURL clears the value of the "thumbnail_url" field.
func (u *LatestSeriesUpsertBulk) ClearThumbnailURL() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.ClearThumbnailURL()
	})
}

// SetArtist sets the "artist" field.
func (u *LatestSeriesUpsertBulk) SetArtist(v string) *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetArtist(v)
	})
}

// UpdateArtist sets the "artist" field to the value that was provided on create.
func (u *LatestSeriesUpsertBulk) UpdateArtist() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateArtist()
	})
}

// ClearArtist clears the value of the "artist" field.
func (u *LatestSeriesUpsertBulk) ClearArtist() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.ClearArtist()
	})
}

// SetAuthor sets the "author" field.
func (u *LatestSeriesUpsertBulk) SetAuthor(v string) *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetAuthor(v)
	})
}

// UpdateAuthor sets the "author" field to the value that was provided on create.
func (u *LatestSeriesUpsertBulk) UpdateAuthor() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateAuthor()
	})
}

// ClearAuthor clears the value of the "author" field.
func (u *LatestSeriesUpsertBulk) ClearAuthor() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.ClearAuthor()
	})
}

// SetDescription sets the "description" field.
func (u *LatestSeriesUpsertBulk) SetDescription(v string) *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *LatestSeriesUpsertBulk) UpdateDescription() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *LatestSeriesUpsertBulk) ClearDescription() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.ClearDescription()
	})
}

// SetGenre sets the "genre" field.
func (u *LatestSeriesUpsertBulk) SetGenre(v []string) *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetGenre(v)
	})
}

// UpdateGenre sets the "genre" field to the value that was provided on create.
func (u *LatestSeriesUpsertBulk) UpdateGenre() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateGenre()
	})
}

// ClearGenre clears the value of the "genre" field.
func (u *LatestSeriesUpsertBulk) ClearGenre() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.ClearGenre()
	})
}

// SetFetchDate sets the "fetch_date" field.
func (u *LatestSeriesUpsertBulk) SetFetchDate(v time.Time) *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetFetchDate(v)
	})
}

// UpdateFetchDate sets the "fetch_date" field to the value that was provided on create.
func (u *LatestSeriesUpsertBulk) UpdateFetchDate() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateFetchDate()
	})
}

// SetChapterCount sets the "chapter_count" field.
func (u *LatestSeriesUpsertBulk) SetChapterCount(v int64) *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetChapterCount(v)
	})
}

// AddChapterCount adds v to the "chapter_count" field.
func (u *LatestSeriesUpsertBulk) AddChapterCount(v int64) *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.AddChapterCount(v)
	})
}

// UpdateChapterCount sets the "chapter_count" field to the value that was provided on create.
func (u *LatestSeriesUpsertBulk) UpdateChapterCount() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateChapterCount()
	})
}

// ClearChapterCount clears the value of the "chapter_count" field.
func (u *LatestSeriesUpsertBulk) ClearChapterCount() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.ClearChapterCount()
	})
}

// SetLatestChapter sets the "latest_chapter" field.
func (u *LatestSeriesUpsertBulk) SetLatestChapter(v float64) *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetLatestChapter(v)
	})
}

// AddLatestChapter adds v to the "latest_chapter" field.
func (u *LatestSeriesUpsertBulk) AddLatestChapter(v float64) *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.AddLatestChapter(v)
	})
}

// UpdateLatestChapter sets the "latest_chapter" field to the value that was provided on create.
func (u *LatestSeriesUpsertBulk) UpdateLatestChapter() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateLatestChapter()
	})
}

// ClearLatestChapter clears the value of the "latest_chapter" field.
func (u *LatestSeriesUpsertBulk) ClearLatestChapter() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.ClearLatestChapter()
	})
}

// SetLatestChapterTitle sets the "latest_chapter_title" field.
func (u *LatestSeriesUpsertBulk) SetLatestChapterTitle(v string) *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetLatestChapterTitle(v)
	})
}

// UpdateLatestChapterTitle sets the "latest_chapter_title" field to the value that was provided on create.
func (u *LatestSeriesUpsertBulk) UpdateLatestChapterTitle() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateLatestChapterTitle()
	})
}

// SetStatus sets the "status" field.
func (u *LatestSeriesUpsertBulk) SetStatus(v string) *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LatestSeriesUpsertBulk) UpdateStatus() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateStatus()
	})
}

// SetInLibrary sets the "in_library" field.
func (u *LatestSeriesUpsertBulk) SetInLibrary(v int) *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetInLibrary(v)
	})
}

// AddInLibrary adds v to the "in_library" field.
func (u *LatestSeriesUpsertBulk) AddInLibrary(v int) *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.AddInLibrary(v)
	})
}

// UpdateInLibrary sets the "in_library" field to the value that was provided on create.
func (u *LatestSeriesUpsertBulk) UpdateInLibrary() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateInLibrary()
	})
}

// SetSeriesID sets the "series_id" field.
func (u *LatestSeriesUpsertBulk) SetSeriesID(v uuid.UUID) *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetSeriesID(v)
	})
}

// UpdateSeriesID sets the "series_id" field to the value that was provided on create.
func (u *LatestSeriesUpsertBulk) UpdateSeriesID() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateSeriesID()
	})
}

// ClearSeriesID clears the value of the "series_id" field.
func (u *LatestSeriesUpsertBulk) ClearSeriesID() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.ClearSeriesID()
	})
}

// SetChapters sets the "chapters" field.
func (u *LatestSeriesUpsertBulk) SetChapters(v []types.SuwayomiChapter) *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.SetChapters(v)
	})
}

// UpdateChapters sets the "chapters" field to the value that was provided on create.
func (u *LatestSeriesUpsertBulk) UpdateChapters() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.UpdateChapters()
	})
}

// ClearChapters clears the value of the "chapters" field.
func (u *LatestSeriesUpsertBulk) ClearChapters() *LatestSeriesUpsertBulk {
	return u.Update(func(s *LatestSeriesUpsert) {
		s.ClearChapters()
	})
}

// Exec executes the query.
func (u *LatestSeriesUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LatestSeriesCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LatestSeriesCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LatestSeriesUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
