// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/technobecet/kaizoku-go/internal/ent/downloadqueueitem"
	"github.com/technobecet/kaizoku-go/internal/ent/etagcache"
	"github.com/technobecet/kaizoku-go/internal/ent/importentry"
	"github.com/technobecet/kaizoku-go/internal/ent/latestseries"
	"github.com/technobecet/kaizoku-go/internal/ent/providerstorage"
	"github.com/technobecet/kaizoku-go/internal/ent/schema"
	"github.com/technobecet/kaizoku-go/internal/ent/series"
	"github.com/technobecet/kaizoku-go/internal/ent/seriesprovider"
	"github.com/technobecet/kaizoku-go/internal/ent/sourceevent"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	downloadqueueitemFields := schema.DownloadQueueItem{}.Fields()
	_ = downloadqueueitemFields
	// downloadqueueitemDescStatus is the schema descriptor for status field.
	downloadqueueitemDescStatus := downloadqueueitemFields[2].Descriptor()
	// downloadqueueitem.DefaultStatus holds the default value on creation for the status field.
	downloadqueueitem.DefaultStatus = downloadqueueitemDescStatus.Default.(int)
	// downloadqueueitemDescPriority is the schema descriptor for priority field.
	downloadqueueitemDescPriority := downloadqueueitemFields[3].Descriptor()
	// downloadqueueitem.DefaultPriority holds the default value on creation for the priority field.
	downloadqueueitem.DefaultPriority = downloadqueueitemDescPriority.Default.(int)
	// downloadqueueitemDescScheduledAt is the schema descriptor for scheduled_at field.
	downloadqueueitemDescScheduledAt := downloadqueueitemFields[4].Descriptor()
	// downloadqueueitem.DefaultScheduledAt holds the default value on creation for the scheduled_at field.
	downloadqueueitem.DefaultScheduledAt = downloadqueueitemDescScheduledAt.Default.(func() time.Time)
	// downloadqueueitemDescCreatedAt is the schema descriptor for created_at field.
	downloadqueueitemDescCreatedAt := downloadqueueitemFields[5].Descriptor()
	// downloadqueueitem.DefaultCreatedAt holds the default value on creation for the created_at field.
	downloadqueueitem.DefaultCreatedAt = downloadqueueitemDescCreatedAt.Default.(func() time.Time)
	// downloadqueueitemDescID is the schema descriptor for id field.
	downloadqueueitemDescID := downloadqueueitemFields[0].Descriptor()
	// downloadqueueitem.DefaultID holds the default value on creation for the id field.
	downloadqueueitem.DefaultID = downloadqueueitemDescID.Default.(func() uuid.UUID)
	etagcacheFields := schema.EtagCache{}.Fields()
	_ = etagcacheFields
	// etagcacheDescLastUpdated is the schema descriptor for last_updated field.
	etagcacheDescLastUpdated := etagcacheFields[2].Descriptor()
	// etagcache.DefaultLastUpdated holds the default value on creation for the last_updated field.
	etagcache.DefaultLastUpdated = etagcacheDescLastUpdated.Default.(func() time.Time)
	importentryFields := schema.ImportEntry{}.Fields()
	_ = importentryFields
	// importentryDescStatus is the schema descriptor for status field.
	importentryDescStatus := importentryFields[2].Descriptor()
	// importentry.DefaultStatus holds the default value on creation for the status field.
	importentry.DefaultStatus = importentryDescStatus.Default.(int)
	// importentryDescAction is the schema descriptor for action field.
	importentryDescAction := importentryFields[3].Descriptor()
	// importentry.DefaultAction holds the default value on creation for the action field.
	importentry.DefaultAction = importentryDescAction.Default.(int)
	latestseriesFields := schema.LatestSeries{}.Fields()
	_ = latestseriesFields
	// latestseriesDescLanguage is the schema descriptor for language field.
	latestseriesDescLanguage := latestseriesFields[3].Descriptor()
	// latestseries.DefaultLanguage holds the default value on creation for the language field.
	latestseries.DefaultLanguage = latestseriesDescLanguage.Default.(string)
	// latestseriesDescTitle is the schema descriptor for title field.
	latestseriesDescTitle := latestseriesFields[5].Descriptor()
	// latestseries.DefaultTitle holds the default value on creation for the title field.
	latestseries.DefaultTitle = latestseriesDescTitle.Default.(string)
	// latestseriesDescLatestChapterTitle is the schema descriptor for latest_chapter_title field.
	latestseriesDescLatestChapterTitle := latestseriesFields[14].Descriptor()
	// latestseries.DefaultLatestChapterTitle holds the default value on creation for the latest_chapter_title field.
	latestseries.DefaultLatestChapterTitle = latestseriesDescLatestChapterTitle.Default.(string)
	// latestseriesDescStatus is the schema descriptor for status field.
	latestseriesDescStatus := latestseriesFields[15].Descriptor()
	// latestseries.DefaultStatus holds the default value on creation for the status field.
	latestseries.DefaultStatus = latestseriesDescStatus.Default.(string)
	// latestseriesDescInLibrary is the schema descriptor for in_library field.
	latestseriesDescInLibrary := latestseriesFields[16].Descriptor()
	// latestseries.DefaultInLibrary holds the default value on creation for the in_library field.
	latestseries.DefaultInLibrary = latestseriesDescInLibrary.Default.(int)
	providerstorageFields := schema.ProviderStorage{}.Fields()
	_ = providerstorageFields
	// providerstorageDescName is the schema descriptor for name field.
	providerstorageDescName := providerstorageFields[3].Descriptor()
	// providerstorage.DefaultName holds the default value on creation for the name field.
	providerstorage.DefaultName = providerstorageDescName.Default.(string)
	// providerstorageDescLang is the schema descriptor for lang field.
	providerstorageDescLang := providerstorageFields[4].Descriptor()
	// providerstorage.DefaultLang holds the default value on creation for the lang field.
	providerstorage.DefaultLang = providerstorageDescLang.Default.(string)
	// providerstorageDescVersionCode is the schema descriptor for version_code field.
	providerstorageDescVersionCode := providerstorageFields[5].Descriptor()
	// providerstorage.DefaultVersionCode holds the default value on creation for the version_code field.
	providerstorage.DefaultVersionCode = providerstorageDescVersionCode.Default.(int64)
	// providerstorageDescIsStorage is the schema descriptor for is_storage field.
	providerstorageDescIsStorage := providerstorageFields[6].Descriptor()
	// providerstorage.DefaultIsStorage holds the default value on creation for the is_storage field.
	providerstorage.DefaultIsStorage = providerstorageDescIsStorage.Default.(bool)
	// providerstorageDescIsDisabled is the schema descriptor for is_disabled field.
	providerstorageDescIsDisabled := providerstorageFields[7].Descriptor()
	// providerstorage.DefaultIsDisabled holds the default value on creation for the is_disabled field.
	providerstorage.DefaultIsDisabled = providerstorageDescIsDisabled.Default.(bool)
	// providerstorageDescID is the schema descriptor for id field.
	providerstorageDescID := providerstorageFields[0].Descriptor()
	// providerstorage.DefaultID holds the default value on creation for the id field.
	providerstorage.DefaultID = providerstorageDescID.Default.(func() uuid.UUID)
	seriesFields := schema.Series{}.Fields()
	_ = seriesFields
	// seriesDescThumbnailURL is the schema descriptor for thumbnail_url field.
	seriesDescThumbnailURL := seriesFields[2].Descriptor()
	// series.DefaultThumbnailURL holds the default value on creation for the thumbnail_url field.
	series.DefaultThumbnailURL = seriesDescThumbnailURL.Default.(string)
	// seriesDescArtist is the schema descriptor for artist field.
	seriesDescArtist := seriesFields[3].Descriptor()
	// series.DefaultArtist holds the default value on creation for the artist field.
	series.DefaultArtist = seriesDescArtist.Default.(string)
	// seriesDescAuthor is the schema descriptor for author field.
	seriesDescAuthor := seriesFields[4].Descriptor()
	// series.DefaultAuthor holds the default value on creation for the author field.
	series.DefaultAuthor = seriesDescAuthor.Default.(string)
	// seriesDescDescription is the schema descriptor for description field.
	seriesDescDescription := seriesFields[5].Descriptor()
	// series.DefaultDescription holds the default value on creation for the description field.
	series.DefaultDescription = seriesDescDescription.Default.(string)
	// seriesDescStatus is the schema descriptor for status field.
	seriesDescStatus := seriesFields[7].Descriptor()
	// series.DefaultStatus holds the default value on creation for the status field.
	series.DefaultStatus = seriesDescStatus.Default.(string)
	// seriesDescChapterCount is the schema descriptor for chapter_count field.
	seriesDescChapterCount := seriesFields[10].Descriptor()
	// series.DefaultChapterCount holds the default value on creation for the chapter_count field.
	series.DefaultChapterCount = seriesDescChapterCount.Default.(int)
	// seriesDescPauseDownloads is the schema descriptor for pause_downloads field.
	seriesDescPauseDownloads := seriesFields[11].Descriptor()
	// series.DefaultPauseDownloads holds the default value on creation for the pause_downloads field.
	series.DefaultPauseDownloads = seriesDescPauseDownloads.Default.(bool)
	// seriesDescID is the schema descriptor for id field.
	seriesDescID := seriesFields[0].Descriptor()
	// series.DefaultID holds the default value on creation for the id field.
	series.DefaultID = seriesDescID.Default.(func() uuid.UUID)
	seriesproviderFields := schema.SeriesProvider{}.Fields()
	_ = seriesproviderFields
	// seriesproviderDescSuwayomiID is the schema descriptor for suwayomi_id field.
	seriesproviderDescSuwayomiID := seriesproviderFields[2].Descriptor()
	// seriesprovider.DefaultSuwayomiID holds the default value on creation for the suwayomi_id field.
	seriesprovider.DefaultSuwayomiID = seriesproviderDescSuwayomiID.Default.(int)
	// seriesproviderDescScanlator is the schema descriptor for scanlator field.
	seriesproviderDescScanlator := seriesproviderFields[4].Descriptor()
	// seriesprovider.DefaultScanlator holds the default value on creation for the scanlator field.
	seriesprovider.DefaultScanlator = seriesproviderDescScanlator.Default.(string)
	// seriesproviderDescTitle is the schema descriptor for title field.
	seriesproviderDescTitle := seriesproviderFields[6].Descriptor()
	// seriesprovider.DefaultTitle holds the default value on creation for the title field.
	seriesprovider.DefaultTitle = seriesproviderDescTitle.Default.(string)
	// seriesproviderDescLanguage is the schema descriptor for language field.
	seriesproviderDescLanguage := seriesproviderFields[7].Descriptor()
	// seriesprovider.DefaultLanguage holds the default value on creation for the language field.
	seriesprovider.DefaultLanguage = seriesproviderDescLanguage.Default.(string)
	// seriesproviderDescIsTitle is the schema descriptor for is_title field.
	seriesproviderDescIsTitle := seriesproviderFields[16].Descriptor()
	// seriesprovider.DefaultIsTitle holds the default value on creation for the is_title field.
	seriesprovider.DefaultIsTitle = seriesproviderDescIsTitle.Default.(bool)
	// seriesproviderDescIsCover is the schema descriptor for is_cover field.
	seriesproviderDescIsCover := seriesproviderFields[17].Descriptor()
	// seriesprovider.DefaultIsCover holds the default value on creation for the is_cover field.
	seriesprovider.DefaultIsCover = seriesproviderDescIsCover.Default.(bool)
	// seriesproviderDescIsUnknown is the schema descriptor for is_unknown field.
	seriesproviderDescIsUnknown := seriesproviderFields[18].Descriptor()
	// seriesprovider.DefaultIsUnknown holds the default value on creation for the is_unknown field.
	seriesprovider.DefaultIsUnknown = seriesproviderDescIsUnknown.Default.(bool)
	// seriesproviderDescImportance is the schema descriptor for importance field.
	seriesproviderDescImportance := seriesproviderFields[19].Descriptor()
	// seriesprovider.DefaultImportance holds the default value on creation for the importance field.
	seriesprovider.DefaultImportance = seriesproviderDescImportance.Default.(int)
	// seriesproviderDescIsDisabled is the schema descriptor for is_disabled field.
	seriesproviderDescIsDisabled := seriesproviderFields[20].Descriptor()
	// seriesprovider.DefaultIsDisabled holds the default value on creation for the is_disabled field.
	seriesprovider.DefaultIsDisabled = seriesproviderDescIsDisabled.Default.(bool)
	// seriesproviderDescIsUninstalled is the schema descriptor for is_uninstalled field.
	seriesproviderDescIsUninstalled := seriesproviderFields[21].Descriptor()
	// seriesprovider.DefaultIsUninstalled holds the default value on creation for the is_uninstalled field.
	seriesprovider.DefaultIsUninstalled = seriesproviderDescIsUninstalled.Default.(bool)
	// seriesproviderDescStatus is the schema descriptor for status field.
	seriesproviderDescStatus := seriesproviderFields[22].Descriptor()
	// seriesprovider.DefaultStatus holds the default value on creation for the status field.
	seriesprovider.DefaultStatus = seriesproviderDescStatus.Default.(string)
	// seriesproviderDescID is the schema descriptor for id field.
	seriesproviderDescID := seriesproviderFields[0].Descriptor()
	// seriesprovider.DefaultID holds the default value on creation for the id field.
	seriesprovider.DefaultID = seriesproviderDescID.Default.(func() uuid.UUID)
	sourceeventFields := schema.SourceEvent{}.Fields()
	_ = sourceeventFields
	// sourceeventDescCreatedAt is the schema descriptor for created_at field.
	sourceeventDescCreatedAt := sourceeventFields[11].Descriptor()
	// sourceevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	sourceevent.DefaultCreatedAt = sourceeventDescCreatedAt.Default.(func() time.Time)
	// sourceeventDescID is the schema descriptor for id field.
	sourceeventDescID := sourceeventFields[0].Descriptor()
	// sourceevent.DefaultID holds the default value on creation for the id field.
	sourceevent.DefaultID = sourceeventDescID.Default.(func() uuid.UUID)
}
