// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/technobecet/kaizoku-go/internal/ent/series"
	"github.com/technobecet/kaizoku-go/internal/ent/seriesprovider"
	"github.com/technobecet/kaizoku-go/internal/types"
)

// SeriesProviderCreate is the builder for creating a SeriesProvider entity.
type SeriesProviderCreate struct {
	config
	mutation *SeriesProviderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSeriesID sets the "series_id" field.
func (_c *SeriesProviderCreate) SetSeriesID(v uuid.UUID) *SeriesProviderCreate {
	_c.mutation.SetSeriesID(v)
	return _c
}

// SetSuwayomiID sets the "suwayomi_id" field.
func (_c *SeriesProviderCreate) SetSuwayomiID(v int) *SeriesProviderCreate {
	_c.mutation.SetSuwayomiID(v)
	return _c
}

// SetNillableSuwayomiID sets the "suwayomi_id" field if the given value is not nil.
func (_c *SeriesProviderCreate) SetNillableSuwayomiID(v *int) *SeriesProviderCreate {
	if v != nil {
		_c.SetSuwayomiID(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *SeriesProviderCreate) SetProvider(v string) *SeriesProviderCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetScanlator sets the "scanlator" field.
func (_c *SeriesProviderCreate) SetScanlator(v string) *SeriesProviderCreate {
	_c.mutation.SetScanlator(v)
	return _c
}

// SetNillableScanlator sets the "scanlator" field if the given value is not nil.
func (_c *SeriesProviderCreate) SetNillableScanlator(v *string) *SeriesProviderCreate {
	if v != nil {
		_c.SetScanlator(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *SeriesProviderCreate) SetURL(v string) *SeriesProviderCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_c *SeriesProviderCreate) SetNillableURL(v *string) *SeriesProviderCreate {
	if v != nil {
		_c.SetURL(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *SeriesProviderCreate) SetTitle(v string) *SeriesProviderCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *SeriesProviderCreate) SetNillableTitle(v *string) *SeriesProviderCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetLanguage sets the "language" field.
func (_c *SeriesProviderCreate) SetLanguage(v string) *SeriesProviderCreate {
	_c.mutation.SetLanguage(v)
	return _c
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_c *SeriesProviderCreate) SetNillableLanguage(v *string) *SeriesProviderCreate {
	if v != nil {
		_c.SetLanguage(*v)
	}
	return _c
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (_c *SeriesProviderCreate) SetThumbnailURL(v string) *SeriesProviderCreate {
	_c.mutation.SetThumbnailURL(v)
	return _c
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (_c *SeriesProviderCreate) SetNillableThumbnailURL(v *string) *SeriesProviderCreate {
	if v != nil {
		_c.SetThumbnailURL(*v)
	}
	return _c
}

// SetArtist sets the "artist" field.
func (_c *SeriesProviderCreate) SetArtist(v string) *SeriesProviderCreate {
	_c.mutation.SetArtist(v)
	return _c
}

// SetNillableArtist sets the "artist" field if the given value is not nil.
func (_c *SeriesProviderCreate) SetNillableArtist(v *string) *SeriesProviderCreate {
	if v != nil {
		_c.SetArtist(*v)
	}
	return _c
}

// SetAuthor sets the "author" field.
func (_c *SeriesProviderCreate) SetAuthor(v string) *SeriesProviderCreate {
	_c.mutation.SetAuthor(v)
	return _c
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_c *SeriesProviderCreate) SetNillableAuthor(v *string) *SeriesProviderCreate {
	if v != nil {
		_c.SetAuthor(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *SeriesProviderCreate) SetDescription(v string) *SeriesProviderCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SeriesProviderCreate) SetNillableDescription(v *string) *SeriesProviderCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetGenre sets the "genre" field.
func (_c *SeriesProviderCreate) SetGenre(v []string) *SeriesProviderCreate {
	_c.mutation.SetGenre(v)
	return _c
}

// SetFetchDate sets the "fetch_date" field.
func (_c *SeriesProviderCreate) SetFetchDate(v time.Time) *SeriesProviderCreate {
	_c.mutation.SetFetchDate(v)
	return _c
}

// SetNillableFetchDate sets the "fetch_date" field if the given value is not nil.
func (_c *SeriesProviderCreate) SetNillableFetchDate(v *time.Time) *SeriesProviderCreate {
	if v != nil {
		_c.SetFetchDate(*v)
	}
	return _c
}

// SetChapterCount sets the "chapter_count" field.
func (_c *SeriesProviderCreate) SetChapterCount(v int64) *SeriesProviderCreate {
	_c.mutation.SetChapterCount(v)
	return _c
}

// SetNillableChapterCount sets the "chapter_count" field if the given value is not nil.
func (_c *SeriesProviderCreate) SetNillableChapterCount(v *int64) *SeriesProviderCreate {
	if v != nil {
		_c.SetChapterCount(*v)
	}
	return _c
}

// SetContinueAfterChapter sets the "continue_after_chapter" field.
func (_c *SeriesProviderCreate) SetContinueAfterChapter(v float64) *SeriesProviderCreate {
	_c.mutation.SetContinueAfterChapter(v)
	return _c
}

// SetNillableContinueAfterChapter sets the "continue_after_chapter" field if the given value is not nil.
func (_c *SeriesProviderCreate) SetNillableContinueAfterChapter(v *float64) *SeriesProviderCreate {
	if v != nil {
		_c.SetContinueAfterChapter(*v)
	}
	return _c
}

// SetIsTitle sets the "is_title" field.
func (_c *SeriesProviderCreate) SetIsTitle(v bool) *SeriesProviderCreate {
	_c.mutation.SetIsTitle(v)
	return _c
}

// SetNillableIsTitle sets the "is_title" field if the given value is not nil.
func (_c *SeriesProviderCreate) SetNillableIsTitle(v *bool) *SeriesProviderCreate {
	if v != nil {
		_c.SetIsTitle(*v)
	}
	return _c
}

// SetIsCover sets the "is_cover" field.
func (_c *SeriesProviderCreate) SetIsCover(v bool) *SeriesProviderCreate {
	_c.mutation.SetIsCover(v)
	return _c
}

// SetNillableIsCover sets the "is_cover" field if the given value is not nil.
func (_c *SeriesProviderCreate) SetNillableIsCover(v *bool) *SeriesProviderCreate {
	if v != nil {
		_c.SetIsCover(*v)
	}
	return _c
}

// SetIsUnknown sets the "is_unknown" field.
func (_c *SeriesProviderCreate) SetIsUnknown(v bool) *SeriesProviderCreate {
	_c.mutation.SetIsUnknown(v)
	return _c
}

// SetNillableIsUnknown sets the "is_unknown" field if the given value is not nil.
func (_c *SeriesProviderCreate) SetNillableIsUnknown(v *bool) *SeriesProviderCreate {
	if v != nil {
		_c.SetIsUnknown(*v)
	}
	return _c
}

// SetImportance sets the "importance" field.
func (_c *SeriesProviderCreate) SetImportance(v int) *SeriesProviderCreate {
	_c.mutation.SetImportance(v)
	return _c
}

// SetNillableImportance sets the "importance" field if the given value is not nil.
func (_c *SeriesProviderCreate) SetNillableImportance(v *int) *SeriesProviderCreate {
	if v != nil {
		_c.SetImportance(*v)
	}
	return _c
}

// SetIsDisabled sets the "is_disabled" field.
func (_c *SeriesProviderCreate) SetIsDisabled(v bool) *SeriesProviderCreate {
	_c.mutation.SetIsDisabled(v)
	return _c
}

// SetNillableIsDisabled sets the "is_disabled" field if the given value is not nil.
func (_c *SeriesProviderCreate) SetNillableIsDisabled(v *bool) *SeriesProviderCreate {
	if v != nil {
		_c.SetIsDisabled(*v)
	}
	return _c
}

// SetIsUninstalled sets the "is_uninstalled" field.
func (_c *SeriesProviderCreate) SetIsUninstalled(v bool) *SeriesProviderCreate {
	_c.mutation.SetIsUninstalled(v)
	return _c
}

// SetNillableIsUninstalled sets the "is_uninstalled" field if the given value is not nil.
func (_c *SeriesProviderCreate) SetNillableIsUninstalled(v *bool) *SeriesProviderCreate {
	if v != nil {
		_c.SetIsUninstalled(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SeriesProviderCreate) SetStatus(v string) *SeriesProviderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SeriesProviderCreate) SetNillableStatus(v *string) *SeriesProviderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetChapters sets the "chapters" field.
func (_c *SeriesProviderCreate) SetChapters(v []types.Chapter) *SeriesProviderCreate {
	_c.mutation.SetChapters(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SeriesProviderCreate) SetID(v uuid.UUID) *SeriesProviderCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SeriesProviderCreate) SetNillableID(v *uuid.UUID) *SeriesProviderCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetSeries sets the "series" edge to the Series entity.
func (_c *SeriesProviderCreate) SetSeries(v *Series) *SeriesProviderCreate {
	return _c.SetSeriesID(v.ID)
}

// Mutation returns the SeriesProviderMutation object of the builder.
func (_c *SeriesProviderCreate) Mutation() *SeriesProviderMutation {
	return _c.mutation
}

// Save creates the SeriesProvider in the database.
func (_c *SeriesProviderCreate) Save(ctx context.Context) (*SeriesProvider, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SeriesProviderCreate) SaveX(ctx context.Context) *SeriesProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SeriesProviderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SeriesProviderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SeriesProviderCreate) defaults() {
	if _, ok := _c.mutation.SuwayomiID(); !ok {
		v := seriesprovider.DefaultSuwayomiID
		_c.mutation.SetSuwayomiID(v)
	}
	if _, ok := _c.mutation.Scanlator(); !ok {
		v := seriesprovider.DefaultScanlator
		_c.mutation.SetScanlator(v)
	}
	if _, ok := _c.mutation.Title(); !ok {
		v := seriesprovider.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.Language(); !ok {
		v := seriesprovider.DefaultLanguage
		_c.mutation.SetLanguage(v)
	}
	if _, ok := _c.mutation.IsTitle(); !ok {
		v := seriesprovider.DefaultIsTitle
		_c.mutation.SetIsTitle(v)
	}
	if _, ok := _c.mutation.IsCover(); !ok {
		v := seriesprovider.DefaultIsCover
		_c.mutation.SetIsCover(v)
	}
	if _, ok := _c.mutation.IsUnknown(); !ok {
		v := seriesprovider.DefaultIsUnknown
		_c.mutation.SetIsUnknown(v)
	}
	if _, ok := _c.mutation.Importance(); !ok {
		v := seriesprovider.DefaultImportance
		_c.mutation.SetImportance(v)
	}
	if _, ok := _c.mutation.IsDisabled(); !ok {
		v := seriesprovider.DefaultIsDisabled
		_c.mutation.SetIsDisabled(v)
	}
	if _, ok := _c.mutation.IsUninstalled(); !ok {
		v := seriesprovider.DefaultIsUninstalled
		_c.mutation.SetIsUninstalled(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := seriesprovider.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := seriesprovider.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SeriesProviderCreate) check() error {
	if _, ok := _c.mutation.SeriesID(); !ok {
		return &ValidationError{Name: "series_id", err: errors.New(`ent: missing required field "SeriesProvider.series_id"`)}
	}
	if _, ok := _c.mutation.SuwayomiID(); !ok {
		return &ValidationError{Name: "suwayomi_id", err: errors.New(`ent: missing required field "SeriesProvider.suwayomi_id"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "SeriesProvider.provider"`)}
	}
	if _, ok := _c.mutation.Scanlator(); !ok {
		return &ValidationError{Name: "scanlator", err: errors.New(`ent: missing required field "SeriesProvider.scanlator"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "SeriesProvider.title"`)}
	}
	if _, ok := _c.mutation.Language(); !ok {
		return &ValidationError{Name: "language", err: errors.New(`ent: missing required field "SeriesProvider.language"`)}
	}
	if _, ok := _c.mutation.IsTitle(); !ok {
		return &ValidationError{Name: "is_title", err: errors.New(`ent: missing required field "SeriesProvider.is_title"`)}
	}
	if _, ok := _c.mutation.IsCover(); !ok {
		return &ValidationError{Name: "is_cover", err: errors.New(`ent: missing required field "SeriesProvider.is_cover"`)}
	}
	if _, ok := _c.mutation.IsUnknown(); !ok {
		return &ValidationError{Name: "is_unknown", err: errors.New(`ent: missing required field "SeriesProvider.is_unknown"`)}
	}
	if _, ok := _c.mutation.Importance(); !ok {
		return &ValidationError{Name: "importance", err: errors.New(`ent: missing required field "SeriesProvider.importance"`)}
	}
	if _, ok := _c.mutation.IsDisabled(); !ok {
		return &ValidationError{Name: "is_disabled", err: errors.New(`ent: missing required field "SeriesProvider.is_disabled"`)}
	}
	if _, ok := _c.mutation.IsUninstalled(); !ok {
		return &ValidationError{Name: "is_uninstalled", err: errors.New(`ent: missing required field "SeriesProvider.is_uninstalled"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SeriesProvider.status"`)}
	}
	if len(_c.mutation.SeriesIDs()) == 0 {
		return &ValidationError{Name: "series", err: errors.New(`ent: missing required edge "SeriesProvider.series"`)}
	}
	return nil
}

func (_c *SeriesProviderCreate) sqlSave(ctx context.Context) (*SeriesProvider, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SeriesProviderCreate) createSpec() (*SeriesProvider, *sqlgraph.CreateSpec) {
	var (
		_node = &SeriesProvider{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(seriesprovider.Table, sqlgraph.NewFieldSpec(seriesprovider.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.SuwayomiID(); ok {
		_spec.SetField(seriesprovider.FieldSuwayomiID, field.TypeInt, value)
		_node.SuwayomiID = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(seriesprovider.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Scanlator(); ok {
		_spec.SetField(seriesprovider.FieldScanlator, field.TypeString, value)
		_node.Scanlator = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(seriesprovider.FieldURL, field.TypeString, value)
		_node.URL = &value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(seriesprovider.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Language(); ok {
		_spec.SetField(seriesprovider.FieldLanguage, field.TypeString, value)
		_node.Language = value
	}
	if value, ok := _c.mutation.ThumbnailURL(); ok {
		_spec.SetField(seriesprovider.FieldThumbnailURL, field.TypeString, value)
		_node.ThumbnailURL = &value
	}
	if value, ok := _c.mutation.Artist(); ok {
		_spec.SetField(seriesprovider.FieldArtist, field.TypeString, value)
		_node.Artist = &value
	}
	if value, ok := _c.mutation.Author(); ok {
		_spec.SetField(seriesprovider.FieldAuthor, field.TypeString, value)
		_node.Author = &value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(seriesprovider.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Genre(); ok {
		_spec.SetField(seriesprovider.FieldGenre, field.TypeJSON, value)
		_node.Genre = value
	}
	if value, ok := _c.mutation.FetchDate(); ok {
		_spec.SetField(seriesprovider.FieldFetchDate, field.TypeTime, value)
		_node.FetchDate = &value
	}
	if value, ok := _c.mutation.ChapterCount(); ok {
		_spec.SetField(seriesprovider.FieldChapterCount, field.TypeInt64, value)
		_node.ChapterCount = &value
	}
	if value, ok := _c.mutation.ContinueAfterChapter(); ok {
		_spec.SetField(seriesprovider.FieldContinueAfterChapter, field.TypeFloat64, value)
		_node.ContinueAfterChapter = &value
	}
	if value, ok := _c.mutation.IsTitle(); ok {
		_spec.SetField(seriesprovider.FieldIsTitle, field.TypeBool, value)
		_node.IsTitle = value
	}
	if value, ok := _c.mutation.IsCover(); ok {
		_spec.SetField(seriesprovider.FieldIsCover, field.TypeBool, value)
		_node.IsCover = value
	}
	if value, ok := _c.mutation.IsUnknown(); ok {
		_spec.SetField(seriesprovider.FieldIsUnknown, field.TypeBool, value)
		_node.IsUnknown = value
	}
	if value, ok := _c.mutation.Importance(); ok {
		_spec.SetField(seriesprovider.FieldImportance, field.TypeInt, value)
		_node.Importance = value
	}
	if value, ok := _c.mutation.IsDisabled(); ok {
		_spec.SetField(seriesprovider.FieldIsDisabled, field.TypeBool, value)
		_node.IsDisabled = value
	}
	if value, ok := _c.mutation.IsUninstalled(); ok {
		_spec.SetField(seriesprovider.FieldIsUninstalled, field.TypeBool, value)
		_node.IsUninstalled = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(seriesprovider.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Chapters(); ok {
		_spec.SetField(seriesprovider.FieldChapters, field.TypeJSON, value)
		_node.Chapters = value
	}
	if nodes := _c.mutation.SeriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   seriesprovider.SeriesTable,
			Columns: []string{seriesprovider.SeriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SeriesID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SeriesProvider.Create().
//		SetSeriesID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SeriesProviderUpsert) {
//			SetSeriesID(v+v).
//		}).
//		Exec(ctx)
func (_c *SeriesProviderCreate) OnConflict(opts ...sql.ConflictOption) *SeriesProviderUpsertOne {
	_c.conflict = opts
	return &SeriesProviderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SeriesProvider.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SeriesProviderCreate) OnConflictColumns(columns ...string) *SeriesProviderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SeriesProviderUpsertOne{
		create: _c,
	}
}

type (
	// SeriesProviderUpsertOne is the builder for "upsert"-ing
	//  one SeriesProvider node.
	SeriesProviderUpsertOne struct {
		create *SeriesProviderCreate
	}

	// SeriesProviderUpsert is the "OnConflict" setter.
	SeriesProviderUpsert struct {
		*sql.UpdateSet
	}
)

// SetSeriesID sets the "series_id" field.
func (u *SeriesProviderUpsert) SetSeriesID(v uuid.UUID) *SeriesProviderUpsert {
	u.Set(seriesprovider.FieldSeriesID, v)
	return u
}

// UpdateSeriesID sets the "series_id" field to the value that was provided on create.
func (u *SeriesProviderUpsert) UpdateSeriesID() *SeriesProviderUpsert {
	u.SetExcluded(seriesprovider.FieldSeriesID)
	return u
}

// SetSuwayomiID sets the "suwayomi_id" field.
func (u *SeriesProviderUpsert) SetSuwayomiID(v int) *SeriesProviderUpsert {
	u.Set(seriesprovider.FieldSuwayomiID, v)
	return u
}

// UpdateSuwayomiID sets the "suwayomi_id" field to the value that was provided on create.
func (u *SeriesProviderUpsert) UpdateSuwayomiID() *SeriesProviderUpsert {
	u.SetExcluded(seriesprovider.FieldSuwayomiID)
	return u
}

// AddSuwayomiID adds v to the "suwayomi_id" field.
func (u *SeriesProviderUpsert) AddSuwayomiID(v int) *SeriesProviderUpsert {
	u.Add(seriesprovider.FieldSuwayomiID, v)
	return u
}

// SetProvider sets the "provider" field.
func (u *SeriesProviderUpsert) SetProvider(v string) *SeriesProviderUpsert {
	u.Set(seriesprovider.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *SeriesProviderUpsert) UpdateProvider() *SeriesProviderUpsert {
	u.SetExcluded(seriesprovider.FieldProvider)
	return u
}

// SetScanlator sets the "scanlator" field.
func (u *SeriesProviderUpsert) SetScanlator(v string) *SeriesProviderUpsert {
	u.Set(seriesprovider.FieldScanlator, v)
	return u
}

// UpdateScanlator sets the "scanlator" field to the value that was provided on create.
func (u *SeriesProviderUpsert) UpdateScanlator() *SeriesProviderUpsert {
	u.SetExcluded(seriesprovider.FieldScanlator)
	return u
}

// SetURL sets the "url" field.
func (u *SeriesProviderUpsert) SetURL(v string) *SeriesProviderUpsert {
	u.Set(seriesprovider.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *SeriesProviderUpsert) UpdateURL() *SeriesProviderUpsert {
	u.SetExcluded(seriesprovider.FieldURL)
	return u
}

// ClearURL clears the value of the "url" field.
func (u *SeriesProviderUpsert) ClearURL() *SeriesProviderUpsert {
	u.SetNull(seriesprovider.FieldURL)
	return u
}

// SetTitle sets the "title" field.
func (u *SeriesProviderUpsert) SetTitle(v string) *SeriesProviderUpsert {
	u.Set(seriesprovider.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *SeriesProviderUpsert) UpdateTitle() *SeriesProviderUpsert {
	u.SetExcluded(seriesprovider.FieldTitle)
	return u
}

// SetLanguage sets the "language" field.
func (u *SeriesProviderUpsert) SetLanguage(v string) *SeriesProviderUpsert {
	u.Set(seriesprovider.FieldLanguage, v)
	return u
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *SeriesProviderUpsert) UpdateLanguage() *SeriesProviderUpsert {
	u.SetExcluded(seriesprovider.FieldLanguage)
	return u
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (u *SeriesProviderUpsert) SetThumbnailURL(v string) *SeriesProviderUpsert {
	u.Set(seriesprovider.FieldThumbnailURL, v)
	return u
}

// UpdateThumbnailURL sets the "thumbnail_url" field to the value that was provided on create.
func (u *SeriesProviderUpsert) UpdateThumbnailURL() *SeriesProviderUpsert {
	u.SetExcluded(seriesprovider.FieldThumbnailURL)
	return u
}

// ClearThumbnailURL clears the value of the "thumbnail_url" field.
func (u *SeriesProviderUpsert) ClearThumbnailURL() *SeriesProviderUpsert {
	u.SetNull(seriesprovider.FieldThumbnailURL)
	return u
}

// SetArtist sets the "artist" field.
func (u *SeriesProviderUpsert) SetArtist(v string) *SeriesProviderUpsert {
	u.Set(seriesprovider.FieldArtist, v)
	return u
}

// UpdateArtist sets the "artist" field to the value that was provided on create.
func (u *SeriesProviderUpsert) UpdateArtist() *SeriesProviderUpsert {
	u.SetExcluded(seriesprovider.FieldArtist)
	return u
}

// ClearArtist clears the value of the "artist" field.
func (u *SeriesProviderUpsert) ClearArtist() *SeriesProviderUpsert {
	u.SetNull(seriesprovider.FieldArtist)
	return u
}

// SetAuthor sets the "author" field.
func (u *SeriesProviderUpsert) SetAuthor(v string) *SeriesProviderUpsert {
	u.Set(seriesprovider.FieldAuthor, v)
	return u
}

// UpdateAuthor sets the "author" field to the value that was provided on create.
func (u *SeriesProviderUpsert) UpdateAuthor() *SeriesProviderUpsert {
	u.SetExcluded(seriesprovider.FieldAuthor)
	return u
}

// ClearAuthor clears the value of the "author" field.
func (u *SeriesProviderUpsert) ClearAuthor() *SeriesProviderUpsert {
	u.SetNull(seriesprovider.FieldAuthor)
	return u
}

// SetDescription sets the "description" field.
func (u *SeriesProviderUpsert) SetDescription(v string) *SeriesProviderUpsert {
	u.Set(seriesprovider.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SeriesProviderUpsert) UpdateDescription() *SeriesProviderUpsert {
	u.SetExcluded(seriesprovider.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *SeriesProviderUpsert) ClearDescription() *SeriesProviderUpsert {
	u.SetNull(seriesprovider.FieldDescription)
	return u
}

// SetGenre sets the "genre" field.
func (u *SeriesProviderUpsert) SetGenre(v []string) *SeriesProviderUpsert {
	u.Set(seriesprovider.FieldGenre, v)
	return u
}

// UpdateGenre sets the "genre" field to the value that was provided on create.
func (u *SeriesProviderUpsert) UpdateGenre() *SeriesProviderUpsert {
	u.SetExcluded(seriesprovider.FieldGenre)
	return u
}

// ClearGenre clears the value of the "genre" field.
func (u *SeriesProviderUpsert) ClearGenre() *SeriesProviderUpsert {
	u.SetNull(seriesprovider.FieldGenre)
	return u
}

// SetFetchDate sets the "fetch_date" field.
func (u *SeriesProviderUpsert) SetFetchDate(v time.Time) *SeriesProviderUpsert {
	u.Set(seriesprovider.FieldFetchDate, v)
	return u
}

// UpdateFetchDate sets the "fetch_date" field to the value that was provided on create.
func (u *SeriesProviderUpsert) UpdateFetchDate() *SeriesProviderUpsert {
	u.SetExcluded(seriesprovider.FieldFetchDate)
	return u
}

// ClearFetchDate clears the value of the "fetch_date" field.
func (u *SeriesProviderUpsert) ClearFetchDate() *SeriesProviderUpsert {
	u.SetNull(seriesprovider.FieldFetchDate)
	return u
}

// SetChapterCount sets the "chapter_count" field.
func (u *SeriesProviderUpsert) SetChapterCount(v int64) *SeriesProviderUpsert {
	u.Set(seriesprovider.FieldChapterCount, v)
	return u
}

// UpdateChapterCount sets the "chapter_count" field to the value that was provided on create.
func (u *SeriesProviderUpsert) UpdateChapterCount() *SeriesProviderUpsert {
	u.SetExcluded(seriesprovider.FieldChapterCount)
	return u
}

// AddChapterCount adds v to the "chapter_count" field.
func (u *SeriesProviderUpsert) AddChapterCount(v int64) *SeriesProviderUpsert {
	u.Add(seriesprovider.FieldChapterCount, v)
	return u
}

// ClearChapterCount clears the value of the "chapter_count" field.
func (u *SeriesProviderUpsert) ClearChapterCount() *SeriesProviderUpsert {
	u.SetNull(seriesprovider.FieldChapterCount)
	return u
}

// SetContinueAfterChapter sets the "continue_after_chapter" field.
func (u *SeriesProviderUpsert) SetContinueAfterChapter(v float64) *SeriesProviderUpsert {
	u.Set(seriesprovider.FieldContinueAfterChapter, v)
	return u
}

// UpdateContinueAfterChapter sets the "continue_after_chapter" field to the value that was provided on create.
func (u *SeriesProviderUpsert) UpdateContinueAfterChapter() *SeriesProviderUpsert {
	u.SetExcluded(seriesprovider.FieldContinueAfterChapter)
	return u
}

// AddContinueAfterChapter adds v to the "continue_after_chapter" field.
func (u *SeriesProviderUpsert) AddContinueAfterChapter(v float64) *SeriesProviderUpsert {
	u.Add(seriesprovider.FieldContinueAfterChapter, v)
	return u
}

// ClearContinueAfterChapter clears the value of the "continue_after_chapter" field.
func (u *SeriesProviderUpsert) ClearContinueAfterChapter() *SeriesProviderUpsert {
	u.SetNull(seriesprovider.FieldContinueAfterChapter)
	return u
}

// SetIsTitle sets the "is_title" field.
func (u *SeriesProviderUpsert) SetIsTitle(v bool) *SeriesProviderUpsert {
	u.Set(seriesprovider.FieldIsTitle, v)
	return u
}

// UpdateIsTitle sets the "is_title" field to the value that was provided on create.
func (u *SeriesProviderUpsert) UpdateIsTitle() *SeriesProviderUpsert {
	u.SetExcluded(seriesprovider.FieldIsTitle)
	return u
}

// SetIsCover sets the "is_cover" field.
func (u *SeriesProviderUpsert) SetIsCover(v bool) *SeriesProviderUpsert {
	u.Set(seriesprovider.FieldIsCover, v)
	return u
}

// UpdateIsCover sets the "is_cover" field to the value that was provided on create.
func (u *SeriesProviderUpsert) UpdateIsCover() *SeriesProviderUpsert {
	u.SetExcluded(seriesprovider.FieldIsCover)
	return u
}

// SetIsUnknown sets the "is_unknown" field.
func (u *SeriesProviderUpsert) SetIsUnknown(v bool) *SeriesProviderUpsert {
	u.Set(seriesprovider.FieldIsUnknown, v)
	return u
}

// UpdateIsUnknown sets the "is_unknown" field to the value that was provided on create.
func (u *SeriesProviderUpsert) UpdateIsUnknown() *SeriesProviderUpsert {
	u.SetExcluded(seriesprovider.FieldIsUnknown)
	return u
}

// SetImportance sets the "importance" field.
func (u *SeriesProviderUpsert) SetImportance(v int) *SeriesProviderUpsert {
	u.Set(seriesprovider.FieldImportance, v)
	return u
}

// UpdateImportance sets the "importance" field to the value that was provided on create.
func (u *SeriesProviderUpsert) UpdateImportance() *SeriesProviderUpsert {
	u.SetExcluded(seriesprovider.FieldImportance)
	return u
}

// AddImportance adds v to the "importance" field.
func (u *SeriesProviderUpsert) AddImportance(v int) *SeriesProviderUpsert {
	u.Add(seriesprovider.FieldImportance, v)
	return u
}

// SetIsDisabled sets the "is_disabled" field.
func (u *SeriesProviderUpsert) SetIsDisabled(v bool) *SeriesProviderUpsert {
	u.Set(seriesprovider.FieldIsDisabled, v)
	return u
}

// UpdateIsDisabled sets the "is_disabled" field to the value that was provided on create.
func (u *SeriesProviderUpsert) UpdateIsDisabled() *SeriesProviderUpsert {
	u.SetExcluded(seriesprovider.FieldIsDisabled)
	return u
}

// SetIsUninstalled sets the "is_uninstalled" field.
func (u *SeriesProviderUpsert) SetIsUninstalled(v bool) *SeriesProviderUpsert {
	u.Set(seriesprovider.FieldIsUninstalled, v)
	return u
}

// UpdateIsUninstalled sets the "is_uninstalled" field to the value that was provided on create.
func (u *SeriesProviderUpsert) UpdateIsUninstalled() *SeriesProviderUpsert {
	u.SetExcluded(seriesprovider.FieldIsUninstalled)
	return u
}

// SetStatus sets the "status" field.
func (u *SeriesProviderUpsert) SetStatus(v string) *SeriesProviderUpsert {
	u.Set(seriesprovider.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SeriesProviderUpsert) UpdateStatus() *SeriesProviderUpsert {
	u.SetExcluded(seriesprovider.FieldStatus)
	return u
}

// SetChapters sets the "chapters" field.
func (u *SeriesProviderUpsert) SetChapters(v []types.Chapter) *SeriesProviderUpsert {
	u.Set(seriesprovider.FieldChapters, v)
	return u
}

// UpdateChapters sets the "chapters" field to the value that was provided on create.
func (u *SeriesProviderUpsert) UpdateChapters() *SeriesProviderUpsert {
	u.SetExcluded(seriesprovider.FieldChapters)
	return u
}

// ClearChapters clears the value of the "chapters" field.
func (u *SeriesProviderUpsert) ClearChapters() *SeriesProviderUpsert {
	u.SetNull(seriesprovider.FieldChapters)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SeriesProvider.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(seriesprovider.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SeriesProviderUpsertOne) UpdateNewValues() *SeriesProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(seriesprovider.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SeriesProvider.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SeriesProviderUpsertOne) Ignore() *SeriesProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SeriesProviderUpsertOne) DoNothing() *SeriesProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SeriesProviderCreate.OnConflict
// documentation for more info.
func (u *SeriesProviderUpsertOne) Update(set func(*SeriesProviderUpsert)) *SeriesProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SeriesProviderUpsert{UpdateSet: update})
	}))
	return u
}

// SetSeriesID sets the "series_id" field.
func (u *SeriesProviderUpsertOne) SetSeriesID(v uuid.UUID) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetSeriesID(v)
	})
}

// UpdateSeriesID sets the "series_id" field to the value that was provided on create.
func (u *SeriesProviderUpsertOne) UpdateSeriesID() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateSeriesID()
	})
}

// SetSuwayomiID sets the "suwayomi_id" field.
func (u *SeriesProviderUpsertOne) SetSuwayomiID(v int) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetSuwayomiID(v)
	})
}

// AddSuwayomiID adds v to the "suwayomi_id" field.
func (u *SeriesProviderUpsertOne) AddSuwayomiID(v int) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.AddSuwayomiID(v)
	})
}

// UpdateSuwayomiID sets the "suwayomi_id" field to the value that was provided on create.
func (u *SeriesProviderUpsertOne) UpdateSuwayomiID() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateSuwayomiID()
	})
}

// SetProvider sets the "provider" field.
func (u *SeriesProviderUpsertOne) SetProvider(v string) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *SeriesProviderUpsertOne) UpdateProvider() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateProvider()
	})
}

// SetScanlator sets the "scanlator" field.
func (u *SeriesProviderUpsertOne) SetScanlator(v string) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetScanlator(v)
	})
}

// UpdateScanlator sets the "scanlator" field to the value that was provided on create.
func (u *SeriesProviderUpsertOne) UpdateScanlator() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateScanlator()
	})
}

// SetURL sets the "url" field.
func (u *SeriesProviderUpsertOne) SetURL(v string) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *SeriesProviderUpsertOne) UpdateURL() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateURL()
	})
}

// ClearURL clears the value of the "url" field.
func (u *SeriesProviderUpsertOne) ClearURL() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.ClearURL()
	})
}

// SetTitle sets the "title" field.
func (u *SeriesProviderUpsertOne) SetTitle(v string) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *SeriesProviderUpsertOne) UpdateTitle() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateTitle()
	})
}

// SetLanguage sets the "language" field.
func (u *SeriesProviderUpsertOne) SetLanguage(v string) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetLanguage(v)
	})
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *SeriesProviderUpsertOne) UpdateLanguage() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateLanguage()
	})
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (u *SeriesProviderUpsertOne) SetThumbnailURL(v string) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetThumbnailURL(v)
	})
}

// UpdateThumbnailURL sets the "thumbnail_url" field to the value that was provided on create.
func (u *SeriesProviderUpsertOne) UpdateThumbnailURL() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateThumbnailURL()
	})
}

// ClearThumbnailURL clears the value of the "thumbnail_url" field.
func (u *SeriesProviderUpsertOne) ClearThumbnailURL() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.ClearThumbnailURL()
	})
}

// SetArtist sets the "artist" field.
func (u *SeriesProviderUpsertOne) SetArtist(v string) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetArtist(v)
	})
}

// UpdateArtist sets the "artist" field to the value that was provided on create.
func (u *SeriesProviderUpsertOne) UpdateArtist() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateArtist()
	})
}

// ClearArtist clears the value of the "artist" field.
func (u *SeriesProviderUpsertOne) ClearArtist() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.ClearArtist()
	})
}

// SetAuthor sets the "author" field.
func (u *SeriesProviderUpsertOne) SetAuthor(v string) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetAuthor(v)
	})
}

// UpdateAuthor sets the "author" field to the value that was provided on create.
func (u *SeriesProviderUpsertOne) UpdateAuthor() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateAuthor()
	})
}

// ClearAuthor clears the value of the "author" field.
func (u *SeriesProviderUpsertOne) ClearAuthor() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.ClearAuthor()
	})
}

// SetDescription sets the "description" field.
func (u *SeriesProviderUpsertOne) SetDescription(v string) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SeriesProviderUpsertOne) UpdateDescription() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SeriesProviderUpsertOne) ClearDescription() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.ClearDescription()
	})
}

// SetGenre sets the "genre" field.
func (u *SeriesProviderUpsertOne) SetGenre(v []string) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetGenre(v)
	})
}

// UpdateGenre sets the "genre" field to the value that was provided on create.
func (u *SeriesProviderUpsertOne) UpdateGenre() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateGenre()
	})
}

// ClearGenre clears the value of the "genre" field.
func (u *SeriesProviderUpsertOne) ClearGenre() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.ClearGenre()
	})
}

// SetFetchDate sets the "fetch_date" field.
func (u *SeriesProviderUpsertOne) SetFetchDate(v time.Time) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetFetchDate(v)
	})
}

// UpdateFetchDate sets the "fetch_date" field to the value that was provided on create.
func (u *SeriesProviderUpsertOne) UpdateFetchDate() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateFetchDate()
	})
}

// ClearFetchDate clears the value of the "fetch_date" field.
func (u *SeriesProviderUpsertOne) ClearFetchDate() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.ClearFetchDate()
	})
}

// SetChapterCount sets the "chapter_count" field.
func (u *SeriesProviderUpsertOne) SetChapterCount(v int64) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetChapterCount(v)
	})
}

// AddChapterCount adds v to the "chapter_count" field.
func (u *SeriesProviderUpsertOne) AddChapterCount(v int64) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.AddChapterCount(v)
	})
}

// UpdateChapterCount sets the "chapter_count" field to the value that was provided on create.
func (u *SeriesProviderUpsertOne) UpdateChapterCount() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateChapterCount()
	})
}

// ClearChapterCount clears the value of the "chapter_count" field.
func (u *SeriesProviderUpsertOne) ClearChapterCount() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.ClearChapterCount()
	})
}

// SetContinueAfterChapter sets the "continue_after_chapter" field.
func (u *SeriesProviderUpsertOne) SetContinueAfterChapter(v float64) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetContinueAfterChapter(v)
	})
}

// AddContinueAfterChapter adds v to the "continue_after_chapter" field.
func (u *SeriesProviderUpsertOne) AddContinueAfterChapter(v float64) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.AddContinueAfterChapter(v)
	})
}

// UpdateContinueAfterChapter sets the "continue_after_chapter" field to the value that was provided on create.
func (u *SeriesProviderUpsertOne) UpdateContinueAfterChapter() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateContinueAfterChapter()
	})
}

// ClearContinueAfterChapter clears the value of the "continue_after_chapter" field.
func (u *SeriesProviderUpsertOne) ClearContinueAfterChapter() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.ClearContinueAfterChapter()
	})
}

// SetIsTitle sets the "is_title" field.
func (u *SeriesProviderUpsertOne) SetIsTitle(v bool) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetIsTitle(v)
	})
}

// UpdateIsTitle sets the "is_title" field to the value that was provided on create.
func (u *SeriesProviderUpsertOne) UpdateIsTitle() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateIsTitle()
	})
}

// SetIsCover sets the "is_cover" field.
func (u *SeriesProviderUpsertOne) SetIsCover(v bool) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetIsCover(v)
	})
}

// UpdateIsCover sets the "is_cover" field to the value that was provided on create.
func (u *SeriesProviderUpsertOne) UpdateIsCover() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateIsCover()
	})
}

// SetIsUnknown sets the "is_unknown" field.
func (u *SeriesProviderUpsertOne) SetIsUnknown(v bool) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetIsUnknown(v)
	})
}

// UpdateIsUnknown sets the "is_unknown" field to the value that was provided on create.
func (u *SeriesProviderUpsertOne) UpdateIsUnknown() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateIsUnknown()
	})
}

// SetImportance sets the "importance" field.
func (u *SeriesProviderUpsertOne) SetImportance(v int) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetImportance(v)
	})
}

// AddImportance adds v to the "importance" field.
func (u *SeriesProviderUpsertOne) AddImportance(v int) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.AddImportance(v)
	})
}

// UpdateImportance sets the "importance" field to the value that was provided on create.
func (u *SeriesProviderUpsertOne) UpdateImportance() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateImportance()
	})
}

// SetIsDisabled sets the "is_disabled" field.
func (u *SeriesProviderUpsertOne) SetIsDisabled(v bool) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetIsDisabled(v)
	})
}

// UpdateIsDisabled sets the "is_disabled" field to the value that was provided on create.
func (u *SeriesProviderUpsertOne) UpdateIsDisabled() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateIsDisabled()
	})
}

// SetIsUninstalled sets the "is_uninstalled" field.
func (u *SeriesProviderUpsertOne) SetIsUninstalled(v bool) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetIsUninstalled(v)
	})
}

// UpdateIsUninstalled sets the "is_uninstalled" field to the value that was provided on create.
func (u *SeriesProviderUpsertOne) UpdateIsUninstalled() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateIsUninstalled()
	})
}

// SetStatus sets the "status" field.
func (u *SeriesProviderUpsertOne) SetStatus(v string) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SeriesProviderUpsertOne) UpdateStatus() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateStatus()
	})
}

// SetChapters sets the "chapters" field.
func (u *SeriesProviderUpsertOne) SetChapters(v []types.Chapter) *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetChapters(v)
	})
}

// UpdateChapters sets the "chapters" field to the value that was provided on create.
func (u *SeriesProviderUpsertOne) UpdateChapters() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateChapters()
	})
}

// ClearChapters clears the value of the "chapters" field.
func (u *SeriesProviderUpsertOne) ClearChapters() *SeriesProviderUpsertOne {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.ClearChapters()
	})
}

// Exec executes the query.
func (u *SeriesProviderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SeriesProviderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SeriesProviderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SeriesProviderUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SeriesProviderUpsertOne.ID is not supported by MySQL driver. Use SeriesProviderUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SeriesProviderUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SeriesProviderCreateBulk is the builder for creating many SeriesProvider entities in bulk.
type SeriesProviderCreateBulk struct {
	config
	err      error
	builders []*SeriesProviderCreate
	conflict []sql.ConflictOption
}

// Save creates the SeriesProvider entities in the database.
func (_c *SeriesProviderCreateBulk) Save(ctx context.Context) ([]*SeriesProvider, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SeriesProvider, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SeriesProviderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SeriesProviderCreateBulk) SaveX(ctx context.Context) []*SeriesProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SeriesProviderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SeriesProviderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SeriesProvider.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SeriesProviderUpsert) {
//			SetSeriesID(v+v).
//		}).
//		Exec(ctx)
func (_c *SeriesProviderCreateBulk) OnConflict(opts ...sql.ConflictOption) *SeriesProviderUpsertBulk {
	_c.conflict = opts
	return &SeriesProviderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SeriesProvider.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SeriesProviderCreateBulk) OnConflictColumns(columns ...string) *SeriesProviderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SeriesProviderUpsertBulk{
		create: _c,
	}
}

// SeriesProviderUpsertBulk is the builder for "upsert"-ing
// a bulk of SeriesProvider nodes.
type SeriesProviderUpsertBulk struct {
	create *SeriesProviderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SeriesProvider.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(seriesprovider.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SeriesProviderUpsertBulk) UpdateNewValues() *SeriesProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(seriesprovider.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SeriesProvider.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SeriesProviderUpsertBulk) Ignore() *SeriesProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SeriesProviderUpsertBulk) DoNothing() *SeriesProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SeriesProviderCreateBulk.OnConflict
// documentation for more info.
func (u *SeriesProviderUpsertBulk) Update(set func(*SeriesProviderUpsert)) *SeriesProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SeriesProviderUpsert{UpdateSet: update})
	}))
	return u
}

// SetSeriesID sets the "series_id" field.
func (u *SeriesProviderUpsertBulk) SetSeriesID(v uuid.UUID) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetSeriesID(v)
	})
}

// UpdateSeriesID sets the "series_id" field to the value that was provided on create.
func (u *SeriesProviderUpsertBulk) UpdateSeriesID() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateSeriesID()
	})
}

// SetSuwayomiID sets the "suwayomi_id" field.
func (u *SeriesProviderUpsertBulk) SetSuwayomiID(v int) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetSuwayomiID(v)
	})
}

// AddSuwayomiID adds v to the "suwayomi_id" field.
func (u *SeriesProviderUpsertBulk) AddSuwayomiID(v int) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.AddSuwayomiID(v)
	})
}

// UpdateSuwayomiID sets the "suwayomi_id" field to the value that was provided on create.
func (u *SeriesProviderUpsertBulk) UpdateSuwayomiID() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateSuwayomiID()
	})
}

// SetProvider sets the "provider" field.
func (u *SeriesProviderUpsertBulk) SetProvider(v string) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *SeriesProviderUpsertBulk) UpdateProvider() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateProvider()
	})
}

// SetScanlator sets the "scanlator" field.
func (u *SeriesProviderUpsertBulk) SetScanlator(v string) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetScanlator(v)
	})
}

// UpdateScanlator sets the "scanlator" field to the value that was provided on create.
func (u *SeriesProviderUpsertBulk) UpdateScanlator() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateScanlator()
	})
}

// SetURL sets the "url" field.
func (u *SeriesProviderUpsertBulk) SetURL(v string) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *SeriesProviderUpsertBulk) UpdateURL() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateURL()
	})
}

// ClearURL clears the value of the "url" field.
func (u *SeriesProviderUpsertBulk) ClearURL() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.ClearURL()
	})
}

// SetTitle sets the "title" field.
func (u *SeriesProviderUpsertBulk) SetTitle(v string) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *SeriesProviderUpsertBulk) UpdateTitle() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateTitle()
	})
}

// SetLanguage sets the "language" field.
func (u *SeriesProviderUpsertBulk) SetLanguage(v string) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetLanguage(v)
	})
}

// UpdateLanguage sets the "language" field to the value that was provided on create.
func (u *SeriesProviderUpsertBulk) UpdateLanguage() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateLanguage()
	})
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (u *SeriesProviderUpsertBulk) SetThumbnailURL(v string) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetThumbnailURL(v)
	})
}

// UpdateThumbnailURL sets the "thumbnail_url" field to the value that was provided on create.
func (u *SeriesProviderUpsertBulk) UpdateThumbnailURL() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateThumbnailURL()
	})
}

// ClearThumbnailURL clears the value of the "thumbnail_url" field.
func (u *SeriesProviderUpsertBulk) ClearThumbnailURL() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.ClearThumbnailURL()
	})
}

// SetArtist sets the "artist" field.
func (u *SeriesProviderUpsertBulk) SetArtist(v string) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetArtist(v)
	})
}

// UpdateArtist sets the "artist" field to the value that was provided on create.
func (u *SeriesProviderUpsertBulk) UpdateArtist() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateArtist()
	})
}

// ClearArtist clears the value of the "artist" field.
func (u *SeriesProviderUpsertBulk) ClearArtist() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.ClearArtist()
	})
}

// SetAuthor sets the "author" field.
func (u *SeriesProviderUpsertBulk) SetAuthor(v string) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetAuthor(v)
	})
}

// UpdateAuthor sets the "author" field to the value that was provided on create.
func (u *SeriesProviderUpsertBulk) UpdateAuthor() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateAuthor()
	})
}

// ClearAuthor clears the value of the "author" field.
func (u *SeriesProviderUpsertBulk) ClearAuthor() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.ClearAuthor()
	})
}

// SetDescription sets the "description" field.
func (u *SeriesProviderUpsertBulk) SetDescription(v string) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SeriesProviderUpsertBulk) UpdateDescription() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SeriesProviderUpsertBulk) ClearDescription() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.ClearDescription()
	})
}

// SetGenre sets the "genre" field.
func (u *SeriesProviderUpsertBulk) SetGenre(v []string) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetGenre(v)
	})
}

// UpdateGenre sets the "genre" field to the value that was provided on create.
func (u *SeriesProviderUpsertBulk) UpdateGenre() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateGenre()
	})
}

// ClearGenre clears the value of the "genre" field.
func (u *SeriesProviderUpsertBulk) ClearGenre() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.ClearGenre()
	})
}

// SetFetchDate sets the "fetch_date" field.
func (u *SeriesProviderUpsertBulk) SetFetchDate(v time.Time) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetFetchDate(v)
	})
}

// UpdateFetchDate sets the "fetch_date" field to the value that was provided on create.
func (u *SeriesProviderUpsertBulk) UpdateFetchDate() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateFetchDate()
	})
}

// ClearFetchDate clears the value of the "fetch_date" field.
func (u *SeriesProviderUpsertBulk) ClearFetchDate() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.ClearFetchDate()
	})
}

// SetChapterCount sets the "chapter_count" field.
func (u *SeriesProviderUpsertBulk) SetChapterCount(v int64) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetChapterCount(v)
	})
}

// AddChapterCount adds v to the "chapter_count" field.
func (u *SeriesProviderUpsertBulk) AddChapterCount(v int64) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.AddChapterCount(v)
	})
}

// UpdateChapterCount sets the "chapter_count" field to the value that was provided on create.
func (u *SeriesProviderUpsertBulk) UpdateChapterCount() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateChapterCount()
	})
}

// ClearChapterCount clears the value of the "chapter_count" field.
func (u *SeriesProviderUpsertBulk) ClearChapterCount() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.ClearChapterCount()
	})
}

// SetContinueAfterChapter sets the "continue_after_chapter" field.
func (u *SeriesProviderUpsertBulk) SetContinueAfterChapter(v float64) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetContinueAfterChapter(v)
	})
}

// AddContinueAfterChapter adds v to the "continue_after_chapter" field.
func (u *SeriesProviderUpsertBulk) AddContinueAfterChapter(v float64) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.AddContinueAfterChapter(v)
	})
}

// UpdateContinueAfterChapter sets the "continue_after_chapter" field to the value that was provided on create.
func (u *SeriesProviderUpsertBulk) UpdateContinueAfterChapter() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateContinueAfterChapter()
	})
}

// ClearContinueAfterChapter clears the value of the "continue_after_chapter" field.
func (u *SeriesProviderUpsertBulk) ClearContinueAfterChapter() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.ClearContinueAfterChapter()
	})
}

// SetIsTitle sets the "is_title" field.
func (u *SeriesProviderUpsertBulk) SetIsTitle(v bool) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetIsTitle(v)
	})
}

// UpdateIsTitle sets the "is_title" field to the value that was provided on create.
func (u *SeriesProviderUpsertBulk) UpdateIsTitle() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateIsTitle()
	})
}

// SetIsCover sets the "is_cover" field.
func (u *SeriesProviderUpsertBulk) SetIsCover(v bool) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetIsCover(v)
	})
}

// UpdateIsCover sets the "is_cover" field to the value that was provided on create.
func (u *SeriesProviderUpsertBulk) UpdateIsCover() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateIsCover()
	})
}

// SetIsUnknown sets the "is_unknown" field.
func (u *SeriesProviderUpsertBulk) SetIsUnknown(v bool) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetIsUnknown(v)
	})
}

// UpdateIsUnknown sets the "is_unknown" field to the value that was provided on create.
func (u *SeriesProviderUpsertBulk) UpdateIsUnknown() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateIsUnknown()
	})
}

// SetImportance sets the "importance" field.
func (u *SeriesProviderUpsertBulk) SetImportance(v int) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetImportance(v)
	})
}

// AddImportance adds v to the "importance" field.
func (u *SeriesProviderUpsertBulk) AddImportance(v int) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.AddImportance(v)
	})
}

// UpdateImportance sets the "importance" field to the value that was provided on create.
func (u *SeriesProviderUpsertBulk) UpdateImportance() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateImportance()
	})
}

// SetIsDisabled sets the "is_disabled" field.
func (u *SeriesProviderUpsertBulk) SetIsDisabled(v bool) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetIsDisabled(v)
	})
}

// UpdateIsDisabled sets the "is_disabled" field to the value that was provided on create.
func (u *SeriesProviderUpsertBulk) UpdateIsDisabled() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateIsDisabled()
	})
}

// SetIsUninstalled sets the "is_uninstalled" field.
func (u *SeriesProviderUpsertBulk) SetIsUninstalled(v bool) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetIsUninstalled(v)
	})
}

// UpdateIsUninstalled sets the "is_uninstalled" field to the value that was provided on create.
func (u *SeriesProviderUpsertBulk) UpdateIsUninstalled() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateIsUninstalled()
	})
}

// SetStatus sets the "status" field.
func (u *SeriesProviderUpsertBulk) SetStatus(v string) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SeriesProviderUpsertBulk) UpdateStatus() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateStatus()
	})
}

// SetChapters sets the "chapters" field.
func (u *SeriesProviderUpsertBulk) SetChapters(v []types.Chapter) *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.SetChapters(v)
	})
}

// UpdateChapters sets the "chapters" field to the value that was provided on create.
func (u *SeriesProviderUpsertBulk) UpdateChapters() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.UpdateChapters()
	})
}

// ClearChapters clears the value of the "chapters" field.
func (u *SeriesProviderUpsertBulk) ClearChapters() *SeriesProviderUpsertBulk {
	return u.Update(func(s *SeriesProviderUpsert) {
		s.ClearChapters()
	})
}

// Exec executes the query.
func (u *SeriesProviderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SeriesProviderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SeriesProviderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SeriesProviderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
