// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/technobecet/kaizoku-go/internal/ent/latestseries"
	"github.com/technobecet/kaizoku-go/internal/ent/series"
	"github.com/technobecet/kaizoku-go/internal/ent/seriesprovider"
)

// SeriesCreate is the builder for creating a Series entity.
type SeriesCreate struct {
	config
	mutation *SeriesMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTitle sets the "title" field.
func (_c *SeriesCreate) SetTitle(v string) *SeriesCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (_c *SeriesCreate) SetThumbnailURL(v string) *SeriesCreate {
	_c.mutation.SetThumbnailURL(v)
	return _c
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableThumbnailURL(v *string) *SeriesCreate {
	if v != nil {
		_c.SetThumbnailURL(*v)
	}
	return _c
}

// SetArtist sets the "artist" field.
func (_c *SeriesCreate) SetArtist(v string) *SeriesCreate {
	_c.mutation.SetArtist(v)
	return _c
}

// SetNillableArtist sets the "artist" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableArtist(v *string) *SeriesCreate {
	if v != nil {
		_c.SetArtist(*v)
	}
	return _c
}

// SetAuthor sets the "author" field.
func (_c *SeriesCreate) SetAuthor(v string) *SeriesCreate {
	_c.mutation.SetAuthor(v)
	return _c
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableAuthor(v *string) *SeriesCreate {
	if v != nil {
		_c.SetAuthor(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *SeriesCreate) SetDescription(v string) *SeriesCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableDescription(v *string) *SeriesCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetGenre sets the "genre" field.
func (_c *SeriesCreate) SetGenre(v []string) *SeriesCreate {
	_c.mutation.SetGenre(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *SeriesCreate) SetStatus(v string) *SeriesCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableStatus(v *string) *SeriesCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetStoragePath sets the "storage_path" field.
func (_c *SeriesCreate) SetStoragePath(v string) *SeriesCreate {
	_c.mutation.SetStoragePath(v)
	return _c
}

// SetNillableStoragePath sets the "storage_path" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableStoragePath(v *string) *SeriesCreate {
	if v != nil {
		_c.SetStoragePath(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *SeriesCreate) SetType(v string) *SeriesCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableType(v *string) *SeriesCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetChapterCount sets the "chapter_count" field.
func (_c *SeriesCreate) SetChapterCount(v int) *SeriesCreate {
	_c.mutation.SetChapterCount(v)
	return _c
}

// SetNillableChapterCount sets the "chapter_count" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableChapterCount(v *int) *SeriesCreate {
	if v != nil {
		_c.SetChapterCount(*v)
	}
	return _c
}

// SetPauseDownloads sets the "pause_downloads" field.
func (_c *SeriesCreate) SetPauseDownloads(v bool) *SeriesCreate {
	_c.mutation.SetPauseDownloads(v)
	return _c
}

// SetNillablePauseDownloads sets the "pause_downloads" field if the given value is not nil.
func (_c *SeriesCreate) SetNillablePauseDownloads(v *bool) *SeriesCreate {
	if v != nil {
		_c.SetPauseDownloads(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SeriesCreate) SetID(v uuid.UUID) *SeriesCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SeriesCreate) SetNillableID(v *uuid.UUID) *SeriesCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddProviderIDs adds the "providers" edge to the SeriesProvider entity by IDs.
func (_c *SeriesCreate) AddProviderIDs(ids ...uuid.UUID) *SeriesCreate {
	_c.mutation.AddProviderIDs(ids...)
	return _c
}

// AddProviders adds the "providers" edges to the SeriesProvider entity.
func (_c *SeriesCreate) AddProviders(v ...*SeriesProvider) *SeriesCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddProviderIDs(ids...)
}

// AddLatestSeriesIDs adds the "latest_series" edge to the LatestSeries entity by IDs.
func (_c *SeriesCreate) AddLatestSeriesIDs(ids ...int) *SeriesCreate {
	_c.mutation.AddLatestSeriesIDs(ids...)
	return _c
}

// AddLatestSeries adds the "latest_series" edges to the LatestSeries entity.
func (_c *SeriesCreate) AddLatestSeries(v ...*LatestSeries) *SeriesCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLatestSeriesIDs(ids...)
}

// Mutation returns the SeriesMutation object of the builder.
func (_c *SeriesCreate) Mutation() *SeriesMutation {
	return _c.mutation
}

// Save creates the Series in the database.
func (_c *SeriesCreate) Save(ctx context.Context) (*Series, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SeriesCreate) SaveX(ctx context.Context) *Series {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SeriesCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SeriesCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SeriesCreate) defaults() {
	if _, ok := _c.mutation.ThumbnailURL(); !ok {
		v := series.DefaultThumbnailURL
		_c.mutation.SetThumbnailURL(v)
	}
	if _, ok := _c.mutation.Artist(); !ok {
		v := series.DefaultArtist
		_c.mutation.SetArtist(v)
	}
	if _, ok := _c.mutation.Author(); !ok {
		v := series.DefaultAuthor
		_c.mutation.SetAuthor(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := series.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := series.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ChapterCount(); !ok {
		v := series.DefaultChapterCount
		_c.mutation.SetChapterCount(v)
	}
	if _, ok := _c.mutation.PauseDownloads(); !ok {
		v := series.DefaultPauseDownloads
		_c.mutation.SetPauseDownloads(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := series.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SeriesCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Series.title"`)}
	}
	if _, ok := _c.mutation.ThumbnailURL(); !ok {
		return &ValidationError{Name: "thumbnail_url", err: errors.New(`ent: missing required field "Series.thumbnail_url"`)}
	}
	if _, ok := _c.mutation.Artist(); !ok {
		return &ValidationError{Name: "artist", err: errors.New(`ent: missing required field "Series.artist"`)}
	}
	if _, ok := _c.mutation.Author(); !ok {
		return &ValidationError{Name: "author", err: errors.New(`ent: missing required field "Series.author"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Series.description"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Series.status"`)}
	}
	if _, ok := _c.mutation.ChapterCount(); !ok {
		return &ValidationError{Name: "chapter_count", err: errors.New(`ent: missing required field "Series.chapter_count"`)}
	}
	if _, ok := _c.mutation.PauseDownloads(); !ok {
		return &ValidationError{Name: "pause_downloads", err: errors.New(`ent: missing required field "Series.pause_downloads"`)}
	}
	return nil
}

func (_c *SeriesCreate) sqlSave(ctx context.Context) (*Series, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SeriesCreate) createSpec() (*Series, *sqlgraph.CreateSpec) {
	var (
		_node = &Series{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(series.Table, sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(series.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.ThumbnailURL(); ok {
		_spec.SetField(series.FieldThumbnailURL, field.TypeString, value)
		_node.ThumbnailURL = value
	}
	if value, ok := _c.mutation.Artist(); ok {
		_spec.SetField(series.FieldArtist, field.TypeString, value)
		_node.Artist = value
	}
	if value, ok := _c.mutation.Author(); ok {
		_spec.SetField(series.FieldAuthor, field.TypeString, value)
		_node.Author = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(series.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Genre(); ok {
		_spec.SetField(series.FieldGenre, field.TypeJSON, value)
		_node.Genre = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(series.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.StoragePath(); ok {
		_spec.SetField(series.FieldStoragePath, field.TypeString, value)
		_node.StoragePath = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(series.FieldType, field.TypeString, value)
		_node.Type = &value
	}
	if value, ok := _c.mutation.ChapterCount(); ok {
		_spec.SetField(series.FieldChapterCount, field.TypeInt, value)
		_node.ChapterCount = value
	}
	if value, ok := _c.mutation.PauseDownloads(); ok {
		_spec.SetField(series.FieldPauseDownloads, field.TypeBool, value)
		_node.PauseDownloads = value
	}
	if nodes := _c.mutation.ProvidersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   series.ProvidersTable,
			Columns: []string{series.ProvidersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(seriesprovider.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LatestSeriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   series.LatestSeriesTable,
			Columns: []string{series.LatestSeriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(latestseries.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Series.Create().
//		SetTitle(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SeriesUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *SeriesCreate) OnConflict(opts ...sql.ConflictOption) *SeriesUpsertOne {
	_c.conflict = opts
	return &SeriesUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Series.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SeriesCreate) OnConflictColumns(columns ...string) *SeriesUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SeriesUpsertOne{
		create: _c,
	}
}

type (
	// SeriesUpsertOne is the builder for "upsert"-ing
	//  one Series node.
	SeriesUpsertOne struct {
		create *SeriesCreate
	}

	// SeriesUpsert is the "OnConflict" setter.
	SeriesUpsert struct {
		*sql.UpdateSet
	}
)

// SetTitle sets the "title" field.
func (u *SeriesUpsert) SetTitle(v string) *SeriesUpsert {
	u.Set(series.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *SeriesUpsert) UpdateTitle() *SeriesUpsert {
	u.SetExcluded(series.FieldTitle)
	return u
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (u *SeriesUpsert) SetThumbnailURL(v string) *SeriesUpsert {
	u.Set(series.FieldThumbnailURL, v)
	return u
}

// UpdateThumbnailURL sets the "thumbnail_url" field to the value that was provided on create.
func (u *SeriesUpsert) UpdateThumbnailURL() *SeriesUpsert {
	u.SetExcluded(series.FieldThumbnailURL)
	return u
}

// SetArtist sets the "artist" field.
func (u *SeriesUpsert) SetArtist(v string) *SeriesUpsert {
	u.Set(series.FieldArtist, v)
	return u
}

// UpdateArtist sets the "artist" field to the value that was provided on create.
func (u *SeriesUpsert) UpdateArtist() *SeriesUpsert {
	u.SetExcluded(series.FieldArtist)
	return u
}

// SetAuthor sets the "author" field.
func (u *SeriesUpsert) SetAuthor(v string) *SeriesUpsert {
	u.Set(series.FieldAuthor, v)
	return u
}

// UpdateAuthor sets the "author" field to the value that was provided on create.
func (u *SeriesUpsert) UpdateAuthor() *SeriesUpsert {
	u.SetExcluded(series.FieldAuthor)
	return u
}

// SetDescription sets the "description" field.
func (u *SeriesUpsert) SetDescription(v string) *SeriesUpsert {
	u.Set(series.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SeriesUpsert) UpdateDescription() *SeriesUpsert {
	u.SetExcluded(series.FieldDescription)
	return u
}

// SetGenre sets the "genre" field.
func (u *SeriesUpsert) SetGenre(v []string) *SeriesUpsert {
	u.Set(series.FieldGenre, v)
	return u
}

// UpdateGenre sets the "genre" field to the value that was provided on create.
func (u *SeriesUpsert) UpdateGenre() *SeriesUpsert {
	u.SetExcluded(series.FieldGenre)
	return u
}

// ClearGenre clears the value of the "genre" field.
func (u *SeriesUpsert) ClearGenre() *SeriesUpsert {
	u.SetNull(series.FieldGenre)
	return u
}

// SetStatus sets the "status" field.
func (u *SeriesUpsert) SetStatus(v string) *SeriesUpsert {
	u.Set(series.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SeriesUpsert) UpdateStatus() *SeriesUpsert {
	u.SetExcluded(series.FieldStatus)
	return u
}

// SetStoragePath sets the "storage_path" field.
func (u *SeriesUpsert) SetStoragePath(v string) *SeriesUpsert {
	u.Set(series.FieldStoragePath, v)
	return u
}

// UpdateStoragePath sets the "storage_path" field to the value that was provided on create.
func (u *SeriesUpsert) UpdateStoragePath() *SeriesUpsert {
	u.SetExcluded(series.FieldStoragePath)
	return u
}

// ClearStoragePath clears the value of the "storage_path" field.
func (u *SeriesUpsert) ClearStoragePath() *SeriesUpsert {
	u.SetNull(series.FieldStoragePath)
	return u
}

// SetType sets the "type" field.
func (u *SeriesUpsert) SetType(v string) *SeriesUpsert {
	u.Set(series.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *SeriesUpsert) UpdateType() *SeriesUpsert {
	u.SetExcluded(series.FieldType)
	return u
}

// ClearType clears the value of the "type" field.
func (u *SeriesUpsert) ClearType() *SeriesUpsert {
	u.SetNull(series.FieldType)
	return u
}

// SetChapterCount sets the "chapter_count" field.
func (u *SeriesUpsert) SetChapterCount(v int) *SeriesUpsert {
	u.Set(series.FieldChapterCount, v)
	return u
}

// UpdateChapterCount sets the "chapter_count" field to the value that was provided on create.
func (u *SeriesUpsert) UpdateChapterCount() *SeriesUpsert {
	u.SetExcluded(series.FieldChapterCount)
	return u
}

// AddChapterCount adds v to the "chapter_count" field.
func (u *SeriesUpsert) AddChapterCount(v int) *SeriesUpsert {
	u.Add(series.FieldChapterCount, v)
	return u
}

// SetPauseDownloads sets the "pause_downloads" field.
func (u *SeriesUpsert) SetPauseDownloads(v bool) *SeriesUpsert {
	u.Set(series.FieldPauseDownloads, v)
	return u
}

// UpdatePauseDownloads sets the "pause_downloads" field to the value that was provided on create.
func (u *SeriesUpsert) UpdatePauseDownloads() *SeriesUpsert {
	u.SetExcluded(series.FieldPauseDownloads)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Series.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(series.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SeriesUpsertOne) UpdateNewValues() *SeriesUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(series.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Series.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SeriesUpsertOne) Ignore() *SeriesUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SeriesUpsertOne) DoNothing() *SeriesUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SeriesCreate.OnConflict
// documentation for more info.
func (u *SeriesUpsertOne) Update(set func(*SeriesUpsert)) *SeriesUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SeriesUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *SeriesUpsertOne) SetTitle(v string) *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *SeriesUpsertOne) UpdateTitle() *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateTitle()
	})
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (u *SeriesUpsertOne) SetThumbnailURL(v string) *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.SetThumbnailURL(v)
	})
}

// UpdateThumbnailURL sets the "thumbnail_url" field to the value that was provided on create.
func (u *SeriesUpsertOne) UpdateThumbnailURL() *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateThumbnailURL()
	})
}

// SetArtist sets the "artist" field.
func (u *SeriesUpsertOne) SetArtist(v string) *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.SetArtist(v)
	})
}

// UpdateArtist sets the "artist" field to the value that was provided on create.
func (u *SeriesUpsertOne) UpdateArtist() *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateArtist()
	})
}

// SetAuthor sets the "author" field.
func (u *SeriesUpsertOne) SetAuthor(v string) *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.SetAuthor(v)
	})
}

// UpdateAuthor sets the "author" field to the value that was provided on create.
func (u *SeriesUpsertOne) UpdateAuthor() *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateAuthor()
	})
}

// SetDescription sets the "description" field.
func (u *SeriesUpsertOne) SetDescription(v string) *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SeriesUpsertOne) UpdateDescription() *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateDescription()
	})
}

// SetGenre sets the "genre" field.
func (u *SeriesUpsertOne) SetGenre(v []string) *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.SetGenre(v)
	})
}

// UpdateGenre sets the "genre" field to the value that was provided on create.
func (u *SeriesUpsertOne) UpdateGenre() *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateGenre()
	})
}

// ClearGenre clears the value of the "genre" field.
func (u *SeriesUpsertOne) ClearGenre() *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.ClearGenre()
	})
}

// SetStatus sets the "status" field.
func (u *SeriesUpsertOne) SetStatus(v string) *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SeriesUpsertOne) UpdateStatus() *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateStatus()
	})
}

// SetStoragePath sets the "storage_path" field.
func (u *SeriesUpsertOne) SetStoragePath(v string) *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.SetStoragePath(v)
	})
}

// UpdateStoragePath sets the "storage_path" field to the value that was provided on create.
func (u *SeriesUpsertOne) UpdateStoragePath() *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateStoragePath()
	})
}

// ClearStoragePath clears the value of the "storage_path" field.
func (u *SeriesUpsertOne) ClearStoragePath() *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.ClearStoragePath()
	})
}

// SetType sets the "type" field.
func (u *SeriesUpsertOne) SetType(v string) *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *SeriesUpsertOne) UpdateType() *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateType()
	})
}

// ClearType clears the value of the "type" field.
func (u *SeriesUpsertOne) ClearType() *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.ClearType()
	})
}

// SetChapterCount sets the "chapter_count" field.
func (u *SeriesUpsertOne) SetChapterCount(v int) *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.SetChapterCount(v)
	})
}

// AddChapterCount adds v to the "chapter_count" field.
func (u *SeriesUpsertOne) AddChapterCount(v int) *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.AddChapterCount(v)
	})
}

// UpdateChapterCount sets the "chapter_count" field to the value that was provided on create.
func (u *SeriesUpsertOne) UpdateChapterCount() *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateChapterCount()
	})
}

// SetPauseDownloads sets the "pause_downloads" field.
func (u *SeriesUpsertOne) SetPauseDownloads(v bool) *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.SetPauseDownloads(v)
	})
}

// UpdatePauseDownloads sets the "pause_downloads" field to the value that was provided on create.
func (u *SeriesUpsertOne) UpdatePauseDownloads() *SeriesUpsertOne {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdatePauseDownloads()
	})
}

// Exec executes the query.
func (u *SeriesUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SeriesCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SeriesUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SeriesUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SeriesUpsertOne.ID is not supported by MySQL driver. Use SeriesUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SeriesUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SeriesCreateBulk is the builder for creating many Series entities in bulk.
type SeriesCreateBulk struct {
	config
	err      error
	builders []*SeriesCreate
	conflict []sql.ConflictOption
}

// Save creates the Series entities in the database.
func (_c *SeriesCreateBulk) Save(ctx context.Context) ([]*Series, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Series, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SeriesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SeriesCreateBulk) SaveX(ctx context.Context) []*Series {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SeriesCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SeriesCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Series.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SeriesUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *SeriesCreateBulk) OnConflict(opts ...sql.ConflictOption) *SeriesUpsertBulk {
	_c.conflict = opts
	return &SeriesUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Series.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SeriesCreateBulk) OnConflictColumns(columns ...string) *SeriesUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SeriesUpsertBulk{
		create: _c,
	}
}

// SeriesUpsertBulk is the builder for "upsert"-ing
// a bulk of Series nodes.
type SeriesUpsertBulk struct {
	create *SeriesCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Series.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(series.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SeriesUpsertBulk) UpdateNewValues() *SeriesUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(series.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Series.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SeriesUpsertBulk) Ignore() *SeriesUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SeriesUpsertBulk) DoNothing() *SeriesUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SeriesCreateBulk.OnConflict
// documentation for more info.
func (u *SeriesUpsertBulk) Update(set func(*SeriesUpsert)) *SeriesUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SeriesUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *SeriesUpsertBulk) SetTitle(v string) *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *SeriesUpsertBulk) UpdateTitle() *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateTitle()
	})
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (u *SeriesUpsertBulk) SetThumbnailURL(v string) *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.SetThumbnailURL(v)
	})
}

// UpdateThumbnailURL sets the "thumbnail_url" field to the value that was provided on create.
func (u *SeriesUpsertBulk) UpdateThumbnailURL() *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateThumbnailURL()
	})
}

// SetArtist sets the "artist" field.
func (u *SeriesUpsertBulk) SetArtist(v string) *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.SetArtist(v)
	})
}

// UpdateArtist sets the "artist" field to the value that was provided on create.
func (u *SeriesUpsertBulk) UpdateArtist() *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateArtist()
	})
}

// SetAuthor sets the "author" field.
func (u *SeriesUpsertBulk) SetAuthor(v string) *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.SetAuthor(v)
	})
}

// UpdateAuthor sets the "author" field to the value that was provided on create.
func (u *SeriesUpsertBulk) UpdateAuthor() *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateAuthor()
	})
}

// SetDescription sets the "description" field.
func (u *SeriesUpsertBulk) SetDescription(v string) *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SeriesUpsertBulk) UpdateDescription() *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateDescription()
	})
}

// SetGenre sets the "genre" field.
func (u *SeriesUpsertBulk) SetGenre(v []string) *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.SetGenre(v)
	})
}

// UpdateGenre sets the "genre" field to the value that was provided on create.
func (u *SeriesUpsertBulk) UpdateGenre() *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateGenre()
	})
}

// ClearGenre clears the value of the "genre" field.
func (u *SeriesUpsertBulk) ClearGenre() *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.ClearGenre()
	})
}

// SetStatus sets the "status" field.
func (u *SeriesUpsertBulk) SetStatus(v string) *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SeriesUpsertBulk) UpdateStatus() *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateStatus()
	})
}

// SetStoragePath sets the "storage_path" field.
func (u *SeriesUpsertBulk) SetStoragePath(v string) *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.SetStoragePath(v)
	})
}

// UpdateStoragePath sets the "storage_path" field to the value that was provided on create.
func (u *SeriesUpsertBulk) UpdateStoragePath() *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateStoragePath()
	})
}

// ClearStoragePath clears the value of the "storage_path" field.
func (u *SeriesUpsertBulk) ClearStoragePath() *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.ClearStoragePath()
	})
}

// SetType sets the "type" field.
func (u *SeriesUpsertBulk) SetType(v string) *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *SeriesUpsertBulk) UpdateType() *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateType()
	})
}

// ClearType clears the value of the "type" field.
func (u *SeriesUpsertBulk) ClearType() *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.ClearType()
	})
}

// SetChapterCount sets the "chapter_count" field.
func (u *SeriesUpsertBulk) SetChapterCount(v int) *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.SetChapterCount(v)
	})
}

// AddChapterCount adds v to the "chapter_count" field.
func (u *SeriesUpsertBulk) AddChapterCount(v int) *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.AddChapterCount(v)
	})
}

// UpdateChapterCount sets the "chapter_count" field to the value that was provided on create.
func (u *SeriesUpsertBulk) UpdateChapterCount() *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdateChapterCount()
	})
}

// SetPauseDownloads sets the "pause_downloads" field.
func (u *SeriesUpsertBulk) SetPauseDownloads(v bool) *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.SetPauseDownloads(v)
	})
}

// UpdatePauseDownloads sets the "pause_downloads" field to the value that was provided on create.
func (u *SeriesUpsertBulk) UpdatePauseDownloads() *SeriesUpsertBulk {
	return u.Update(func(s *SeriesUpsert) {
		s.UpdatePauseDownloads()
	})
}

// Exec executes the query.
func (u *SeriesUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SeriesCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SeriesCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SeriesUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
