// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/technobecet/kaizoku-go/internal/ent/predicate"
	"github.com/technobecet/kaizoku-go/internal/ent/series"
	"github.com/technobecet/kaizoku-go/internal/ent/seriesprovider"
	"github.com/technobecet/kaizoku-go/internal/types"
)

// SeriesProviderUpdate is the builder for updating SeriesProvider entities.
type SeriesProviderUpdate struct {
	config
	hooks    []Hook
	mutation *SeriesProviderMutation
}

// Where appends a list predicates to the SeriesProviderUpdate builder.
func (_u *SeriesProviderUpdate) Where(ps ...predicate.SeriesProvider) *SeriesProviderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSeriesID sets the "series_id" field.
func (_u *SeriesProviderUpdate) SetSeriesID(v uuid.UUID) *SeriesProviderUpdate {
	_u.mutation.SetSeriesID(v)
	return _u
}

// SetNillableSeriesID sets the "series_id" field if the given value is not nil.
func (_u *SeriesProviderUpdate) SetNillableSeriesID(v *uuid.UUID) *SeriesProviderUpdate {
	if v != nil {
		_u.SetSeriesID(*v)
	}
	return _u
}

// SetSuwayomiID sets the "suwayomi_id" field.
func (_u *SeriesProviderUpdate) SetSuwayomiID(v int) *SeriesProviderUpdate {
	_u.mutation.ResetSuwayomiID()
	_u.mutation.SetSuwayomiID(v)
	return _u
}

// SetNillableSuwayomiID sets the "suwayomi_id" field if the given value is not nil.
func (_u *SeriesProviderUpdate) SetNillableSuwayomiID(v *int) *SeriesProviderUpdate {
	if v != nil {
		_u.SetSuwayomiID(*v)
	}
	return _u
}

// AddSuwayomiID adds value to the "suwayomi_id" field.
func (_u *SeriesProviderUpdate) AddSuwayomiID(v int) *SeriesProviderUpdate {
	_u.mutation.AddSuwayomiID(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *SeriesProviderUpdate) SetProvider(v string) *SeriesProviderUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *SeriesProviderUpdate) SetNillableProvider(v *string) *SeriesProviderUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetScanlator sets the "scanlator" field.
func (_u *SeriesProviderUpdate) SetScanlator(v string) *SeriesProviderUpdate {
	_u.mutation.SetScanlator(v)
	return _u
}

// SetNillableScanlator sets the "scanlator" field if the given value is not nil.
func (_u *SeriesProviderUpdate) SetNillableScanlator(v *string) *SeriesProviderUpdate {
	if v != nil {
		_u.SetScanlator(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *SeriesProviderUpdate) SetURL(v string) *SeriesProviderUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *SeriesProviderUpdate) SetNillableURL(v *string) *SeriesProviderUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *SeriesProviderUpdate) ClearURL() *SeriesProviderUpdate {
	_u.mutation.ClearURL()
	return _u
}

// SetTitle sets the "title" field.
func (_u *SeriesProviderUpdate) SetTitle(v string) *SeriesProviderUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SeriesProviderUpdate) SetNillableTitle(v *string) *SeriesProviderUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *SeriesProviderUpdate) SetLanguage(v string) *SeriesProviderUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *SeriesProviderUpdate) SetNillableLanguage(v *string) *SeriesProviderUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (_u *SeriesProviderUpdate) SetThumbnailURL(v string) *SeriesProviderUpdate {
	_u.mutation.SetThumbnailURL(v)
	return _u
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (_u *SeriesProviderUpdate) SetNillableThumbnailURL(v *string) *SeriesProviderUpdate {
	if v != nil {
		_u.SetThumbnailURL(*v)
	}
	return _u
}

// ClearThumbnailURL clears the value of the "thumbnail_url" field.
func (_u *SeriesProviderUpdate) ClearThumbnailURL() *SeriesProviderUpdate {
	_u.mutation.ClearThumbnailURL()
	return _u
}

// SetArtist sets the "artist" field.
func (_u *SeriesProviderUpdate) SetArtist(v string) *SeriesProviderUpdate {
	_u.mutation.SetArtist(v)
	return _u
}

// SetNillableArtist sets the "artist" field if the given value is not nil.
func (_u *SeriesProviderUpdate) SetNillableArtist(v *string) *SeriesProviderUpdate {
	if v != nil {
		_u.SetArtist(*v)
	}
	return _u
}

// ClearArtist clears the value of the "artist" field.
func (_u *SeriesProviderUpdate) ClearArtist() *SeriesProviderUpdate {
	_u.mutation.ClearArtist()
	return _u
}

// SetAuthor sets the "author" field.
func (_u *SeriesProviderUpdate) SetAuthor(v string) *SeriesProviderUpdate {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *SeriesProviderUpdate) SetNillableAuthor(v *string) *SeriesProviderUpdate {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// ClearAuthor clears the value of the "author" field.
func (_u *SeriesProviderUpdate) ClearAuthor() *SeriesProviderUpdate {
	_u.mutation.ClearAuthor()
	return _u
}

// SetDescription sets the "description" field.
func (_u *SeriesProviderUpdate) SetDescription(v string) *SeriesProviderUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SeriesProviderUpdate) SetNillableDescription(v *string) *SeriesProviderUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SeriesProviderUpdate) ClearDescription() *SeriesProviderUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetGenre sets the "genre" field.
func (_u *SeriesProviderUpdate) SetGenre(v []string) *SeriesProviderUpdate {
	_u.mutation.SetGenre(v)
	return _u
}

// AppendGenre appends value to the "genre" field.
func (_u *SeriesProviderUpdate) AppendGenre(v []string) *SeriesProviderUpdate {
	_u.mutation.AppendGenre(v)
	return _u
}

// ClearGenre clears the value of the "genre" field.
func (_u *SeriesProviderUpdate) ClearGenre() *SeriesProviderUpdate {
	_u.mutation.ClearGenre()
	return _u
}

// SetFetchDate sets the "fetch_date" field.
func (_u *SeriesProviderUpdate) SetFetchDate(v time.Time) *SeriesProviderUpdate {
	_u.mutation.SetFetchDate(v)
	return _u
}

// SetNillableFetchDate sets the "fetch_date" field if the given value is not nil.
func (_u *SeriesProviderUpdate) SetNillableFetchDate(v *time.Time) *SeriesProviderUpdate {
	if v != nil {
		_u.SetFetchDate(*v)
	}
	return _u
}

// ClearFetchDate clears the value of the "fetch_date" field.
func (_u *SeriesProviderUpdate) ClearFetchDate() *SeriesProviderUpdate {
	_u.mutation.ClearFetchDate()
	return _u
}

// SetChapterCount sets the "chapter_count" field.
func (_u *SeriesProviderUpdate) SetChapterCount(v int64) *SeriesProviderUpdate {
	_u.mutation.ResetChapterCount()
	_u.mutation.SetChapterCount(v)
	return _u
}

// SetNillableChapterCount sets the "chapter_count" field if the given value is not nil.
func (_u *SeriesProviderUpdate) SetNillableChapterCount(v *int64) *SeriesProviderUpdate {
	if v != nil {
		_u.SetChapterCount(*v)
	}
	return _u
}

// AddChapterCount adds value to the "chapter_count" field.
func (_u *SeriesProviderUpdate) AddChapterCount(v int64) *SeriesProviderUpdate {
	_u.mutation.AddChapterCount(v)
	return _u
}

// ClearChapterCount clears the value of the "chapter_count" field.
func (_u *SeriesProviderUpdate) ClearChapterCount() *SeriesProviderUpdate {
	_u.mutation.ClearChapterCount()
	return _u
}

// SetContinueAfterChapter sets the "continue_after_chapter" field.
func (_u *SeriesProviderUpdate) SetContinueAfterChapter(v float64) *SeriesProviderUpdate {
	_u.mutation.ResetContinueAfterChapter()
	_u.mutation.SetContinueAfterChapter(v)
	return _u
}

// SetNillableContinueAfterChapter sets the "continue_after_chapter" field if the given value is not nil.
func (_u *SeriesProviderUpdate) SetNillableContinueAfterChapter(v *float64) *SeriesProviderUpdate {
	if v != nil {
		_u.SetContinueAfterChapter(*v)
	}
	return _u
}

// AddContinueAfterChapter adds value to the "continue_after_chapter" field.
func (_u *SeriesProviderUpdate) AddContinueAfterChapter(v float64) *SeriesProviderUpdate {
	_u.mutation.AddContinueAfterChapter(v)
	return _u
}

// ClearContinueAfterChapter clears the value of the "continue_after_chapter" field.
func (_u *SeriesProviderUpdate) ClearContinueAfterChapter() *SeriesProviderUpdate {
	_u.mutation.ClearContinueAfterChapter()
	return _u
}

// SetIsTitle sets the "is_title" field.
func (_u *SeriesProviderUpdate) SetIsTitle(v bool) *SeriesProviderUpdate {
	_u.mutation.SetIsTitle(v)
	return _u
}

// SetNillableIsTitle sets the "is_title" field if the given value is not nil.
func (_u *SeriesProviderUpdate) SetNillableIsTitle(v *bool) *SeriesProviderUpdate {
	if v != nil {
		_u.SetIsTitle(*v)
	}
	return _u
}

// SetIsCover sets the "is_cover" field.
func (_u *SeriesProviderUpdate) SetIsCover(v bool) *SeriesProviderUpdate {
	_u.mutation.SetIsCover(v)
	return _u
}

// SetNillableIsCover sets the "is_cover" field if the given value is not nil.
func (_u *SeriesProviderUpdate) SetNillableIsCover(v *bool) *SeriesProviderUpdate {
	if v != nil {
		_u.SetIsCover(*v)
	}
	return _u
}

// SetIsUnknown sets the "is_unknown" field.
func (_u *SeriesProviderUpdate) SetIsUnknown(v bool) *SeriesProviderUpdate {
	_u.mutation.SetIsUnknown(v)
	return _u
}

// SetNillableIsUnknown sets the "is_unknown" field if the given value is not nil.
func (_u *SeriesProviderUpdate) SetNillableIsUnknown(v *bool) *SeriesProviderUpdate {
	if v != nil {
		_u.SetIsUnknown(*v)
	}
	return _u
}

// SetImportance sets the "importance" field.
func (_u *SeriesProviderUpdate) SetImportance(v int) *SeriesProviderUpdate {
	_u.mutation.ResetImportance()
	_u.mutation.SetImportance(v)
	return _u
}

// SetNillableImportance sets the "importance" field if the given value is not nil.
func (_u *SeriesProviderUpdate) SetNillableImportance(v *int) *SeriesProviderUpdate {
	if v != nil {
		_u.SetImportance(*v)
	}
	return _u
}

// AddImportance adds value to the "importance" field.
func (_u *SeriesProviderUpdate) AddImportance(v int) *SeriesProviderUpdate {
	_u.mutation.AddImportance(v)
	return _u
}

// SetIsDisabled sets the "is_disabled" field.
func (_u *SeriesProviderUpdate) SetIsDisabled(v bool) *SeriesProviderUpdate {
	_u.mutation.SetIsDisabled(v)
	return _u
}

// SetNillableIsDisabled sets the "is_disabled" field if the given value is not nil.
func (_u *SeriesProviderUpdate) SetNillableIsDisabled(v *bool) *SeriesProviderUpdate {
	if v != nil {
		_u.SetIsDisabled(*v)
	}
	return _u
}

// SetIsUninstalled sets the "is_uninstalled" field.
func (_u *SeriesProviderUpdate) SetIsUninstalled(v bool) *SeriesProviderUpdate {
	_u.mutation.SetIsUninstalled(v)
	return _u
}

// SetNillableIsUninstalled sets the "is_uninstalled" field if the given value is not nil.
func (_u *SeriesProviderUpdate) SetNillableIsUninstalled(v *bool) *SeriesProviderUpdate {
	if v != nil {
		_u.SetIsUninstalled(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SeriesProviderUpdate) SetStatus(v string) *SeriesProviderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SeriesProviderUpdate) SetNillableStatus(v *string) *SeriesProviderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetChapters sets the "chapters" field.
func (_u *SeriesProviderUpdate) SetChapters(v []types.Chapter) *SeriesProviderUpdate {
	_u.mutation.SetChapters(v)
	return _u
}

// AppendChapters appends value to the "chapters" field.
func (_u *SeriesProviderUpdate) AppendChapters(v []types.Chapter) *SeriesProviderUpdate {
	_u.mutation.AppendChapters(v)
	return _u
}

// ClearChapters clears the value of the "chapters" field.
func (_u *SeriesProviderUpdate) ClearChapters() *SeriesProviderUpdate {
	_u.mutation.ClearChapters()
	return _u
}

// SetSeries sets the "series" edge to the Series entity.
func (_u *SeriesProviderUpdate) SetSeries(v *Series) *SeriesProviderUpdate {
	return _u.SetSeriesID(v.ID)
}

// Mutation returns the SeriesProviderMutation object of the builder.
func (_u *SeriesProviderUpdate) Mutation() *SeriesProviderMutation {
	return _u.mutation
}

// ClearSeries clears the "series" edge to the Series entity.
func (_u *SeriesProviderUpdate) ClearSeries() *SeriesProviderUpdate {
	_u.mutation.ClearSeries()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SeriesProviderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SeriesProviderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SeriesProviderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SeriesProviderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SeriesProviderUpdate) check() error {
	if _u.mutation.SeriesCleared() && len(_u.mutation.SeriesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SeriesProvider.series"`)
	}
	return nil
}

func (_u *SeriesProviderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(seriesprovider.Table, seriesprovider.Columns, sqlgraph.NewFieldSpec(seriesprovider.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SuwayomiID(); ok {
		_spec.SetField(seriesprovider.FieldSuwayomiID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSuwayomiID(); ok {
		_spec.AddField(seriesprovider.FieldSuwayomiID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(seriesprovider.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scanlator(); ok {
		_spec.SetField(seriesprovider.FieldScanlator, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(seriesprovider.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(seriesprovider.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(seriesprovider.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(seriesprovider.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.ThumbnailURL(); ok {
		_spec.SetField(seriesprovider.FieldThumbnailURL, field.TypeString, value)
	}
	if _u.mutation.ThumbnailURLCleared() {
		_spec.ClearField(seriesprovider.FieldThumbnailURL, field.TypeString)
	}
	if value, ok := _u.mutation.Artist(); ok {
		_spec.SetField(seriesprovider.FieldArtist, field.TypeString, value)
	}
	if _u.mutation.ArtistCleared() {
		_spec.ClearField(seriesprovider.FieldArtist, field.TypeString)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(seriesprovider.FieldAuthor, field.TypeString, value)
	}
	if _u.mutation.AuthorCleared() {
		_spec.ClearField(seriesprovider.FieldAuthor, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(seriesprovider.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(seriesprovider.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Genre(); ok {
		_spec.SetField(seriesprovider.FieldGenre, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGenre(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, seriesprovider.FieldGenre, value)
		})
	}
	if _u.mutation.GenreCleared() {
		_spec.ClearField(seriesprovider.FieldGenre, field.TypeJSON)
	}
	if value, ok := _u.mutation.FetchDate(); ok {
		_spec.SetField(seriesprovider.FieldFetchDate, field.TypeTime, value)
	}
	if _u.mutation.FetchDateCleared() {
		_spec.ClearField(seriesprovider.FieldFetchDate, field.TypeTime)
	}
	if value, ok := _u.mutation.ChapterCount(); ok {
		_spec.SetField(seriesprovider.FieldChapterCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChapterCount(); ok {
		_spec.AddField(seriesprovider.FieldChapterCount, field.TypeInt64, value)
	}
	if _u.mutation.ChapterCountCleared() {
		_spec.ClearField(seriesprovider.FieldChapterCount, field.TypeInt64)
	}
	if value, ok := _u.mutation.ContinueAfterChapter(); ok {
		_spec.SetField(seriesprovider.FieldContinueAfterChapter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedContinueAfterChapter(); ok {
		_spec.AddField(seriesprovider.FieldContinueAfterChapter, field.TypeFloat64, value)
	}
	if _u.mutation.ContinueAfterChapterCleared() {
		_spec.ClearField(seriesprovider.FieldContinueAfterChapter, field.TypeFloat64)
	}
	if value, ok := _u.mutation.IsTitle(); ok {
		_spec.SetField(seriesprovider.FieldIsTitle, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsCover(); ok {
		_spec.SetField(seriesprovider.FieldIsCover, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsUnknown(); ok {
		_spec.SetField(seriesprovider.FieldIsUnknown, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Importance(); ok {
		_spec.SetField(seriesprovider.FieldImportance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedImportance(); ok {
		_spec.AddField(seriesprovider.FieldImportance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsDisabled(); ok {
		_spec.SetField(seriesprovider.FieldIsDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsUninstalled(); ok {
		_spec.SetField(seriesprovider.FieldIsUninstalled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(seriesprovider.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Chapters(); ok {
		_spec.SetField(seriesprovider.FieldChapters, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedChapters(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, seriesprovider.FieldChapters, value)
		})
	}
	if _u.mutation.ChaptersCleared() {
		_spec.ClearField(seriesprovider.FieldChapters, field.TypeJSON)
	}
	if _u.mutation.SeriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   seriesprovider.SeriesTable,
			Columns: []string{seriesprovider.SeriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   seriesprovider.SeriesTable,
			Columns: []string{seriesprovider.SeriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{seriesprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SeriesProviderUpdateOne is the builder for updating a single SeriesProvider entity.
type SeriesProviderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SeriesProviderMutation
}

// SetSeriesID sets the "series_id" field.
func (_u *SeriesProviderUpdateOne) SetSeriesID(v uuid.UUID) *SeriesProviderUpdateOne {
	_u.mutation.SetSeriesID(v)
	return _u
}

// SetNillableSeriesID sets the "series_id" field if the given value is not nil.
func (_u *SeriesProviderUpdateOne) SetNillableSeriesID(v *uuid.UUID) *SeriesProviderUpdateOne {
	if v != nil {
		_u.SetSeriesID(*v)
	}
	return _u
}

// SetSuwayomiID sets the "suwayomi_id" field.
func (_u *SeriesProviderUpdateOne) SetSuwayomiID(v int) *SeriesProviderUpdateOne {
	_u.mutation.ResetSuwayomiID()
	_u.mutation.SetSuwayomiID(v)
	return _u
}

// SetNillableSuwayomiID sets the "suwayomi_id" field if the given value is not nil.
func (_u *SeriesProviderUpdateOne) SetNillableSuwayomiID(v *int) *SeriesProviderUpdateOne {
	if v != nil {
		_u.SetSuwayomiID(*v)
	}
	return _u
}

// AddSuwayomiID adds value to the "suwayomi_id" field.
func (_u *SeriesProviderUpdateOne) AddSuwayomiID(v int) *SeriesProviderUpdateOne {
	_u.mutation.AddSuwayomiID(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *SeriesProviderUpdateOne) SetProvider(v string) *SeriesProviderUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *SeriesProviderUpdateOne) SetNillableProvider(v *string) *SeriesProviderUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetScanlator sets the "scanlator" field.
func (_u *SeriesProviderUpdateOne) SetScanlator(v string) *SeriesProviderUpdateOne {
	_u.mutation.SetScanlator(v)
	return _u
}

// SetNillableScanlator sets the "scanlator" field if the given value is not nil.
func (_u *SeriesProviderUpdateOne) SetNillableScanlator(v *string) *SeriesProviderUpdateOne {
	if v != nil {
		_u.SetScanlator(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *SeriesProviderUpdateOne) SetURL(v string) *SeriesProviderUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *SeriesProviderUpdateOne) SetNillableURL(v *string) *SeriesProviderUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *SeriesProviderUpdateOne) ClearURL() *SeriesProviderUpdateOne {
	_u.mutation.ClearURL()
	return _u
}

// SetTitle sets the "title" field.
func (_u *SeriesProviderUpdateOne) SetTitle(v string) *SeriesProviderUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *SeriesProviderUpdateOne) SetNillableTitle(v *string) *SeriesProviderUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *SeriesProviderUpdateOne) SetLanguage(v string) *SeriesProviderUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *SeriesProviderUpdateOne) SetNillableLanguage(v *string) *SeriesProviderUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (_u *SeriesProviderUpdateOne) SetThumbnailURL(v string) *SeriesProviderUpdateOne {
	_u.mutation.SetThumbnailURL(v)
	return _u
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (_u *SeriesProviderUpdateOne) SetNillableThumbnailURL(v *string) *SeriesProviderUpdateOne {
	if v != nil {
		_u.SetThumbnailURL(*v)
	}
	return _u
}

// ClearThumbnailURL clears the value of the "thumbnail_url" field.
func (_u *SeriesProviderUpdateOne) ClearThumbnailURL() *SeriesProviderUpdateOne {
	_u.mutation.ClearThumbnailURL()
	return _u
}

// SetArtist sets the "artist" field.
func (_u *SeriesProviderUpdateOne) SetArtist(v string) *SeriesProviderUpdateOne {
	_u.mutation.SetArtist(v)
	return _u
}

// SetNillableArtist sets the "artist" field if the given value is not nil.
func (_u *SeriesProviderUpdateOne) SetNillableArtist(v *string) *SeriesProviderUpdateOne {
	if v != nil {
		_u.SetArtist(*v)
	}
	return _u
}

// ClearArtist clears the value of the "artist" field.
func (_u *SeriesProviderUpdateOne) ClearArtist() *SeriesProviderUpdateOne {
	_u.mutation.ClearArtist()
	return _u
}

// SetAuthor sets the "author" field.
func (_u *SeriesProviderUpdateOne) SetAuthor(v string) *SeriesProviderUpdateOne {
	_u.mutation.SetAuthor(v)
	return _u
}

// SetNillableAuthor sets the "author" field if the given value is not nil.
func (_u *SeriesProviderUpdateOne) SetNillableAuthor(v *string) *SeriesProviderUpdateOne {
	if v != nil {
		_u.SetAuthor(*v)
	}
	return _u
}

// ClearAuthor clears the value of the "author" field.
func (_u *SeriesProviderUpdateOne) ClearAuthor() *SeriesProviderUpdateOne {
	_u.mutation.ClearAuthor()
	return _u
}

// SetDescription sets the "description" field.
func (_u *SeriesProviderUpdateOne) SetDescription(v string) *SeriesProviderUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *SeriesProviderUpdateOne) SetNillableDescription(v *string) *SeriesProviderUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *SeriesProviderUpdateOne) ClearDescription() *SeriesProviderUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetGenre sets the "genre" field.
func (_u *SeriesProviderUpdateOne) SetGenre(v []string) *SeriesProviderUpdateOne {
	_u.mutation.SetGenre(v)
	return _u
}

// AppendGenre appends value to the "genre" field.
func (_u *SeriesProviderUpdateOne) AppendGenre(v []string) *SeriesProviderUpdateOne {
	_u.mutation.AppendGenre(v)
	return _u
}

// ClearGenre clears the value of the "genre" field.
func (_u *SeriesProviderUpdateOne) ClearGenre() *SeriesProviderUpdateOne {
	_u.mutation.ClearGenre()
	return _u
}

// SetFetchDate sets the "fetch_date" field.
func (_u *SeriesProviderUpdateOne) SetFetchDate(v time.Time) *SeriesProviderUpdateOne {
	_u.mutation.SetFetchDate(v)
	return _u
}

// SetNillableFetchDate sets the "fetch_date" field if the given value is not nil.
func (_u *SeriesProviderUpdateOne) SetNillableFetchDate(v *time.Time) *SeriesProviderUpdateOne {
	if v != nil {
		_u.SetFetchDate(*v)
	}
	return _u
}

// ClearFetchDate clears the value of the "fetch_date" field.
func (_u *SeriesProviderUpdateOne) ClearFetchDate() *SeriesProviderUpdateOne {
	_u.mutation.ClearFetchDate()
	return _u
}

// SetChapterCount sets the "chapter_count" field.
func (_u *SeriesProviderUpdateOne) SetChapterCount(v int64) *SeriesProviderUpdateOne {
	_u.mutation.ResetChapterCount()
	_u.mutation.SetChapterCount(v)
	return _u
}

// SetNillableChapterCount sets the "chapter_count" field if the given value is not nil.
func (_u *SeriesProviderUpdateOne) SetNillableChapterCount(v *int64) *SeriesProviderUpdateOne {
	if v != nil {
		_u.SetChapterCount(*v)
	}
	return _u
}

// AddChapterCount adds value to the "chapter_count" field.
func (_u *SeriesProviderUpdateOne) AddChapterCount(v int64) *SeriesProviderUpdateOne {
	_u.mutation.AddChapterCount(v)
	return _u
}

// ClearChapterCount clears the value of the "chapter_count" field.
func (_u *SeriesProviderUpdateOne) ClearChapterCount() *SeriesProviderUpdateOne {
	_u.mutation.ClearChapterCount()
	return _u
}

// SetContinueAfterChapter sets the "continue_after_chapter" field.
func (_u *SeriesProviderUpdateOne) SetContinueAfterChapter(v float64) *SeriesProviderUpdateOne {
	_u.mutation.ResetContinueAfterChapter()
	_u.mutation.SetContinueAfterChapter(v)
	return _u
}

// SetNillableContinueAfterChapter sets the "continue_after_chapter" field if the given value is not nil.
func (_u *SeriesProviderUpdateOne) SetNillableContinueAfterChapter(v *float64) *SeriesProviderUpdateOne {
	if v != nil {
		_u.SetContinueAfterChapter(*v)
	}
	return _u
}

// AddContinueAfterChapter adds value to the "continue_after_chapter" field.
func (_u *SeriesProviderUpdateOne) AddContinueAfterChapter(v float64) *SeriesProviderUpdateOne {
	_u.mutation.AddContinueAfterChapter(v)
	return _u
}

// ClearContinueAfterChapter clears the value of the "continue_after_chapter" field.
func (_u *SeriesProviderUpdateOne) ClearContinueAfterChapter() *SeriesProviderUpdateOne {
	_u.mutation.ClearContinueAfterChapter()
	return _u
}

// SetIsTitle sets the "is_title" field.
func (_u *SeriesProviderUpdateOne) SetIsTitle(v bool) *SeriesProviderUpdateOne {
	_u.mutation.SetIsTitle(v)
	return _u
}

// SetNillableIsTitle sets the "is_title" field if the given value is not nil.
func (_u *SeriesProviderUpdateOne) SetNillableIsTitle(v *bool) *SeriesProviderUpdateOne {
	if v != nil {
		_u.SetIsTitle(*v)
	}
	return _u
}

// SetIsCover sets the "is_cover" field.
func (_u *SeriesProviderUpdateOne) SetIsCover(v bool) *SeriesProviderUpdateOne {
	_u.mutation.SetIsCover(v)
	return _u
}

// SetNillableIsCover sets the "is_cover" field if the given value is not nil.
func (_u *SeriesProviderUpdateOne) SetNillableIsCover(v *bool) *SeriesProviderUpdateOne {
	if v != nil {
		_u.SetIsCover(*v)
	}
	return _u
}

// SetIsUnknown sets the "is_unknown" field.
func (_u *SeriesProviderUpdateOne) SetIsUnknown(v bool) *SeriesProviderUpdateOne {
	_u.mutation.SetIsUnknown(v)
	return _u
}

// SetNillableIsUnknown sets the "is_unknown" field if the given value is not nil.
func (_u *SeriesProviderUpdateOne) SetNillableIsUnknown(v *bool) *SeriesProviderUpdateOne {
	if v != nil {
		_u.SetIsUnknown(*v)
	}
	return _u
}

// SetImportance sets the "importance" field.
func (_u *SeriesProviderUpdateOne) SetImportance(v int) *SeriesProviderUpdateOne {
	_u.mutation.ResetImportance()
	_u.mutation.SetImportance(v)
	return _u
}

// SetNillableImportance sets the "importance" field if the given value is not nil.
func (_u *SeriesProviderUpdateOne) SetNillableImportance(v *int) *SeriesProviderUpdateOne {
	if v != nil {
		_u.SetImportance(*v)
	}
	return _u
}

// AddImportance adds value to the "importance" field.
func (_u *SeriesProviderUpdateOne) AddImportance(v int) *SeriesProviderUpdateOne {
	_u.mutation.AddImportance(v)
	return _u
}

// SetIsDisabled sets the "is_disabled" field.
func (_u *SeriesProviderUpdateOne) SetIsDisabled(v bool) *SeriesProviderUpdateOne {
	_u.mutation.SetIsDisabled(v)
	return _u
}

// SetNillableIsDisabled sets the "is_disabled" field if the given value is not nil.
func (_u *SeriesProviderUpdateOne) SetNillableIsDisabled(v *bool) *SeriesProviderUpdateOne {
	if v != nil {
		_u.SetIsDisabled(*v)
	}
	return _u
}

// SetIsUninstalled sets the "is_uninstalled" field.
func (_u *SeriesProviderUpdateOne) SetIsUninstalled(v bool) *SeriesProviderUpdateOne {
	_u.mutation.SetIsUninstalled(v)
	return _u
}

// SetNillableIsUninstalled sets the "is_uninstalled" field if the given value is not nil.
func (_u *SeriesProviderUpdateOne) SetNillableIsUninstalled(v *bool) *SeriesProviderUpdateOne {
	if v != nil {
		_u.SetIsUninstalled(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SeriesProviderUpdateOne) SetStatus(v string) *SeriesProviderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SeriesProviderUpdateOne) SetNillableStatus(v *string) *SeriesProviderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetChapters sets the "chapters" field.
func (_u *SeriesProviderUpdateOne) SetChapters(v []types.Chapter) *SeriesProviderUpdateOne {
	_u.mutation.SetChapters(v)
	return _u
}

// AppendChapters appends value to the "chapters" field.
func (_u *SeriesProviderUpdateOne) AppendChapters(v []types.Chapter) *SeriesProviderUpdateOne {
	_u.mutation.AppendChapters(v)
	return _u
}

// ClearChapters clears the value of the "chapters" field.
func (_u *SeriesProviderUpdateOne) ClearChapters() *SeriesProviderUpdateOne {
	_u.mutation.ClearChapters()
	return _u
}

// SetSeries sets the "series" edge to the Series entity.
func (_u *SeriesProviderUpdateOne) SetSeries(v *Series) *SeriesProviderUpdateOne {
	return _u.SetSeriesID(v.ID)
}

// Mutation returns the SeriesProviderMutation object of the builder.
func (_u *SeriesProviderUpdateOne) Mutation() *SeriesProviderMutation {
	return _u.mutation
}

// ClearSeries clears the "series" edge to the Series entity.
func (_u *SeriesProviderUpdateOne) ClearSeries() *SeriesProviderUpdateOne {
	_u.mutation.ClearSeries()
	return _u
}

// Where appends a list predicates to the SeriesProviderUpdate builder.
func (_u *SeriesProviderUpdateOne) Where(ps ...predicate.SeriesProvider) *SeriesProviderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SeriesProviderUpdateOne) Select(field string, fields ...string) *SeriesProviderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SeriesProvider entity.
func (_u *SeriesProviderUpdateOne) Save(ctx context.Context) (*SeriesProvider, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SeriesProviderUpdateOne) SaveX(ctx context.Context) *SeriesProvider {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SeriesProviderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SeriesProviderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SeriesProviderUpdateOne) check() error {
	if _u.mutation.SeriesCleared() && len(_u.mutation.SeriesIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SeriesProvider.series"`)
	}
	return nil
}

func (_u *SeriesProviderUpdateOne) sqlSave(ctx context.Context) (_node *SeriesProvider, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(seriesprovider.Table, seriesprovider.Columns, sqlgraph.NewFieldSpec(seriesprovider.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SeriesProvider.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, seriesprovider.FieldID)
		for _, f := range fields {
			if !seriesprovider.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != seriesprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SuwayomiID(); ok {
		_spec.SetField(seriesprovider.FieldSuwayomiID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSuwayomiID(); ok {
		_spec.AddField(seriesprovider.FieldSuwayomiID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(seriesprovider.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scanlator(); ok {
		_spec.SetField(seriesprovider.FieldScanlator, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(seriesprovider.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(seriesprovider.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(seriesprovider.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(seriesprovider.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.ThumbnailURL(); ok {
		_spec.SetField(seriesprovider.FieldThumbnailURL, field.TypeString, value)
	}
	if _u.mutation.ThumbnailURLCleared() {
		_spec.ClearField(seriesprovider.FieldThumbnailURL, field.TypeString)
	}
	if value, ok := _u.mutation.Artist(); ok {
		_spec.SetField(seriesprovider.FieldArtist, field.TypeString, value)
	}
	if _u.mutation.ArtistCleared() {
		_spec.ClearField(seriesprovider.FieldArtist, field.TypeString)
	}
	if value, ok := _u.mutation.Author(); ok {
		_spec.SetField(seriesprovider.FieldAuthor, field.TypeString, value)
	}
	if _u.mutation.AuthorCleared() {
		_spec.ClearField(seriesprovider.FieldAuthor, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(seriesprovider.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(seriesprovider.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Genre(); ok {
		_spec.SetField(seriesprovider.FieldGenre, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGenre(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, seriesprovider.FieldGenre, value)
		})
	}
	if _u.mutation.GenreCleared() {
		_spec.ClearField(seriesprovider.FieldGenre, field.TypeJSON)
	}
	if value, ok := _u.mutation.FetchDate(); ok {
		_spec.SetField(seriesprovider.FieldFetchDate, field.TypeTime, value)
	}
	if _u.mutation.FetchDateCleared() {
		_spec.ClearField(seriesprovider.FieldFetchDate, field.TypeTime)
	}
	if value, ok := _u.mutation.ChapterCount(); ok {
		_spec.SetField(seriesprovider.FieldChapterCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChapterCount(); ok {
		_spec.AddField(seriesprovider.FieldChapterCount, field.TypeInt64, value)
	}
	if _u.mutation.ChapterCountCleared() {
		_spec.ClearField(seriesprovider.FieldChapterCount, field.TypeInt64)
	}
	if value, ok := _u.mutation.ContinueAfterChapter(); ok {
		_spec.SetField(seriesprovider.FieldContinueAfterChapter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedContinueAfterChapter(); ok {
		_spec.AddField(seriesprovider.FieldContinueAfterChapter, field.TypeFloat64, value)
	}
	if _u.mutation.ContinueAfterChapterCleared() {
		_spec.ClearField(seriesprovider.FieldContinueAfterChapter, field.TypeFloat64)
	}
	if value, ok := _u.mutation.IsTitle(); ok {
		_spec.SetField(seriesprovider.FieldIsTitle, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsCover(); ok {
		_spec.SetField(seriesprovider.FieldIsCover, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsUnknown(); ok {
		_spec.SetField(seriesprovider.FieldIsUnknown, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Importance(); ok {
		_spec.SetField(seriesprovider.FieldImportance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedImportance(); ok {
		_spec.AddField(seriesprovider.FieldImportance, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsDisabled(); ok {
		_spec.SetField(seriesprovider.FieldIsDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsUninstalled(); ok {
		_spec.SetField(seriesprovider.FieldIsUninstalled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(seriesprovider.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Chapters(); ok {
		_spec.SetField(seriesprovider.FieldChapters, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedChapters(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, seriesprovider.FieldChapters, value)
		})
	}
	if _u.mutation.ChaptersCleared() {
		_spec.ClearField(seriesprovider.FieldChapters, field.TypeJSON)
	}
	if _u.mutation.SeriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   seriesprovider.SeriesTable,
			Columns: []string{seriesprovider.SeriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   seriesprovider.SeriesTable,
			Columns: []string{seriesprovider.SeriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(series.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SeriesProvider{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{seriesprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
