// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/technobecet/kaizoku-go/internal/ent/series"
	"github.com/technobecet/kaizoku-go/internal/ent/seriesprovider"
	"github.com/technobecet/kaizoku-go/internal/types"
)

// SeriesProvider is the model entity for the SeriesProvider schema.
type SeriesProvider struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// SeriesID holds the value of the "series_id" field.
	SeriesID uuid.UUID `json:"series_id,omitempty"`
	// SuwayomiID holds the value of the "suwayomi_id" field.
	SuwayomiID int `json:"suwayomi_id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// Scanlator holds the value of the "scanlator" field.
	Scanlator string `json:"scanlator,omitempty"`
	// URL holds the value of the "url" field.
	URL *string `json:"url,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Language holds the value of the "language" field.
	Language string `json:"language,omitempty"`
	// ThumbnailURL holds the value of the "thumbnail_url" field.
	ThumbnailURL *string `json:"thumbnail_url,omitempty"`
	// Artist holds the value of the "artist" field.
	Artist *string `json:"artist,omitempty"`
	// Author holds the value of the "author" field.
	Author *string `json:"author,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// Genre holds the value of the "genre" field.
	Genre []string `json:"genre,omitempty"`
	// FetchDate holds the value of the "fetch_date" field.
	FetchDate *time.Time `json:"fetch_date,omitempty"`
	// ChapterCount holds the value of the "chapter_count" field.
	ChapterCount *int64 `json:"chapter_count,omitempty"`
	// ContinueAfterChapter holds the value of the "continue_after_chapter" field.
	ContinueAfterChapter *float64 `json:"continue_after_chapter,omitempty"`
	// IsTitle holds the value of the "is_title" field.
	IsTitle bool `json:"is_title,omitempty"`
	// IsCover holds the value of the "is_cover" field.
	IsCover bool `json:"is_cover,omitempty"`
	// IsUnknown holds the value of the "is_unknown" field.
	IsUnknown bool `json:"is_unknown,omitempty"`
	// Importance holds the value of the "importance" field.
	Importance int `json:"importance,omitempty"`
	// IsDisabled holds the value of the "is_disabled" field.
	IsDisabled bool `json:"is_disabled,omitempty"`
	// IsUninstalled holds the value of the "is_uninstalled" field.
	IsUninstalled bool `json:"is_uninstalled,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Chapters holds the value of the "chapters" field.
	Chapters []types.Chapter `json:"chapters,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SeriesProviderQuery when eager-loading is set.
	Edges        SeriesProviderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SeriesProviderEdges holds the relations/edges for other nodes in the graph.
type SeriesProviderEdges struct {
	// Series holds the value of the series edge.
	Series *Series `json:"series,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SeriesOrErr returns the Series value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SeriesProviderEdges) SeriesOrErr() (*Series, error) {
	if e.Series != nil {
		return e.Series, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: series.Label}
	}
	return nil, &NotLoadedError{edge: "series"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SeriesProvider) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case seriesprovider.FieldGenre, seriesprovider.FieldChapters:
			values[i] = new([]byte)
		case seriesprovider.FieldIsTitle, seriesprovider.FieldIsCover, seriesprovider.FieldIsUnknown, seriesprovider.FieldIsDisabled, seriesprovider.FieldIsUninstalled:
			values[i] = new(sql.NullBool)
		case seriesprovider.FieldContinueAfterChapter:
			values[i] = new(sql.NullFloat64)
		case seriesprovider.FieldSuwayomiID, seriesprovider.FieldChapterCount, seriesprovider.FieldImportance:
			values[i] = new(sql.NullInt64)
		case seriesprovider.FieldProvider, seriesprovider.FieldScanlator, seriesprovider.FieldURL, seriesprovider.FieldTitle, seriesprovider.FieldLanguage, seriesprovider.FieldThumbnailURL, seriesprovider.FieldArtist, seriesprovider.FieldAuthor, seriesprovider.FieldDescription, seriesprovider.FieldStatus:
			values[i] = new(sql.NullString)
		case seriesprovider.FieldFetchDate:
			values[i] = new(sql.NullTime)
		case seriesprovider.FieldID, seriesprovider.FieldSeriesID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SeriesProvider fields.
func (_m *SeriesProvider) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case seriesprovider.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case seriesprovider.FieldSeriesID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field series_id", values[i])
			} else if value != nil {
				_m.SeriesID = *value
			}
		case seriesprovider.FieldSuwayomiID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field suwayomi_id", values[i])
			} else if value.Valid {
				_m.SuwayomiID = int(value.Int64)
			}
		case seriesprovider.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case seriesprovider.FieldScanlator:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scanlator", values[i])
			} else if value.Valid {
				_m.Scanlator = value.String
			}
		case seriesprovider.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = new(string)
				*_m.URL = value.String
			}
		case seriesprovider.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case seriesprovider.FieldLanguage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language", values[i])
			} else if value.Valid {
				_m.Language = value.String
			}
		case seriesprovider.FieldThumbnailURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field thumbnail_url", values[i])
			} else if value.Valid {
				_m.ThumbnailURL = new(string)
				*_m.ThumbnailURL = value.String
			}
		case seriesprovider.FieldArtist:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field artist", values[i])
			} else if value.Valid {
				_m.Artist = new(string)
				*_m.Artist = value.String
			}
		case seriesprovider.FieldAuthor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field author", values[i])
			} else if value.Valid {
				_m.Author = new(string)
				*_m.Author = value.String
			}
		case seriesprovider.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case seriesprovider.FieldGenre:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field genre", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Genre); err != nil {
					return fmt.Errorf("unmarshal field genre: %w", err)
				}
			}
		case seriesprovider.FieldFetchDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field fetch_date", values[i])
			} else if value.Valid {
				_m.FetchDate = new(time.Time)
				*_m.FetchDate = value.Time
			}
		case seriesprovider.FieldChapterCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chapter_count", values[i])
			} else if value.Valid {
				_m.ChapterCount = new(int64)
				*_m.ChapterCount = value.Int64
			}
		case seriesprovider.FieldContinueAfterChapter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field continue_after_chapter", values[i])
			} else if value.Valid {
				_m.ContinueAfterChapter = new(float64)
				*_m.ContinueAfterChapter = value.Float64
			}
		case seriesprovider.FieldIsTitle:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_title", values[i])
			} else if value.Valid {
				_m.IsTitle = value.Bool
			}
		case seriesprovider.FieldIsCover:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_cover", values[i])
			} else if value.Valid {
				_m.IsCover = value.Bool
			}
		case seriesprovider.FieldIsUnknown:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_unknown", values[i])
			} else if value.Valid {
				_m.IsUnknown = value.Bool
			}
		case seriesprovider.FieldImportance:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field importance", values[i])
			} else if value.Valid {
				_m.Importance = int(value.Int64)
			}
		case seriesprovider.FieldIsDisabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_disabled", values[i])
			} else if value.Valid {
				_m.IsDisabled = value.Bool
			}
		case seriesprovider.FieldIsUninstalled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_uninstalled", values[i])
			} else if value.Valid {
				_m.IsUninstalled = value.Bool
			}
		case seriesprovider.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case seriesprovider.FieldChapters:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field chapters", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Chapters); err != nil {
					return fmt.Errorf("unmarshal field chapters: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SeriesProvider.
// This includes values selected through modifiers, order, etc.
func (_m *SeriesProvider) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySeries queries the "series" edge of the SeriesProvider entity.
func (_m *SeriesProvider) QuerySeries() *SeriesQuery {
	return NewSeriesProviderClient(_m.config).QuerySeries(_m)
}

// Update returns a builder for updating this SeriesProvider.
// Note that you need to call SeriesProvider.Unwrap() before calling this method if this SeriesProvider
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SeriesProvider) Update() *SeriesProviderUpdateOne {
	return NewSeriesProviderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SeriesProvider entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SeriesProvider) Unwrap() *SeriesProvider {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SeriesProvider is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SeriesProvider) String() string {
	var builder strings.Builder
	builder.WriteString("SeriesProvider(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("series_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SeriesID))
	builder.WriteString(", ")
	builder.WriteString("suwayomi_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SuwayomiID))
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("scanlator=")
	builder.WriteString(_m.Scanlator)
	builder.WriteString(", ")
	if v := _m.URL; v != nil {
		builder.WriteString("url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("language=")
	builder.WriteString(_m.Language)
	builder.WriteString(", ")
	if v := _m.ThumbnailURL; v != nil {
		builder.WriteString("thumbnail_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Artist; v != nil {
		builder.WriteString("artist=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Author; v != nil {
		builder.WriteString("author=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("genre=")
	builder.WriteString(fmt.Sprintf("%v", _m.Genre))
	builder.WriteString(", ")
	if v := _m.FetchDate; v != nil {
		builder.WriteString("fetch_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ChapterCount; v != nil {
		builder.WriteString("chapter_count=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ContinueAfterChapter; v != nil {
		builder.WriteString("continue_after_chapter=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("is_title=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsTitle))
	builder.WriteString(", ")
	builder.WriteString("is_cover=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsCover))
	builder.WriteString(", ")
	builder.WriteString("is_unknown=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsUnknown))
	builder.WriteString(", ")
	builder.WriteString("importance=")
	builder.WriteString(fmt.Sprintf("%v", _m.Importance))
	builder.WriteString(", ")
	builder.WriteString("is_disabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDisabled))
	builder.WriteString(", ")
	builder.WriteString("is_uninstalled=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsUninstalled))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("chapters=")
	builder.WriteString(fmt.Sprintf("%v", _m.Chapters))
	builder.WriteByte(')')
	return builder.String()
}

// SeriesProviders is a parsable slice of SeriesProvider.
type SeriesProviders []*SeriesProvider
