// Code generated by ent, DO NOT EDIT.

package seriesprovider

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the seriesprovider type in the database.
	Label = "series_provider"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSeriesID holds the string denoting the series_id field in the database.
	FieldSeriesID = "series_id"
	// FieldSuwayomiID holds the string denoting the suwayomi_id field in the database.
	FieldSuwayomiID = "suwayomi_id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldScanlator holds the string denoting the scanlator field in the database.
	FieldScanlator = "scanlator"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldLanguage holds the string denoting the language field in the database.
	FieldLanguage = "language"
	// FieldThumbnailURL holds the string denoting the thumbnail_url field in the database.
	FieldThumbnailURL = "thumbnail_url"
	// FieldArtist holds the string denoting the artist field in the database.
	FieldArtist = "artist"
	// FieldAuthor holds the string denoting the author field in the database.
	FieldAuthor = "author"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldGenre holds the string denoting the genre field in the database.
	FieldGenre = "genre"
	// FieldFetchDate holds the string denoting the fetch_date field in the database.
	FieldFetchDate = "fetch_date"
	// FieldChapterCount holds the string denoting the chapter_count field in the database.
	FieldChapterCount = "chapter_count"
	// FieldContinueAfterChapter holds the string denoting the continue_after_chapter field in the database.
	FieldContinueAfterChapter = "continue_after_chapter"
	// FieldIsTitle holds the string denoting the is_title field in the database.
	FieldIsTitle = "is_title"
	// FieldIsCover holds the string denoting the is_cover field in the database.
	FieldIsCover = "is_cover"
	// FieldIsUnknown holds the string denoting the is_unknown field in the database.
	FieldIsUnknown = "is_unknown"
	// FieldImportance holds the string denoting the importance field in the database.
	FieldImportance = "importance"
	// FieldIsDisabled holds the string denoting the is_disabled field in the database.
	FieldIsDisabled = "is_disabled"
	// FieldIsUninstalled holds the string denoting the is_uninstalled field in the database.
	FieldIsUninstalled = "is_uninstalled"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldChapters holds the string denoting the chapters field in the database.
	FieldChapters = "chapters"
	// EdgeSeries holds the string denoting the series edge name in mutations.
	EdgeSeries = "series"
	// Table holds the table name of the seriesprovider in the database.
	Table = "series_providers"
	// SeriesTable is the table that holds the series relation/edge.
	SeriesTable = "series_providers"
	// SeriesInverseTable is the table name for the Series entity.
	// It exists in this package in order to avoid circular dependency with the "series" package.
	SeriesInverseTable = "series"
	// SeriesColumn is the table column denoting the series relation/edge.
	SeriesColumn = "series_id"
)

// Columns holds all SQL columns for seriesprovider fields.
var Columns = []string{
	FieldID,
	FieldSeriesID,
	FieldSuwayomiID,
	FieldProvider,
	FieldScanlator,
	FieldURL,
	FieldTitle,
	FieldLanguage,
	FieldThumbnailURL,
	FieldArtist,
	FieldAuthor,
	FieldDescription,
	FieldGenre,
	FieldFetchDate,
	FieldChapterCount,
	FieldContinueAfterChapter,
	FieldIsTitle,
	FieldIsCover,
	FieldIsUnknown,
	FieldImportance,
	FieldIsDisabled,
	FieldIsUninstalled,
	FieldStatus,
	FieldChapters,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSuwayomiID holds the default value on creation for the "suwayomi_id" field.
	DefaultSuwayomiID int
	// DefaultScanlator holds the default value on creation for the "scanlator" field.
	DefaultScanlator string
	// DefaultTitle holds the default value on creation for the "title" field.
	DefaultTitle string
	// DefaultLanguage holds the default value on creation for the "language" field.
	DefaultLanguage string
	// DefaultIsTitle holds the default value on creation for the "is_title" field.
	DefaultIsTitle bool
	// DefaultIsCover holds the default value on creation for the "is_cover" field.
	DefaultIsCover bool
	// DefaultIsUnknown holds the default value on creation for the "is_unknown" field.
	DefaultIsUnknown bool
	// DefaultImportance holds the default value on creation for the "importance" field.
	DefaultImportance int
	// DefaultIsDisabled holds the default value on creation for the "is_disabled" field.
	DefaultIsDisabled bool
	// DefaultIsUninstalled holds the default value on creation for the "is_uninstalled" field.
	DefaultIsUninstalled bool
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the SeriesProvider queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySeriesID orders the results by the series_id field.
func BySeriesID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeriesID, opts...).ToFunc()
}

// BySuwayomiID orders the results by the suwayomi_id field.
func BySuwayomiID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuwayomiID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByScanlator orders the results by the scanlator field.
func ByScanlator(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScanlator, opts...).ToFunc()
}

// ByURL orders the results by the url field.
func ByURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURL, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByLanguage orders the results by the language field.
func ByLanguage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLanguage, opts...).ToFunc()
}

// ByThumbnailURL orders the results by the thumbnail_url field.
func ByThumbnailURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThumbnailURL, opts...).ToFunc()
}

// ByArtist orders the results by the artist field.
func ByArtist(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArtist, opts...).ToFunc()
}

// ByAuthor orders the results by the author field.
func ByAuthor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthor, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByFetchDate orders the results by the fetch_date field.
func ByFetchDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFetchDate, opts...).ToFunc()
}

// ByChapterCount orders the results by the chapter_count field.
func ByChapterCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChapterCount, opts...).ToFunc()
}

// ByContinueAfterChapter orders the results by the continue_after_chapter field.
func ByContinueAfterChapter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContinueAfterChapter, opts...).ToFunc()
}

// ByIsTitle orders the results by the is_title field.
func ByIsTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsTitle, opts...).ToFunc()
}

// ByIsCover orders the results by the is_cover field.
func ByIsCover(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsCover, opts...).ToFunc()
}

// ByIsUnknown orders the results by the is_unknown field.
func ByIsUnknown(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsUnknown, opts...).ToFunc()
}

// ByImportance orders the results by the importance field.
func ByImportance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImportance, opts...).ToFunc()
}

// ByIsDisabled orders the results by the is_disabled field.
func ByIsDisabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsDisabled, opts...).ToFunc()
}

// ByIsUninstalled orders the results by the is_uninstalled field.
func ByIsUninstalled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsUninstalled, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySeriesField orders the results by series field.
func BySeriesField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSeriesStep(), sql.OrderByField(field, opts...))
	}
}
func newSeriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SeriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SeriesTable, SeriesColumn),
	)
}
