// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DownloadQueueItemsColumns holds the columns for the "download_queue_items" table.
	DownloadQueueItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "group_key", Type: field.TypeString},
		{Name: "status", Type: field.TypeInt, Default: 0},
		{Name: "priority", Type: field.TypeInt, Default: 0},
		{Name: "scheduled_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "args", Type: field.TypeJSON},
	}
	// DownloadQueueItemsTable holds the schema information for the "download_queue_items" table.
	DownloadQueueItemsTable = &schema.Table{
		Name:       "download_queue_items",
		Columns:    DownloadQueueItemsColumns,
		PrimaryKey: []*schema.Column{DownloadQueueItemsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "downloadqueueitem_status_scheduled_at",
				Unique:  false,
				Columns: []*schema.Column{DownloadQueueItemsColumns[2], DownloadQueueItemsColumns[4]},
			},
			{
				Name:    "downloadqueueitem_status_group_key",
				Unique:  false,
				Columns: []*schema.Column{DownloadQueueItemsColumns[2], DownloadQueueItemsColumns[1]},
			},
		},
	}
	// EtagCachesColumns holds the columns for the "etag_caches" table.
	EtagCachesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "etag", Type: field.TypeString},
		{Name: "last_updated", Type: field.TypeTime},
	}
	// EtagCachesTable holds the schema information for the "etag_caches" table.
	EtagCachesTable = &schema.Table{
		Name:       "etag_caches",
		Columns:    EtagCachesColumns,
		PrimaryKey: []*schema.Column{EtagCachesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "etagcache_last_updated",
				Unique:  false,
				Columns: []*schema.Column{EtagCachesColumns[2]},
			},
		},
	}
	// ImportEntriesColumns holds the columns for the "import_entries" table.
	ImportEntriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "title", Type: field.TypeString},
		{Name: "status", Type: field.TypeInt, Default: 0},
		{Name: "action", Type: field.TypeInt, Default: 0},
		{Name: "info", Type: field.TypeJSON, Nullable: true},
		{Name: "series", Type: field.TypeJSON, Nullable: true},
		{Name: "continue_after_chapter", Type: field.TypeFloat64, Nullable: true},
	}
	// ImportEntriesTable holds the schema information for the "import_entries" table.
	ImportEntriesTable = &schema.Table{
		Name:       "import_entries",
		Columns:    ImportEntriesColumns,
		PrimaryKey: []*schema.Column{ImportEntriesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "importentry_status_action",
				Unique:  false,
				Columns: []*schema.Column{ImportEntriesColumns[2], ImportEntriesColumns[3]},
			},
		},
	}
	// LatestSeriesColumns holds the columns for the "latest_series" table.
	LatestSeriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "suwayomi_source_id", Type: field.TypeString},
		{Name: "provider", Type: field.TypeString},
		{Name: "language", Type: field.TypeString, Default: ""},
		{Name: "url", Type: field.TypeString, Nullable: true},
		{Name: "title", Type: field.TypeString, Default: ""},
		{Name: "thumbnail_url", Type: field.TypeString, Nullable: true},
		{Name: "artist", Type: field.TypeString, Nullable: true},
		{Name: "author", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "genre", Type: field.TypeJSON, Nullable: true},
		{Name: "fetch_date", Type: field.TypeTime},
		{Name: "chapter_count", Type: field.TypeInt64, Nullable: true},
		{Name: "latest_chapter", Type: field.TypeFloat64, Nullable: true},
		{Name: "latest_chapter_title", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString, Default: "UNKNOWN"},
		{Name: "in_library", Type: field.TypeInt, Default: 0},
		{Name: "chapters", Type: field.TypeJSON, Nullable: true},
		{Name: "series_id", Type: field.TypeUUID, Nullable: true},
	}
	// LatestSeriesTable holds the schema information for the "latest_series" table.
	LatestSeriesTable = &schema.Table{
		Name:       "latest_series",
		Columns:    LatestSeriesColumns,
		PrimaryKey: []*schema.Column{LatestSeriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "latest_series_series_latest_series",
				Columns:    []*schema.Column{LatestSeriesColumns[18]},
				RefColumns: []*schema.Column{SeriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "latestseries_suwayomi_source_id",
				Unique:  false,
				Columns: []*schema.Column{LatestSeriesColumns[1]},
			},
			{
				Name:    "latestseries_fetch_date",
				Unique:  false,
				Columns: []*schema.Column{LatestSeriesColumns[11]},
			},
			{
				Name:    "latestseries_title",
				Unique:  false,
				Columns: []*schema.Column{LatestSeriesColumns[5]},
			},
		},
	}
	// ProviderStoragesColumns holds the columns for the "provider_storages" table.
	ProviderStoragesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "apk_name", Type: field.TypeString},
		{Name: "pkg_name", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "lang", Type: field.TypeString, Default: ""},
		{Name: "version_code", Type: field.TypeInt64, Default: 0},
		{Name: "is_storage", Type: field.TypeBool, Default: true},
		{Name: "is_disabled", Type: field.TypeBool, Default: false},
		{Name: "mappings", Type: field.TypeJSON, Nullable: true},
	}
	// ProviderStoragesTable holds the schema information for the "provider_storages" table.
	ProviderStoragesTable = &schema.Table{
		Name:       "provider_storages",
		Columns:    ProviderStoragesColumns,
		PrimaryKey: []*schema.Column{ProviderStoragesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "providerstorage_name_lang",
				Unique:  false,
				Columns: []*schema.Column{ProviderStoragesColumns[3], ProviderStoragesColumns[4]},
			},
		},
	}
	// SeriesColumns holds the columns for the "series" table.
	SeriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "title", Type: field.TypeString},
		{Name: "thumbnail_url", Type: field.TypeString, Default: ""},
		{Name: "artist", Type: field.TypeString, Default: ""},
		{Name: "author", Type: field.TypeString, Default: ""},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "genre", Type: field.TypeJSON, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "UNKNOWN"},
		{Name: "storage_path", Type: field.TypeString, Nullable: true},
		{Name: "type", Type: field.TypeString, Nullable: true},
		{Name: "chapter_count", Type: field.TypeInt, Default: 0},
		{Name: "pause_downloads", Type: field.TypeBool, Default: false},
	}
	// SeriesTable holds the schema information for the "series" table.
	SeriesTable = &schema.Table{
		Name:       "series",
		Columns:    SeriesColumns,
		PrimaryKey: []*schema.Column{SeriesColumns[0]},
	}
	// SeriesProvidersColumns holds the columns for the "series_providers" table.
	SeriesProvidersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "suwayomi_id", Type: field.TypeInt, Default: 0},
		{Name: "provider", Type: field.TypeString},
		{Name: "scanlator", Type: field.TypeString, Default: ""},
		{Name: "url", Type: field.TypeString, Nullable: true},
		{Name: "title", Type: field.TypeString, Default: ""},
		{Name: "language", Type: field.TypeString, Default: ""},
		{Name: "thumbnail_url", Type: field.TypeString, Nullable: true},
		{Name: "artist", Type: field.TypeString, Nullable: true},
		{Name: "author", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "genre", Type: field.TypeJSON, Nullable: true},
		{Name: "fetch_date", Type: field.TypeTime, Nullable: true},
		{Name: "chapter_count", Type: field.TypeInt64, Nullable: true},
		{Name: "continue_after_chapter", Type: field.TypeFloat64, Nullable: true},
		{Name: "is_title", Type: field.TypeBool, Default: false},
		{Name: "is_cover", Type: field.TypeBool, Default: false},
		{Name: "is_unknown", Type: field.TypeBool, Default: false},
		{Name: "importance", Type: field.TypeInt, Default: 0},
		{Name: "is_disabled", Type: field.TypeBool, Default: false},
		{Name: "is_uninstalled", Type: field.TypeBool, Default: false},
		{Name: "status", Type: field.TypeString, Default: "UNKNOWN"},
		{Name: "chapters", Type: field.TypeJSON, Nullable: true},
		{Name: "series_id", Type: field.TypeUUID},
	}
	// SeriesProvidersTable holds the schema information for the "series_providers" table.
	SeriesProvidersTable = &schema.Table{
		Name:       "series_providers",
		Columns:    SeriesProvidersColumns,
		PrimaryKey: []*schema.Column{SeriesProvidersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "series_providers_series_providers",
				Columns:    []*schema.Column{SeriesProvidersColumns[23]},
				RefColumns: []*schema.Column{SeriesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "seriesprovider_series_id",
				Unique:  false,
				Columns: []*schema.Column{SeriesProvidersColumns[23]},
			},
			{
				Name:    "seriesprovider_suwayomi_id",
				Unique:  false,
				Columns: []*schema.Column{SeriesProvidersColumns[1]},
			},
			{
				Name:    "seriesprovider_title_language",
				Unique:  false,
				Columns: []*schema.Column{SeriesProvidersColumns[5], SeriesProvidersColumns[6]},
			},
			{
				Name:    "seriesprovider_provider_language_scanlator",
				Unique:  false,
				Columns: []*schema.Column{SeriesProvidersColumns[2], SeriesProvidersColumns[6], SeriesProvidersColumns[3]},
			},
		},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeString},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
	}
	// SourceEventsColumns holds the columns for the "source_events" table.
	SourceEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "source_id", Type: field.TypeString},
		{Name: "source_name", Type: field.TypeString},
		{Name: "language", Type: field.TypeString},
		{Name: "event_type", Type: field.TypeString},
		{Name: "status", Type: field.TypeString},
		{Name: "duration_ms", Type: field.TypeInt64},
		{Name: "error_message", Type: field.TypeString, Nullable: true},
		{Name: "error_category", Type: field.TypeString, Nullable: true},
		{Name: "items_count", Type: field.TypeInt, Nullable: true},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// SourceEventsTable holds the schema information for the "source_events" table.
	SourceEventsTable = &schema.Table{
		Name:       "source_events",
		Columns:    SourceEventsColumns,
		PrimaryKey: []*schema.Column{SourceEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sourceevent_source_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{SourceEventsColumns[1], SourceEventsColumns[11]},
			},
			{
				Name:    "sourceevent_event_type_created_at",
				Unique:  false,
				Columns: []*schema.Column{SourceEventsColumns[4], SourceEventsColumns[11]},
			},
			{
				Name:    "sourceevent_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{SourceEventsColumns[5], SourceEventsColumns[11]},
			},
			{
				Name:    "sourceevent_created_at",
				Unique:  false,
				Columns: []*schema.Column{SourceEventsColumns[11]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DownloadQueueItemsTable,
		EtagCachesTable,
		ImportEntriesTable,
		LatestSeriesTable,
		ProviderStoragesTable,
		SeriesTable,
		SeriesProvidersTable,
		SettingsTable,
		SourceEventsTable,
	}
)

func init() {
	LatestSeriesTable.ForeignKeys[0].RefTable = SeriesTable
	SeriesProvidersTable.ForeignKeys[0].RefTable = SeriesTable
}
