// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DownloadQueueItem is the predicate function for downloadqueueitem builders.
type DownloadQueueItem func(*sql.Selector)

// EtagCache is the predicate function for etagcache builders.
type EtagCache func(*sql.Selector)

// ImportEntry is the predicate function for importentry builders.
type ImportEntry func(*sql.Selector)

// LatestSeries is the predicate function for latestseries builders.
type LatestSeries func(*sql.Selector)

// ProviderStorage is the predicate function for providerstorage builders.
type ProviderStorage func(*sql.Selector)

// Series is the predicate function for series builders.
type Series func(*sql.Selector)

// SeriesProvider is the predicate function for seriesprovider builders.
type SeriesProvider func(*sql.Selector)

// Setting is the predicate function for setting builders.
type Setting func(*sql.Selector)

// SourceEvent is the predicate function for sourceevent builders.
type SourceEvent func(*sql.Selector)
