// Code generated by ent, DO NOT EDIT.

package importentry

import (
	"entgo.io/ent/dialect/sql"
	"github.com/technobecet/kaizoku-go/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldContainsFold(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldEQ(FieldTitle, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldEQ(FieldStatus, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v int) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldEQ(FieldAction, v))
}

// ContinueAfterChapter applies equality check predicate on the "continue_after_chapter" field. It's identical to ContinueAfterChapterEQ.
func ContinueAfterChapter(v float64) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldEQ(FieldContinueAfterChapter, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldContainsFold(FieldTitle, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldLTE(FieldStatus, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v int) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v int) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...int) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...int) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v int) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v int) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v int) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v int) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldLTE(FieldAction, v))
}

// InfoIsNil applies the IsNil predicate on the "info" field.
func InfoIsNil() predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldIsNull(FieldInfo))
}

// InfoNotNil applies the NotNil predicate on the "info" field.
func InfoNotNil() predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldNotNull(FieldInfo))
}

// SeriesIsNil applies the IsNil predicate on the "series" field.
func SeriesIsNil() predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldIsNull(FieldSeries))
}

// SeriesNotNil applies the NotNil predicate on the "series" field.
func SeriesNotNil() predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldNotNull(FieldSeries))
}

// ContinueAfterChapterEQ applies the EQ predicate on the "continue_after_chapter" field.
func ContinueAfterChapterEQ(v float64) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldEQ(FieldContinueAfterChapter, v))
}

// ContinueAfterChapterNEQ applies the NEQ predicate on the "continue_after_chapter" field.
func ContinueAfterChapterNEQ(v float64) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldNEQ(FieldContinueAfterChapter, v))
}

// ContinueAfterChapterIn applies the In predicate on the "continue_after_chapter" field.
func ContinueAfterChapterIn(vs ...float64) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldIn(FieldContinueAfterChapter, vs...))
}

// ContinueAfterChapterNotIn applies the NotIn predicate on the "continue_after_chapter" field.
func ContinueAfterChapterNotIn(vs ...float64) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldNotIn(FieldContinueAfterChapter, vs...))
}

// ContinueAfterChapterGT applies the GT predicate on the "continue_after_chapter" field.
func ContinueAfterChapterGT(v float64) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldGT(FieldContinueAfterChapter, v))
}

// ContinueAfterChapterGTE applies the GTE predicate on the "continue_after_chapter" field.
func ContinueAfterChapterGTE(v float64) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldGTE(FieldContinueAfterChapter, v))
}

// ContinueAfterChapterLT applies the LT predicate on the "continue_after_chapter" field.
func ContinueAfterChapterLT(v float64) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldLT(FieldContinueAfterChapter, v))
}

// ContinueAfterChapterLTE applies the LTE predicate on the "continue_after_chapter" field.
func ContinueAfterChapterLTE(v float64) predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldLTE(FieldContinueAfterChapter, v))
}

// ContinueAfterChapterIsNil applies the IsNil predicate on the "continue_after_chapter" field.
func ContinueAfterChapterIsNil() predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldIsNull(FieldContinueAfterChapter))
}

// ContinueAfterChapterNotNil applies the NotNil predicate on the "continue_after_chapter" field.
func ContinueAfterChapterNotNil() predicate.ImportEntry {
	return predicate.ImportEntry(sql.FieldNotNull(FieldContinueAfterChapter))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ImportEntry) predicate.ImportEntry {
	return predicate.ImportEntry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ImportEntry) predicate.ImportEntry {
	return predicate.ImportEntry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ImportEntry) predicate.ImportEntry {
	return predicate.ImportEntry(sql.NotPredicates(p))
}
